- controller/api/__init__.py
- controller/api/tests/test_app.py
- controller/api/tests/test_build.py
- controller/api/tests/test_config.py
- controller/api/tests/test_domain.py
- controller/api/tests/test_perm.py
- controller/api/tests/test_release.py
- controller/api/views.py
- docs/reference/api-v1.1.rst
- tests/perms_test.go
Authenticated users who were not given explicit permission
to view or modify an app were still allowed to create new releases,
run commands, retrieve logs etc. This makes those requests return a 404
if the user should not be able to see the application.
Please let me know if I missed any loopholes and I will happily correct them.
closes #2820, refs #2811
> fix(controller): disallow unauthorized users from modifying apps

- contrib/coreos/user-data.example
The debug-etcd service added in #2779 has an issue - the `command: start`
is invalid.
This doesn't *appear* to break things, but the service that handles
cloud-config parsing will error out, which can result in services not starting.
> fix(contrib/coreos): fix debug-etcd service

- contrib/ec2/gen-json.py
The changes in #2803 unfortunately don't address all of the etcd-related
performance issues. Provisioning Deis can still cause etcd timeouts.
Moving the etcd journal to the unused ephemeral disk allows etcd to
write to a very fast disk, resulting in fewer etcd/fleet issues.
refs #2793
refs #2506
> feat(contrib/ec2): use ephemeral drive for etcd journal

- controller/api/permissions.py
- controller/api/tests/test_app.py
- controller/api/tests/test_release.py
- controller/api/views.py
Authenticated users who were not given explicit permission to view
or modify an application were still allowed to delete other user's
applications, should the unauthorized user know what the ID of the
application would be. This returns a 404 message if the user is
unauthorized to see the application.
Because we were calling get_object_or_404(), we were not performing
any authorization against the API call. Calling self.get_object() is
the preferred method to retrieve an object since it authenticates
against the classes' permissions classes to ensure that the user is
authorized to see the application.
This also fixes up an issue where administrators were not explicitly
given permission to an app. They fell through the same "unauthorized"
issue as above.
closes #2845
closes #2846
> fix(controller): disallow unauthorized users from deleting apps

- contrib/ec2/deis.template.json
- docs/managing_deis/configure-load-balancers.rst
Amazon added support for setting the ELB timeout directly from
CloudFormation on the 24th of December.
This commit removes the documentation which tells the user to change it
manually, as that is no longer needed, and sets it to 1200s.
See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-connectionsettings.html
> feat(contrib/ec2): Set ELB timeout to 1200s

- controller/api/tests/test_app.py
- controller/api/tests/test_container.py
When testing the security holes found recently (#2826), we found a few response
codes that were not what was to be expected. Adding test coverage around
this such that we can address these tests in future refactors.
> test(controller): add expected unit test failures for response codes

- controller/bin/boot
- controller/deis/settings.py
- controller/scheduler/fleet.py
- controller/templates/confd_settings.py
- docs/customizing_deis/controller_settings.rst
This exposes a configurable hostname type to Docker container through
fleet unit files.
Three hostname types are supported:
- default     : standard Docker hostname
- application : application hostname (e.g. my-app.v54.web.1)
- server      : Core OS hostname
This fixes #2835 and is an alternative to #2428, which got rejected.
It is necessary when using a monitoring solution like New Relic.
> feat(controller): add hostname exposing to units

- controller/requirements.txt
- docs/docs_requirements.txt
See https://docs.djangoproject.com/en/dev/releases/1.6.9/ for details.
> chore(controller): update Django to 1.6.9 bugfix release

- builder/image/slugbuilder/builder/install-buildpacks
This release provides 2 very importan updates: 
1. the option to specify the [npm version](https://github.com/heroku/heroku-buildpack-nodejs/tree/yoga#specify-an-npm-version) to use
2. support for [scoped packages](https://docs.npmjs.com/misc/scope) (using npm 2.1.x)
3. correct support for chaining buildpacks
> feat(slugbuilder): update nodejs buildpack to v64 (yoga release)

- client/deis.py
If you have a violating key in your known_hosts file, it will cause
you to fail adding the git remote, even though the app is already
created on the controller's side. Validating that the server's key
is correct should happen at git push to match Heroku.
> fix(client): remove fetch call from apps:create

- database/build.sh
A new build of the current content of deis-database produces this error:
```
Processing /tmp/wal-e
/usr/local/lib/python2.7/dist-packages/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '0.8rc1' instead of '0.8c1'.
self.metadata.version,
Collecting gevent>=0.13.1 (from wal-e==0.8rc1)
Downloading gevent-1.0.1.tar.gz (1.5MB)
Collecting boto>=2.6.0 (from wal-e==0.8rc1)
Downloading boto-2.35.1-py2.py3-none-any.whl (1.3MB)
Collecting azure>=0.7.0 (from wal-e==0.8rc1)
Downloading azure-0.9.0.zip (107kB)
Collecting python-swiftclient>=1.8.0 (from wal-e==0.8rc1)
Downloading python_swiftclient-2.3.1-py2.py3-none-any.whl (51kB)
Collecting python-keystoneclient>=0.4.2 (from wal-e==0.8rc1)
Downloading python_keystoneclient-1.0.0-py2.py3-none-any.whl …
```
> fix(database): update wal-e because error in python-daemon

- builder/image/bin/boot
- contrib/coreos/user-data.example
An additional address range, 100.64.0.0/10, is reserved by RFC 6598.
This is also the private address space used by Azure, so this will
also allow us to support Azure without building a custom builder
component just for Azure, which was the previously-planned approach.
refs #2824
> feat(*): support RFC 6598 for insecure registries

- client/deis.py
Whoami command needs to display both username and controller. Useful
when using multiple deis clusters.
> feat(client): Add controller to whoami command.

- Vagrantfile
- contrib/ec2/deis.template.json
- contrib/rackspace/provision-rackspace-cluster.sh
- docs/installing_deis/baremetal.rst
- docs/installing_deis/gce.rst
Note that I didn't bump the minimum required CoreOS version in the
docs (as nothing in this release is mandatory), but I did bump
the Vagrantfile version so Jenkins tests the latest stable release.
> chore(*): bump CoreOS to 522.5.0

- docs/managing_deis/upgrading-deis.rst
etcd/fleet incompatibilities used to be a problem, but not so
much anymore - we should stop calling that out.
ping @gabrtv
> docs(managing_deis): clarify reasons for disabling CoreOS upgrades

- docs/managing_deis/operational_tasks.rst
- docs/using_deis/register-user.rst
@brynary suggested that it'd be helpful to note how to disable user registration after instructing users to create their superuser account.
> docs(using_deis): add disabling registration docs to user creation

- deisctl/config/config.go
- deisctl/config/config_test.go
- docs/managing_deis/ssl-endpoints.rst
This PR fixes #2712 and cleans up the config logic in `deisctl`:
* defines `fileKeys` which are read from local files
* defines `b64Keys` which are base64-encoded before stored (needed for `sshPrivateKey`)
* `valueForPath` is factored out with corresponding test coverage
I've also added documentation on how to configure the Deis routers to terminate SSL.
> Refactor deisctl config logic and add docs on Router SSL

- builder/image/templates/builder
This PR reworks the process type resolution logic in the builder.  As of @53204c1ec, it appears we stopped respecting `Procfile` as an override for default process types.  Is that right @bacongobbler?
Fixes #2874 and #2637.
```console
$ cat > Procfile <<EOF
web: bundle exec ruby web.rb -p ${PORT:-5000}
worker: bash -c "while true; do echo hi; sleep 5; done"
EOF
$ git add Procfile 
$ git commit -m 'add worker to Procfile'
[master 2a9ef52] add worker to Procfile
1 file changed, 1 insertion(+)
$ git push deis master
...
-----> Discovering process types
Procfile declares types -> web, worker
Default process types for Ruby -> rake, console, web
-----> Compiled slug size is 15M
...
$ deis scale worker=1
Scaling processes... but first, coffee!
done in 31s
=== ruby Processes
--- web: 
web.1 up …
```
> fix(builder): allow procfile to override default process types

- store/base/templates/ceph.conf
Commit 690b380 had a typo which made the `mon host` config entry for
Ceph contain IP addresses, not hostnames. This doesn't seem to
be an issue for day-to-day operations, but could have unforeseen
consequences. It's best to fix this up.
> fix(store): use hostnames for mon host

- Vagrantfile
The paravirtualized "virtio" adapter is the default when creating a CoreOS 522.5.0 vagrant / VirtualBox instance, so this stanza is no longer needed.
> ref(Vagrantfile): remove redundant virtio NIC section

- builder/Makefile
Without this any error is omitted by the for loop.
To test this change any .go to contain an error and compile the builder `make -C builder/ build`.
> fix(builder): exit if an error occur compiling go

- controller/api/authentication.py
- controller/api/models.py
- controller/api/serializers.py
- controller/api/tests/test_app.py
- controller/api/tests/test_auth.py
- controller/api/tests/test_build.py
- controller/api/tests/test_config.py
- controller/api/tests/test_domain.py
- controller/api/tests/test_release.py
- controller/api/urls.py
- controller/api/views.py
- controller/api/viewsets.py
- controller/deis/settings.py
- controller/requirements.txt
- docs/docs_requirements.txt
- tests/apps_test.go
- tests/keys_test.go
this is the beginning of #2854. Considering that bumping to DRF 3.0.3 broke a lot of old functionality, I wanted to mainly focus on bumping DRF before completely refactoring so there's less to review.
TODO:
> chore(controller): bump django-rest-framework to 3.0.3

- contrib/coreos/user-data.example
In the logs I saw this:
`Jan 21 18:06:05 nodo-3 sh[27968]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]`
Usually this means that something is wrong in the cluster but everything was working just fine (I even checked the etcd leader stats :) )
The problem is the default for `nf_conntrack_max`: 65536 [docs](https://www.kernel.org/doc/Documentation/networking/nf_conntrack-sysctl.txt)
This number sound high but every docker container uses iptables with connection tracking so 200 containers using mongodb with replication (1 connection per mongodb node per application) and that number is a joke.
To check if there is a problem with  nf_conntrack run: `dmesg | grep conntrack`
If it shows something like `nf_conntrack: table full, dropping …
> fix(security): increase max conntrack connections

- contrib/gce/create-gce-user-data
fix (contrib/gce/create-gce-user-data): replace discovery_url with discovery
This simply changes the discovery_url to discovery to allow the nodes in gce set their ETCD_DISCOVERY
> fix (contrib/gce/create-gce-user-data): replace discovery_url with discovery

- docs/conf.py
Doc generation creates a local_settings.py file, because at one time having `SECRET_KEY` unset caused an error when importing Django code. That was essentially a temp file that was never cleaned up, and it no longer seems to be necessary.
> ref(docs): remove local_settings.py hack for secret key

- controller/requirements.txt
See https://github.com/lukearno/static/compare/v1.0.2...v1.1.1
TESTING:
This is a minor update that affects only resources served at the `/static/` prefix, copied there by `manage.py collectstatic`.
Do `deisctl config controller set webEnabled=1` and log in at the admin URL, then visit http://deis.local3.deisapp.com/apps/ and verify that CSS and images are served correctly.
> chore(controller): update static wsgi library to v1.1.1

- .gitignore
- docs/conf.py
- docs/docs_requirements.txt
To automatically generate python code documentation, Sphinx needs to import the code, which requires Django, which requires a database driver. This change sets the driver to python's built-in `sqlite3` at runtime to simplify requirements for building the docs.
Refs #2887.
> ref(docs): remove postgresql from doc generation requirements

- builder/image/templates/gitreceive
This avoids that two or more users to run `git push` in the same app while the application is being built (create a pseudo lock during the push)
> feat(builder): disable simultaneous push in the same repository

- docs/faq.rst
Thanks again to the Chinese DockerOne community for this great work! See #2852 for the details.
I used Google translate to spot-check several sections, and the content seems good. It would be nice to include multiple translations at http://docs.deis.io/ directly, but for now providing a link is better than nothing.
Closes #2852.
> docs(faq): added a link to unofficial Chinese documentation

- tests/utils/utils.go
The artificial delay in `RunCommandWithStdoutStderr` has always been there, without explanation. I couldn't discern why, so I removed it and ran test-integration.sh three times without any errors. Hopefully Jenkins agrees, as this shaves a couple minutes off the overall test time.
> ref(tests): remove unnecessary time.Sleep()

- deisctl/cmd/cmd.go
- deisctl/units/deis-store-admin.service
- store/Makefile
- store/admin/Dockerfile.template
- store/admin/bin/boot
Adds a new optional component, `deis-store-admin`, to aid in diagnosing and recovering from issues with store.
Most of the store containers only write the Ceph config file once before the /bin/boot script execs the Ceph daemon, so when a user comes along and tries to query cluster state, it's likely that he's using a very old config file and will see a bunch of monitor faults. This admin container uses confd to rewrite the config file constantly, ensuring that the latest cluster state is reflected in the config.
This change also moves the Troubleshooting Store docs into its own page, since they were overwhelming the Troubleshooting Deis docs. I had to include a toctree in the main Troubleshooting docs to satisfy Sphinx.
closes #2925
> feat(store): add store-admin container

- router/image/templates/deis.conf
With this change, applications can both listen on port 80 and port 443
when application SSL is enabled. Applications can use the guide at
https://help.openshift.com/hc/en-us/articles/202398810-How-to-redirect-traffic-to-HTTPS-
to redirect applications to their respective protocol.
refs #2786
> feat(router): listen on port 80 for platform SSL

- docs/installing_deis/gce.rst
closes #2722 
We already [direct the user to change directories](http://docs.deis.io/en/latest/installing_deis/gce/#cloud-init) over to `contrib/gce` in the docs so no action required there.
> docs(installing_deis): add --use_compute_key option flag

- contrib/coreos/user-data.example
When validating the ``user-data.example`` in https://coreos.com/validate/ it warns (or errors?) about 'Line 19:incorrect type for "etcd_request_timeout" (want float64).'
Also using the ``user-data.example`` (with token added to ``coreos.fleet.discovery``) it failed to discover the cluster nodes (but worked after lunch when I changed the ``3`` to ``3.0`` and reinited the cluster) haven't reproduced it, could just be coincidence. Used ``CoreOS 522.5.0`` on digitalocean.
Solution: Use ``float64`` as the value type for ``etcd_request_timeout``
> fix(contrib/coreos) etdcd_request_timeout value type

- Vagrantfile
- contrib/ec2/deis.template.json
- contrib/rackspace/provision-rackspace-cluster.sh
- docs/installing_deis/baremetal.rst
- docs/installing_deis/gce.rst
This release includes a glibc fix for CVE-2015-0235.
> chore(*): bump CoreOS to 522.6.0

- docs/using_deis/manage-application.rst
```console
$ deis perms:add -h
Found no matching command, try `deis help`
Usage: deis <command> [<args>...]
```
> fix(docs): refer to correct "deis perms:create" command

- controller/api/permissions.py
- controller/api/tests/test_perm.py
- controller/api/views.py
The majority of code shifting was done earlier in #2898, so this optimizes the rest of the viewsets to use more generic calls, specifically the hooks and app perm viewsets which were basically re-implementing the permission calls.
closes #2854
> ref(controller): API view refactor

- builder/image/Dockerfile
- builder/image/templates/builder
- builder/image/templates/gitreceive
Changed the builder from running an entire script as root through sudo, to just a single command.
This also fixes #1843, which happened since the builder script was ran as root, and we executed "git gc" as root, causing files and folders to "randomly" be owned by root:root instead of git:git
> ref(builder): Remove use of root in gitreceive

- logger/Dockerfile
- logger/Makefile
This issue was brought up when building a new release of images for
deployment. The logger relied on `go get` to fetch dependencies. Because
there was a breaking change in the etcd client[1], the logger failed to
connect to the cluster. We have moved over to a global Godeps for
managing dependencies, so this changes the compilation on the host to
follow the other components' build process.
[1]: https://github.com/coreos/go-etcd/commit/5348c80bde6223fa53c48ef546b4802db69b1d70#diff-33c1223aac4ef741731cc8c73b4d7777L295
> fix(logger): use godep for dependencies

- Vagrantfile
This reverts commit 10f80cf8528cb669780bf686bafdd7108ec5e83a.
Many tears were shed because the testing infrastructure was choking
due to having too little memory. Trying to run Deis with too little
memory invites a slew of issues.
If Deis doesn't work well on 1GB, we shouldn't easily allow people
to run it that way. Our system requirements documentation even
calls out that instances should have at least 2GB minimum. Folks can
always manually edit the file if they want to try 1GB, but in that case
it's clear that it's not recommended.
Deis is a distributed system - 8GB of RAM really isn't a ridiculous requirement.
There's always Digital Ocean test machines, or Dokku for 1-node production workloads.
> Revert "fix(contrib): use 1GB per VM"

- builder/image/slugbuilder/builder/install-buildpacks
Try to shallow clone buildpack repositories before falling back to deep cloning. This improves clone times significantly.
Shallow cloning only works for tags and branches, but not for a specific commit.
Benchmark:
```
localhost:deis johannes$ time git clone https://github.com/heroku/heroku-buildpack-ruby.git
Cloning into 'heroku-buildpack-ruby'...
...
real	0m12.764s
user	0m0.610s
sys	0m0.565s
localhost:deis johannes$ rm -rf heroku-buildpack-ruby/
localhost:deis johannes$ time git clone --branch v129 --depth 1 https://github.com/heroku/heroku-buildpack-ruby.git
Cloning into 'heroku-buildpack-ruby'...
...
real	0m1.657s
user	0m0.078s
sys	0m0.092s
```
This saves around 10 seconds per buildpack and we are cloning 7 buildpacks using a tag currently.
> feat(builder): Try shallow cloning buildpack repos

- docs/managing_deis/backing_up_data.rst
We no longer need to maintain the Deis fork of s3cmd, as the necessary
patches for Ceph have been merged upstream.
When this commit is merged, we should delete https://github.com/deis/s3cmd
closes #3002
> docs(managing_deis): use non-forked s3cmd

- builder/image/slugbuilder/builder/install-buildpacks
Both buildpacks are now also tagged when released.
Changes:
https://github.com/heroku/heroku-buildpack-gradle/compare/24a8ebe...v12
https://github.com/heroku/heroku-buildpack-play/compare/9c137b4...v22
This improves https://github.com/deis/deis/pull/2988 even further. @bacongobbler do you have example apps to tests those buildpacks?  Otherwise I would create them.
> chore(builder): Updated gradle and play buildpack

- builder/Makefile
- cache/Makefile
- controller/Makefile
- database/Makefile
- logger/Makefile
- logspout/Makefile
- publisher/Makefile
- registry/Makefile
- router/Makefile
- store/Makefile
When running `make build`, sometimes components fail to build,
aborting the Makefile run. After fixing the issue, building again,
and running `make dev-release`, some components
have already been tagged and emit an error like "Tag asdf already
references image bcde".
This commit makes `docker tag` force the tag, preventing
a semi-successful build from preventing releases.
replaces #2998
> fix(*): force tags in Makefiles

- logspout/README.md
A tiny tweak to the logspout readme to include the correct Docker incantation to route logs to a syslog endpoint.
> docs(logspout): Fix remote syslog example

- logger/syslogd/syslogd.go
Currently, logger expects logRoot to exist. If it doesn't,
logger will throw errors hundreds of times per second as it tries
to write a logfile.
This commit makes logger create logRoot on startup.
Note that this doesn't necessarily close #2398, as it's conceivable that permissions could change (or directories removed) while logger is already running, so a single log file write could still fail.
refs #2398
> fix(logger): create logRoot on startup

- Godeps/Godeps.json
- router/Dockerfile
- tests/bin/setup-node.sh
- tests/etcdutils/Dockerfile
Besides keeping things up-to-date, I'm working on a test refactoring that will require go 1.4 or later.
> chore(*): update to go 1.4.1

- logspout/README.md
- logspout/logspout.go
This commit enables users to specify their own datetime format
by supplying the `DATETIME_FORMAT` environment variable when
using logspout. If none is supplied, logspout will continue to use
`DEIS_DATETIME_FORMAT`.
closes #3032
> feat(logspout): use custom datetime

- builder/README.md
- builder/image/bin/boot
- builder/tests/builder_test.go
- deisctl/units/deis-builder.service
Docker at one point had to be coerced into using `btrfs` on CoreOS--which had to be overridden with `aufs` for functional testing on non-`btrfs` hosts. In testing with CoreOS alpha, our choice of `btrfs` fails, since it won't work on a host filesystem formatted with `ext4`.
This change removes the `--storage-driver` override code and allows Docker(-in-Docker) to choose the best driver. This is still `btrfs` when the host filesystem matches--I verified several times inside the container. On CoreOS alpha, Docker chooses `devicemapper` (both `aufs` and `overlay` fail with "not supported"). This would be fine except there are no `/dev/loopN` devices yet, only the master `/dev/loop-control` device, and Docker will fail with "no loopback devices available." Calling `losetup -f` once before …
> Let docker-in-docker choose its storage driver

- builder/image/templates/check-repos
After `deis apps:destroy`, deis-builder will run the [`check-repos`](https://github.com/deis/deis/blob/master/builder/image/templates/check-repos#L21) script, which does `docker rmi` on dangling images. But it includes the header line:
```console
$ docker images --filter "dangling=true" | awk '{ print $3 }'
IMAGE
ea77b2e915c0
71a345926906
77c93f4b07c3
```
causing useless Docker API output in deis-builder:
```log
Feb 06 23:48:37 deis-01 sh[4015]: [info] DELETE /v1.15/images/IMAGE?force=1
Feb 06 23:48:37 deis-01 sh[4015]: [ad780995] +job image_delete(IMAGE)
Feb 06 23:48:37 deis-01 sh[4015]: No such image: IMAGE
Feb 06 23:48:37 deis-01 sh[4015]: [ad780995] -job image_delete(IMAGE) = ERR (1)
Feb 06 23:48:37 deis-01 sh[4015]: [error] server.go:1207 Handler for DELETE /images/{name:.*} returned …
```
> fix(builder): ignore header when removing dangling docker images

- client/deis.py
Just making it clear that if an answer is not supplied, the default answer is no.
> fix(client): display default answer for auth:cancel prompt

- contrib/ec2/deis.template.json
Added a commit to remove provisioned iops as an option based on the discussion starting at https://github.com/deis/deis/pull/2973#discussion_r23650395
replaces #2973
> feat(ec2/cloudformation): use SSD EBS volumes by default

- deisctl/README.md
- deisctl/cmd/cmd.go
- deisctl/deisctl.go
- deisctl/units/deis-store-gateway.service
- store/Makefile
- store/gateway/bin/boot
Allow the store gateway to be scaled across multiple cluster nodes. This speeds up app rescheduling when the node hosting the gateway died
Helps with cases like https://github.com/deis/deis/issues/2920 
Basis for: https://github.com/deis/deis/issues/2725
An inactive gateway uses ~40mb memory, so it might make sense to schedule two gateways by default. https://www.dropbox.com/s/3uwz2brmn188ouu/Screenshot%202015-01-20%2015.36.00.png?dl=0
> feat(store): Scalable store-gateway

- contrib/azure/azure-coreos-cluster
The default is only 4 minutes, which frequently is too short to
successfully deploy an application.
closes #3053
> fix(contrib/azure): bump load balancer timeout to 20 minutes

- builder/image/bin/boot
- builder/image/bin/entry
- builder/image/slugbuilder/builder/build.sh
- builder/image/slugrunner/runner/init
- builder/image/templates/builder
- builder/tests/builder_test.go
- contrib/coreos/user-data.example
- deisctl/units/deis-builder.service
- docs/managing_deis/index.rst
- docs/managing_deis/using-a-proxy-server.rst
Proxy settings for coreos, builder, slugrunner, slugbuilder and docker
originally using /etc/environment, changed to /etc/environment_proxy to avoid current automations failures
closes #1734 -- edited by @bacongobbler
> feat(builder+docker+user-data): proxy settings

- controller/requirements.txt
- docs/docs_requirements.txt
See https://github.com/docker/docker-py/compare/0.6.0...0.7.2
Deis still uses only the `utils.parse_repository_tag` function, so this is purely housekeeping for now.
> chore(controller): update docker-py to 0.7.2

- builder/image/bin/boot
- builder/image/bin/entry
- builder/image/slugbuilder/builder/build.sh
- builder/image/slugrunner/runner/init
The proxy settings added in #2825 included a [workaround](https://github.com/deis/deis/blob/master/builder/tests/builder_test.go#L69) for the builder functional tests that does not work for `boot2docker`. The mount either fails or appears as a directory inside the container, which hangs up `/app/bin/entry/` or `/app/bin/boot`.
This changes each `source /etc/environment_proxy` line in builder to be conditional on whether that file exists. This fixes running the functional tests on a Mac, and seems to me more backward-compatible.
> fix(tests): source /etc/environment only if it exists

- controller/api/models.py
- controller/api/tests/test_container.py
Refs #3022, which still needs a cleanup fix for the fleet unit files that can be orphaned in that situation if a worker actually times out. ~~It wasn't reasonable to write a unit or integration test for this case unfortunately, IMHO, but I await the judgment of other maintainers.~~ Implemented a controller unit test that fails before this fix, passes afterward. :green_heart:
> fix(controller): ignore run procs when updating structure field

- controller/bin/boot
- controller/deis/gconf.py
- controller/requirements.txt
[The `-n` gunicorn option](http://docs.gunicorn.org/en/latest/settings.html#proc-name) wasn't working because the python [setproctitle](https://pypi.python.org/pypi/setproctitle/) library wasn't installed. This change also moves config options into a separate file (which facilitates signal handlers, which I've been [~~fighting~~ working with](https://github.com/deis/deis/issues/3035#issuecomment-74346603)), and renames the processes from "deis" to "deis-controller" so they're easier to identify on the host.
Before (cropped, but you get the idea):
```console
root@71881ad2ee93:/app# ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       662  0.0  0.1  18148  3180 ?        S    20:04   0:00 bash
root       680  0.0  0.1  15572  2132 ?        R+   20:04 …
```
> feat(controller): worker processes named as "deis-controller"

- router/image/templates/nginx.conf
I'm with @TrollWarlord and his comment in https://github.com/deis/deis/issues/1078#issuecomment-74879266, that leaking internal IPs is a bad thing.
The information, which instance handled which request, should be also available via `deis logs`.
> feat(router): Removed X-Deis-Upstream

- docs/contributing/hacking.rst
@mhahn pointed out in IRC that this command doesn't actually exist.
> docs(contributing): remove reference to `deisctl ssh`

- controller/web/templates/web/base.html
- controller/web/templates/web/support.html
- docs/theme/deis/layout.html
The footer links at http://docs.deis.io/en/latest/ and content in two controller web templates didn't match the footer links at http://deis.io/.  cc: @JoshuaSchnell.
> fix(docs+controller): update botbot.me and stackoverflow links

- controller/api/models.py
- controller/api/tests/test_container.py
When a process type is removed in a new build, the old containers are
not killed, and there's no way for the user to stop them. This change
will destroy the containers that no longer exist in the procfile.
closes #2930
> fix(controller): kill processes removed from procfile

- Makefile
- builder/Makefile
- builder/bin/generate-buildhook.go
- builder/bin/yaml2json-procfile.go
- builder/utils.go
- builder/utils_test.go
- cache/Makefile
- deisctl/Makefile
- logger/Makefile
- logspout/Makefile
- logspout/logspout.go
- pkg/time/time.go
- publisher/Makefile
- publisher/main.go
- publisher/server/publisher.go
- router/Makefile
- router/logger/stdout_formatter.go
- tests/Makefile
- tests/dockercli/dockercli.go
- tests/etcdutils/etcdutils.go
- tests/mock/mock.go
- tests/utils/utils.go
- version/version.go
This change cleans up some go language constructs and adds comments. It also makes the `go vet` command in `make test-style` mandatory. (`golint` always returns 0, so it can't easily be made mandatory, and that is not recommended anyway.)
I left a few warnings alone--all those in logspout, plus:
```
backend/fleet/fleet.go:6:6: type name will be used as fleet.FleetClient by other packages, and that stutters; consider calling this Client
syslog/message.go:9:6: type name will be used as syslog.SyslogMessage by other packages, and that stutters; consider calling this Message
```
That code originated elsewhere and I wasn't willing to change the package names without more thought. And logspout has no code comments at all, even upstream. :disappointed: 
Refs #2158, which we can still fix …
> ref(*): clean up most code linter warnings

- contrib/coreos/user-data.example
At some point CoreOS stopped loading the `nf_conntrack` kernel module by default, which broke the increase-nf_conntrack-connections.service we added in #2942. I tried to fix it in a more elegant way as @ineu suggested in #3105, but for some reason a /etc/modules-load.d/conntrack.conf file did not cause the module to be loaded on boot, so instead I added a `modprobe` command to the existing one-shot unit.
Before:
```console
core@deis-01 ~ $ sysctl net.netfilter.nf_conntrack_max
sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_max: No such file or directory
core@deis-01 ~ $ lsmod | grep conntrack
core@deis-01 ~ $ 
```
After:
```console
core@deis-01 ~ $ sysctl net.netfilter.nf_conntrack_max
net.netfilter.nf_conntrack_max = 262144
```
Closes #3105. ping @aledbf.
> fix(user-data): ensure nf_conntrack kernel module is loaded

- router/image/templates/deis.conf
This can break compatibility with IE6. Good news everyone! Microsoft released [a fix]. Tell your raging dinos to download [the msi].
Or just don't enforce ssl. For more see https://disablessl3.com/
[CVE-2014-3566](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-3566)
related #3097
[a fix]: https://support.microsoft.com/kb/3009008
[the msi]: http://go.microsoft.com/?linkid=9863266
> fix(router): disable SSLv3 CVE-2014-3566

- contrib/coreos/user-data.example
It makes no sense to download `deisctl` in every boot. It only delays the end of `systemd` boot
> feat(cloud-init): check if deisctl does not exists before install it

- builder/image/Dockerfile
- controller/registry/private.py
- registry/bin/boot
- registry/build.sh
I updated our private support [tweaks to docker-registry](https://github.com/deis/docker-registry/compare/docker:0.9.1...new-repository-import-v091) against v0.9.1 of docker-registry. This required fixing the tests and some code to match new validation and behavior. Then I fixed our docker checksum calculation to match the behavior in docker-registry's current tests, purged the `TarSum` class we don't use now, had deis-registry build from the new-repository-import-v091 branch, and updated builder's docker to 1.4.1.
Closes #3079.
> Update docker-registry to v0.9.1

- Vagrantfile
- contrib/azure/azure-coreos-cluster
- contrib/ec2/deis.template.json
- contrib/rackspace/provision-rackspace-cluster.sh
- docs/installing_deis/baremetal.rst
- docs/installing_deis/gce.rst
Notable changes in this version bump:
* Linux 3.18.2 (from 3.17.8)
* Docker 1.4.1 (from 1.3.3)
* fleet 0.9.0 (from 0.8.3)
closes #2745
refs #3046
> chore(*): bump CoreOS to 557.2.0

- controller/api/models.py
- controller/api/serializers.py
- controller/api/south_migrations/0020_auto__del_field_container_state.py
- controller/api/tests/test_container.py
- controller/api/tests/test_scheduler.py
- controller/deis/settings.py
- controller/registry/private.py
- controller/requirements.txt
- controller/scheduler/chaos.py
- controller/scheduler/fleet.py
- controller/scheduler/mock.py
- controller/scheduler/states.py
- controller/templates/confd_settings.py
- docs/docs_requirements.txt
Before, we relied on django-fsm to give us a general idea of what state
the container object in the model is at. This did not give users an
accurate idea of the state of their containers. Introducing a new
.state() method to the scheduler as well as changing Container.state to
call it's own scheduler's .state() method allows users to directly
understand what state their containers are in.
closes #2766 
closes #2987
This was thoroughly tested by hand since the controller does not wrap unit tests around fleet.py, but this should cover it :)
Points: PTAL at the systemdActiveStateMap in fleet.py and let me know if the mappings between the [dbus API's ActiveState](http://www.freedesktop.org/wiki/Software/systemd/dbus/) and what used to be DjangoFSM's JobState is correct.
> ref(controller): query fleet state

- database/tests/database_test.go
- registry/tests/registry_test.go
- tests/bin/prime-docker-images.sh
- tests/mock/mock.go
Test code hadn't been updated and was cleaning up some nonexistent containers instead of mock-store in the database and registry functional tests. Tested on my Mac and a Linux node several times, followed by `docker ps`.
Closes #3138.
> fix(tests): remove mock-store containers after functional tests

- builder/image/Dockerfile
- tests/bin/setup-node.sh
The endpoint https://get.docker.io is serving up a hearty breakfast of 504s today. The Docker [install docs](https://docs.docker.com/installation/ubuntulinux/) reference https://get.docker.com instead. This change points builder (and our CI node setup script) to what is apparently the preferred endpoint.
> fix(builder): install docker from get.docker.com

- contrib/coreos/user-data.example
By default systemd enables automatic coredumps. 
This could lead to a lot of problems like this one:
1. program consuming a lot of memory generates a core dump
2. the program will restart (systemd) and the same error will happen
3. if the disk space is the default, it will take only a couple of core dumps to fill the disk
4. (the important one) docker will die (no disk space available)
5. all the containers die
6. only rebooting the node solved the issue
Just in case this is a real example (my fault, I didn't resize the coreos disk)
http://www.freedesktop.org/software/systemd/man/systemd-coredump.html
> feat(cloud-init): disable automatic core dumps

- publisher/server/publisher.go
- publisher/server/publisher_test.go
> feat(publisher): Check if app port is open before publishing it. Fixes 3115

- docs/managing_deis/upgrading-deis.rst
The note for Deis v1.0.2 upgrades confuses folks, and considering
we're several versions beyond now, it's probably safe to remove
> docs(managing_deis): remove note on upgrading

- docs/installing_deis/install-platform.rst
- docs/installing_deis/vagrant.rst
Vagrant Users by default have to set the sshPrivateKey to .vagrant.d/insecure_private_key instead of the deis key. Even the make dev-cluster does this:
```shell
dev-cluster: discovery-url
vagrant up
ssh-add ~/.vagrant.d/insecure_private_key
deisctl config platform set sshPrivateKey=$(HOME)/.vagrant.d/insecure_private_key
deisctl config platform set domain=local3.deisapp.com
deisctl install platform
```
In all my installations and tests I always use this key instead the deis key, since the key is not used anywhere when you're in vagrant mode.
closes #2528 -- *edited by @bacongobbler*
> Docs: Missing note for Vagrant users

- docs/managing_deis/platform_logging.rst
- logger/drain/drain.go
- logger/syslogd/syslogd.go
Currently [platform logging](http://docs.deis.io/en/latest/managing_deis/platform_logging/) is done via `journalctl -o short -f | ncat --ssl logs2.papertrailapp.com 23654`
There are a couple of disadvantages to this:
1. A unit needs to be created (and customised) by end users.
2. Container logs aren't prefixed with application name.
I propose adding an external drain to `logger` that would send to external syslog servers in addition to the current write to disk process.
Interface would be:
```
$ deisctl config logs set drain/host logs2.papertrailapp.com
$ deisctl config logs set drain/port 23654
```
Logger pulls this configuration out of etcd and sends the messages on.
related #980
> Proposal: Platform-wide log drain

- builder/bin/get-app-values.go
- builder/image/slugbuilder/builder/build.sh
- builder/image/templates/builder
- builder/utils.go
- builder/utils_test.go
- tests/config_test.go
Builder is extremely finnicky, and the lack of tests around this workflow has caused issues like #3212.
This reverts #3129 and #3020, effectively re-opening #2980 and #3010 until we have a better way to test these workflows.
closes #3212
> Revert "properly escape backticks in envvars"

- contrib/ec2/provision-ec2-cluster.sh
The EC2 provisioning script requires the user to visit the EC2 control panel (or equivalent) and refresh until instances are available. This change makes `provision-ec2-cluster.sh` itself do the waiting, then prints out the instance IPs and the DNS name of the ELB:
```console
$ ./provision-ec2-cluster.sh deis-foo
{
"StackId": "arn:aws:cloudformation:us-west-2:693041077886:stack/deis-foo/16799670-c6a8-11e4-a859-5088487b0895"
}
Waiting for instances to be created...
Waiting for instances to be created...
Waiting for instances to be created...
Waiting for instances to be created...
Waiting for instances to be created...
Waiting for instances to be created...
Waiting for instances to be created...
Waiting for instances to be created...
Waiting for instances to be created...
Waiting for …
```
> feat(contrib/ec2): loop until instances have passed health checks

- tests/mock/mock.go
We've found this image to be more reliable than
paintedfox/test-postgresql.
relies on https://github.com/deis/test-postgresql/pull/1 to be merged first, but initial tests have been showing improved reliability on node2.opdemand.com.
> ref(controller): use postgres:9.3 for functional tests

- builder/image/templates/builder
In newer refactors of the builder, some commands are piped. In bash,
the last command's exit code in the pipe is considered. With
`set -o pipefail`, any command that fails in the pipe means that it's a
non-zero pipe fail, which is what we expect to occur.
closes #2996
closes #3207
> fix(builder): error on pipefail

- deisctl/cmd/cmd.go
For existing clusters, they'll have to run the following to disable
the cache:
$ deisctl stop cache
$ deisctl uninstall cache
$ deisctl restart registry@1
I opted away from removing the LRU cache -> registry links as we will still want those in the future once we figure out the root cause of this issue. This is just a stopgap until the root issue arises.
closes #3269
> fix(registry): remove cache from install/start platform

- builder/image/slugbuilder/builder/install-buildpacks
If we supply a commit, we are expecting the first clone to error, since
shallow clones do not accept commits. If there's a problem, it'll be
captured in the second clone (--quiet only silences stdout, not stderr).
closes #3180
> fix(builder): silence clone on .download_buildpack()

- controller/scheduler/fleet.py
sometimes the unit load state and the fleet api disagree due to some discrepancies between the dbus API and fleet. Re-using the same API call to determine the loadState will help better determine the current state of the job.
> fix(controller): use same API call to determine loadstate

- docs/customizing_deis/registry_settings.rst
- registry/bin/boot
This key was removed in a recent release of the docker registry so it
is no longer in use.
> docs(customizing_deis): remove unused registry secret key

- store/Makefile
From https://ci.deis.io/job/test-vagrant/2410/consoleFull#68219213cb8ad894-464c-4a3e-a6e5-fe9c952136da
```
...
tep 0 : FROM deis/store-base:jenkins-test-vagrant-2410
---> dbff0d3b9df6
Step 1 : ADD build.sh /tmp/build.sh
time="2015-03-11T22:04:59-06:00" level="info" msg="build.sh: no such file or directory" 
Sending build context to Docker daemon 6.656 kB
.....
```
that should throw an error and abort the build but it continues and it fails in the test phase.
> fix(store): abort build in case of any error

- contrib/gce/gce-user-data-template
Undefined behavior occurs if format-ephemeral.service has not finished before var-lib-docker.mount is run.
> fix(docker): wait for drive formatting to complete before mounting

- router/image/templates/nginx.conf
$http_x_forwarded_proto is only set by a load balancer. The rest of us just want to check if `$https = "on"`
closes #3245
> fix(router) enforce HTTPS correctly when not behind an elb

- builder/tests/builder_test.go
- cache/tests/cache_test.go
- controller/tests/controller_test.go
- database/tests/database_test.go
- includes.mk
- logger/tests/logger_test.go
- registry/tests/registry_test.go
- router/tests/router_test.go
- store/Makefile
- store/tests/store_test.go
- tests/bin/route53-wildcard.py
- tests/bin/test-integration-ec2.sh
- tests/bin/test-integration.sh
- tests/bin/test-setup.sh
- tests/mock/mock.go
- tests/ps_test.go
- tests/utils/utils.go
This forks `test-integration.sh` into `test-integration-ec2.sh` so we can target both providers. EC2 testing ~~seems to be more reliable currently than vagrant and~~ will allow us to scale CI more easily. This has run several times as [test-ec2](https://ci.deis.io/job/test-ec2/).
Closes #1680.
> Run integration tests against EC2 clusters

- controller/deis/settings.py
Some of the CORS headers changes since I last looked at the spec so I updated them. This allows external domains, like a deis ui, to be permitted to send and receive these headers.
> fix(controller): Update CORS whitelisted request headers.

- database/build.sh
Builds just began [failing](https://ci.deis.io/job/test-ec2/46/console) with `fatal error: ffi.h: No such file or directory` when building [wal-e](https://github.com/wal-e/wal-e) for deis/database. A python library required by wal-e probably changed its requirements; this fixes it. Also updates wal-e to the [most recent tag](https://github.com/wal-e/wal-e/releases/tag/v0.8c2), which differs from the version Deis was using by [two minor commits](https://github.com/wal-e/wal-e/compare/c16e58a...master).
> fix(database): add requirements for wal-e build

- contrib/coreos/user-data.example
- tests/bin/test-setup.sh
Dumping etcd logs showed "too many open files" errors from etcd, which seems related to #1240 and https://github.com/coreos/coreos-overlay/commit/9d4e63bec512eb9ca97844e47afe93be8b2aea1a. This adapts the Azure user-data change from #3173 for the coreos/user-data file, which overrides the etcd service to increase file handles.
Also includes the commit from #3310 since I need to see etcd logs after this change.
> Use LimitNOFILE for etcd service

- tests/bin/test-setup.sh
Unexplained failures in the test suite seem to point to etcd communication issues currently. This dumps etcd logs from each host into the integration test tarball for forensic analysis.
> chore(tests): add etcd log output to integration tests

- contrib/util/custom-firewall.sh
This allows for more clear error messages. Instead of
coreos-3.example.com [x.x.x.x] 554 (rtsp) : No route to host
it gives
coreos-3.example.com [x.x.x.x] 554 (rtsp) : Connection refused
> ref(security): REJECT target uses port-unreachable

- Vagrantfile
From upstream coreos/coreos-vagrant#211. Allows adding VM guest => host [port forwarding rules](https://github.com/coreos/coreos-vagrant/blob/master/config.rb.sample#L68-L69) in `config.rb`. Credit to @sym3tri.
> feat(Vagrantfile): add forwarded ports configuration

- controller/deis/settings.py
- tests/bin/test-integration-ec2.sh
Multiple simultaneous runs of `make -C controller/ test-unit` have collided on our CI server, so this uses Django's [`TEST_NAME`](https://docs.djangoproject.com/en/1.6/topics/testing/overview/#the-test-database) setting to add a psuedo-random suffix to the PostgreSQL database name. Also changes the ec2 test script to use `openssl rand` instead of `/dev/urandom`, which allows us to `set -eo pipefail` again.
> Random test fixes

- Makefile
This helps when CI test nodes are rebooted in particular--the registry will start again when docker comes up. I've been using this flag locally and on test nodes for months.
> feat(Makefile): always restart dev registry

- contrib/ec2/gen-json.py
- docs/installing_deis/aws.rst
When installing a Deis cluster in an existing VPC, it is currently only
possible to specify one set of (public) subnets in which both the
Deis EC2 instances and the ELB are placed. It is not possible to
enhance security by placing the Deis hosts in a private section of the
VPC, into subnets that have no direct connection to the Internet.
This change adds two new environment variables `VPC_EC2_SUBNETS` and
`VPC_ELB_SUBNETS` to help set up a Deis cluster in such a 'split' VPC
environment.
> feat(contrib/ec2/gen-json.py): split private and public subnets

- controller/web/templates/web/account.html
deis-controller has a (deprecated, not unmaintained) set of web pages; this fixes an error trying to render the `/account/` page.
Closes #3321.
> fix(controller): remove dead web link to logout page

- Makefile
- deisctl/README.md
- deisctl/units/deis-builder.service
- deisctl/units/deis-cache.service
- deisctl/units/deis-controller.service
- deisctl/units/deis-database.service
- deisctl/units/deis-logger.service
- deisctl/units/deis-logspout.service
- deisctl/units/deis-publisher.service
- deisctl/units/deis-registry.service
- deisctl/units/deis-router.service
- docs/managing_deis/platform_monitoring.rst
Currently, whenever we run `docker history` and `docker inspect`
before pulling components for the first time, we emit an
"Image not found" error, which is confusing.
This commit suppresses this output.
> fix(deisctl/units): eat error output for history and inspect

- router/image/templates/nginx.conf
Currently X-Forwarded-Proto does not work correctly behind a load balance with SSL termination. This hopes to fix that and ensures the most common protocol related headers are set.
1.) Ensure X-Forwarded-Proto header is always set for greater application compatibility.
2.) Add X-Forwarded-Protocol and X-Forwarded-Ssl headers for greater application compatibility.
3.) Attempt to detect the proper protocol when running behind load balancers or proxies.
> feat(router): set additional X-Forwarded headers

- contrib/azure/azure-coreos-cluster
- docs/installing_deis/azure.rst
**NOTE**: this replaces #3173 since I was too lazy to do a full rebase
This PR adds two fixes that will make a 5-vm Deis cluster stable on Windows Azure:
1. Support for specifying `affinity-group` as a valid argument to the `azure-coreos-cluster` script.
* Overall platform startup speed reduced by about 15 minutes (ballpark) for a 5-vm cluster on Azure.
* Overall platorm stability and inter-fleet latency reduced to an average of 59ms. [See full cluster stats](https://gist.github.com/gvilarino/aa20c427b5e08b959083)
2. Specific settings for `etcd.service` that will prevent the cluster from dying because of reaching the file-open limit
* Cluster becomes stable and stops throwing "too many open files" error anymore (possibly related to #1240).
* Add setting an `affinity-group` option as a …
> fix(azure): add support for Azure affinity groups

- docs/customizing_deis/router_settings.rst
- router/build.sh
- router/image/templates/nginx.conf
To be enabled with extreme prejudice. Twelve-factor processes should be
stateless and share-nothing. Sticky sessions should not be used to cache
user data in memory. Use a backing store to persist session state.
Valid uses, however, do exist and are widespread: eg. see primus/primus#147
> HTTP implementations are expected to engage in connection management,
> which includes maintaining the state of current connections,
> establishing a new connection or reusing an existing connection,
> processing messages received on a connection, detecting connection
> failures, and closing each connection.
> <cite>[RFC 7230]</cite>
Many real time systems rely on detection of connection failures at the
application level. Without session affinity, detection of connection
failures stops at the load …
> feat(router): add optional query string affinity support

- builder/image/bin/boot
- contrib/azure/azure-user-data-template
- contrib/coreos/user-data.example
- contrib/ec2/gen-json.py
- contrib/gce/gce-user-data-template
This includes the commits from #3316.
We switch from btrfs to ext4 to support overlayfs in Docker. Note that we also format the device with a particular number of inodes. This is what CoreOS does to the root volume to prepare it to run Docker, and since we're running Docker with a separate volume, we must prepare it in the same way. 
Since we're no longer using devmapper in the Docker-in-Docker builder component, this PR also:
closes #3294 
refs #3317
~~TODO: Write wrapper script in builder's /bin/boot to override overlayfs if it's supported.~~
/cc @marineam
> chore(*): replace btrfs with overlayfs

- controller/requirements.txt
- docs/docs_requirements.txt
See https://www.djangoproject.com/weblog/2015/mar/18/security-releases/
It looks unlikely that Deis' controller code was affected by either bug, but we keep up with Django security releases anyway.
> chore(controller): update Django to 1.6.11 security release

- contrib/coreos/user-data.example
replaces #3222 
References:
- https://github.com/coreos/bugs/issues/304
- https://github.com/coreos/coreos-overlay/pull/1145
**This should be temporal until the overlay PR is available in CoreOS stable**
> feat(cloud-init): temporal fix for ntpd error and clock skew

- client/deis.py
- tests/auth_test.go
- tests/utils/itutils.go
this fixes up those random `/dev/ptmx` errors we're finding in ci.deis.io every so often when piping manual I/O to `auth:cancel`.
> feat(client): add flags for automating auth:cancel

- controller/bin/boot
- controller/deis/gconf.py
When a gunicorn worker process inside the controller times out, the only thing that shows up in `deisctl journal controller` is:
```
Mar 20 18:22:07 deis-03 sh[2692]: [2015-03-20 18:22:07 +0000] [254] [CRITICAL] WORKER TIMEOUT (pid:260)
```
This uses gunicorn's [server hooks](http://docs.gunicorn.org/en/latest/settings.html#server-hooks) to add python stack trace output when a worker times out or is killed, for help in debugging:
```
Mar 20 18:22:07 deis-03 sh[2692]: [2015-03-20 18:22:07 +0000] [254] [CRITICAL] WORKER TIMEOUT (pid:260)
Mar 20 18:22:07 deis-03 sh[2692]: [2015-03-20 18:22:07 +0000] [260] [WARNING] worker aborted
Mar 20 18:22:07 deis-03 sh[2692]: File "/usr/local/bin/gunicorn", line 11, in <module>
Mar 20 18:22:07 deis-03 sh[2692]: sys.exit(run())
Mar 20 18:22:07 deis-03 …
```
> feat(controller): print stack trace when worker is killed

- docs/contributing/testing.rst
- tests/fixtures/mock-store/README.md
These test containers change so rarely, it didn't seem worth the machinery necessary to rebuild them. This documents that compromise.
Closes #3151.
> docs(testing): note that some containers don't rebuild automatically

- controller/deis/settings.py
- controller/requirements.txt
- controller/scheduler/fleet.py
- deisctl/units/deis-controller.service
- docs/docs_requirements.txt
The `memory-swap=-1` argument must wait for a future release of Docker: see https://github.com/docker/docker/pull/10633
Reverts deis/deis#3214
> Revert "feat(controller): disable swap usage if there is a memory limit"

- controller/api/models.py
In some odd cases, etcd keys no longer exist from manual intervention.
That should not stop resources from being destroyed, however, as it is
assumed that the etcd key does not exist (which is what was intended,
anyways).
closes #3357
> fix(controller): ignore KeyError on delete

- builder/bin/get-app-config.go
- builder/bin/publish-release-controller.go
- builder/utils.go
- builder/utils_test.go
This change this error message
```
2015/02/23 21:01:47 failed retrieving config from controller: &{%!s(*http.body=&{0xc20800aea0 0xc208058120 0xc208062420 true {0 0} false}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error)=0x49c0b0) %!s(func() error=0x49c040)}
```
with:
```
2015/02/23 22:43:43 failed retrieving config from controller: <h1>Server Error (500)</h1>
```
closes #2883
closes #2984 -- *edited by @bacongobbler*
> fix(builder): return error message as string

- client/deis.py
- docs/using_deis/install-client.rst
Profile names map to deis client configuration file. The profile
name is picked up from the DEIS_PROFILE environment variable if it exists.
The default is 'client' which points to 'client.json'. To run deis
client under a different profile use: DEIS_PROFILE=dev deis
> feat(client): Add multiple profile support to the client

- tests/bin/test-integration-ec2.sh
`test-integration-ec2.sh` generates a subdomain in route53 for testing, but failed to make the root domain configurable.
```console
$ DEIS_TEST_DOMAIN=deis.rocks ./tests/bin/test-integration-ec2.sh
```
> fix(tests): replace hard-coded test domain in ec2 script

- client/deis.py
- tests/config_test.go
This new feature reads from a local .env and pushes the environment variables to Deis.
closes #1532
> feat(client): add deis config:push

- docs/using_deis/using-buildpacks.rst
It was suggested that the "Optional: Add SSH key to use private repositories" section detours too much from the basic workflow in the "Using Buildpacks" doc, and that it would fit better after "Custom Buildpacks." This does that as well as shortens some language and adds a basic usage example. ping @gabrtv.
Refs #3305.
> ref(docs): move "private repos" section after "custom buildpacks"

- controller/scheduler/fleet.py
Controller code was checking the SSH channel's exit status *before* reading data from it, which surprisingly worked--up to a certain size in the neighborhood of [2182300 bytes](https://github.com/deis/deis/issues/3035#issuecomment-73433740). The similar issue paramiko/paramiko#448 suggested calling `recv_exit_status()` first was the problem, and changing the call order does fix large file output from `deis run` for the largest test files I've used, which previously failed.
```console
$ deis run -- "cat pg3008.txt | wc -c"
Running `cat pg3008.txt | wc -c`...
2474769
$ deis run -- "cat pg3008.txt"
Running `cat pg3008.txt`...
...
15331. jarg422h.htm#The%20Cuckoo's%20Egg
15332. jarg422h.htm#wizard
15333. jarg422h.htm#wannabee
End of The Project Gutenberg Etext of The New Hacker's Dictionary …
```
> fix(controller): read from SSH channel before checking exit status

- database/bin/boot
deis-database startup logs a couple of `ERROR exit status 127` messages. Adding `-debug=true -verbose=true` and removing `--quiet` from `confd` flags showed that we had a chicken-and-egg situation where our check_cmd `/usr/local/bin/reload` script was called before it existed, since it is also templated by `confd`.
This PR installs a no-op shell script to `/usr/local/bin/reload` to make `confd` quieter during initial startup.
```console
--- Run deisci/database:git-5246753 at 192.168.59.103:58203
Error response from daemon: No such container: deis-database-git-5246753
2015-04-01T19:52:55Z c5022545f3b2 confd[49]: WARNING Skipping confd config file.
database: no existing database found.
database: no backups found. Initializing a new database...
2015-04-01T19:52:55Z c5022545f3b2 confd[82]: …
```
> fix(database): stub out reload script before starting confd

- docs/installing_deis/install-platform.rst
IRC user [bkleef](https://botbot.me/freenode/deis/2015-03-31/?msg=35482821&page=2) pointed out this shell bracketing typo in [Installing Deis](http://docs.deis.io/en/latest/installing_deis/install-platform/).
```console
$ deisctl config platform set sshPrivateKey=$(HOME)/.vagrant.d/insecure_private_key
-bash: HOME: command not found
$ deisctl config platform set sshPrivateKey=${HOME}/.vagrant.d/insecure_private_key
```
> fix(docs): bracket $HOME properly in "deisctl config" example

- builder/image/templates/builder
/bin/release was unofficially deprecated for declaring default process
types a while back, which is why some buildpacks don't supply any
default process types in /bin/release. Instead, the buildpack will
generate a Procfile if none is supplied.
Before: https://gist.github.com/bacongobbler/0a530ebaf08685b20d09
After: https://gist.github.com/bacongobbler/6ae9fc07f2fd7b248953
closes #3404
> fix(builder): retrieve process types from slugbuilder's Procfile

- builder/image/templates/check-repos
deis-builder startup logs an `ERROR exit status 123` message. This is due to the `docker rmi` command being run through `xargs` with no arguments. The [`-r` or `-no-run-if-empty` flag](https://www.gnu.org/software/findutils/manual/html_node/find_html/xargs-options.html) ensures that GNU `xargs` doesn't run its target command if no args were provided.
```console
--- Run deisci/builder:git-e9f7093 at 192.168.59.103:61203
Error response from daemon: No such container: deis-builder-git-e9f7093
2015-04-01T21:02:53Z b013f1daa439 confd[71]: WARNING Skipping confd config file.
2015-04-01T21:02:53Z b013f1daa439 confd[114]: WARNING Skipping confd config file.
time="2015-04-01T21:02:53Z" level="info" msg="+job serveapi(unix:///var/run/docker.sock)" 
time="2015-04-01T21:02:53Z" level="info" msg="+job …
```
> fix(builder): skip `docker rmi` if there are no images to remove

- client/deis.py
- docs/customizing_deis/cli-plugins.rst
- docs/customizing_deis/index.rst
I've talked about this before and I think this would be really beneficial for commands like `deis config:push` etc. as discussed in #1532.
This article describes the changes involved in the client in order to manage client plugins. It essentially behaves the same as `heroku plugins`, following the theme of winning big with the Heroku -> Deis migration path. I didn't feel like it fit in any of the other document paths, and it follows the same URL path as [heroku's articles](https://devcenter.heroku.com/articles). Docker does the same thing as well: http://docs.docker.com/articles/
If this is approved, I'll get to work on implementing a PoC plugin called `deis-accounts`, similar to https://github.com/ddollar/heroku-accounts.
> Proposal: deis client plugins

- deisctl/cmd/cmd.go
`deisctl start platform` omits deis-cache as of #3273, but `deisctl stop platform` and `deisctl uninstall platform` weren't updated:
```console
$ deisctl stop platform
● ▴ ■
■ ● ▴ Stopping Deis...
▴ ■ ●
Routing mesh...
deis-router@1.service: inactive/dead                                 
deis-router@2.service: inactive/dead                                 
deis-router@3.service: inactive/dead                                 
Data plane...
deis-publisher.service: inactive/dead                                 
Control plane...
deis-builder.service: inactive/dead                                 
deis-controller.service: inactive/dead                                 
deis-database.service: inactive/dead                                 
deis-registry@1.service: inactive/dead …
```
> fix(deisctl): omit cache from `deisctl stop platform"

- deisctl/units/deis-registry.service
Otherwise registry will loop forever waiting for the `/deis/cache` dir to exist, nice find @smothiki.
> fix(registry): create /deis/cache etcdctl dir

- docs/customizing_deis/logger_settings.rst
Change an incorrect reference to the database component in the documentation for customizing the logger component.
> docs(logger): change incorrect ref to db component

- contrib/coreos/user-data.example
This commit introduces a systemd unit to upgrade fleet to 0.9.2
before the daemon is started. This is intended to address
https://github.com/coreos/fleet/issues/1158 which was a regression
from fixes introduced in fleet 0.9.1, which is included for the first
time in CoreOS 607.0.0.
> chore(contrib/coreos): upgrade fleet to 0.9.2

- docs/reference/index.rst
- docs/reference/self-signed-certs.rst
- docs/using_deis/app-ssl.rst
- docs/using_deis/index.rst
"Using App SSL" belongs in "Using Deis". I've also cleaned up some of
the more confusing terms like "domain ssl" in favour of "app ssl".
> ref(docs): clean up app ssl documentation

- database/templates/create_bucket
- registry/templates/create_bucket
The previous test was always returning `False` since it compared a string to a `boto.s3.bucket.Bucket` instance. So before this change we always tried to create the bucket and presumably hit errors if it already existed. 
I tested this change interactively in `ipython` and it fixes the comparison. I also ran `flake8` on the template scripts and cleaned them up. Thanks to @Blystad for catching this bug!
Closes #3430.
> fix(database+registry): check for S3 bucket name before creating it

- contrib/azure/azure-coreos-cluster
Currently this error spews for any little reason. It helps if we catch and explain some quick things to look for
> fix('contrib/azure/azure-coreos-cluster'): make this not found error more user friendly

- logspout/image/Dockerfile
flynn/logspout has not been modified in 15 months, whereas busybox is
an officially supported image by docker.
> chore(logspout): switch to busybox

- router/image/templates/nginx.conf
This broke in #3266 when removing taxing regex rewrites from nginx. See http://wiki.nginx.org/HttpCoreModule#.24host
TESTING: on a cluster with this router patch applied, do `deisctl config router set enforceHTTPS=true`, then use `wget` to query an HTTP endpoint on the server. You should see a proper HTTPS redirect to the same URL, rather than the bogus one created previously.
Closes #3438, #3437.
> fix(router): use nginx $host in HTTPS redirects

- client/Makefile
- client/setup.py
- controller/dev_requirements.txt
- docs/docs_requirements.txt
Includes an update to [zoneinfo](http://en.wikipedia.org/wiki/Tz_database) and bug fixes, see https://github.com/dateutil/dateutil/releases/tag/2.4.2
> chore(client): update python-dateutil to 2.4.2

- builder/image/templates/gitreceive
The `exit $?` was capturing the call to `rm -rf`, which will almost always exit 0. As a fix, whenever gitreceive captures a failed build, it will exit with exit code 1 so that the commit will get rejected.
closes #3342
closes #3427
> fix(builder): exit 1 when gitreceive captures a build

- controller/build.sh
- database/build.sh
- registry/build.sh
- tests/bin/setup-node.sh
- tests/fixtures/mock-store/build.sh
I got tired of seeing these warnings:
```console
venv/bin/pip install -q -r requirements.txt -r dev_requirements.txt
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
> chore(*): update pip installer tool to 6.1.1

- controller/requirements.txt
- docs/docs_requirements.txt
See https://github.com/docker/docker-py/compare/0.7.2-release...1.1.0-release
Deis still uses only the (unchanged) [`utils.parse_repository_tag`](https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L183) function, so this is purely housekeeping for now, although #3134 may want this.
> chore(controller): update docker-py to 1.1.0

- controller/api/tests/test_domain.py
.get_object() returns all domains instead of the requested domain, which
causes an issue when attempting to delete or modify a specific domain.
Left this unit test open in case someone wants to work on this until I get time to fix 'er up for v1.6
Refs #3475.
> test(controller): add unit test for deleting domains

- controller/Makefile
Deis used to summarize test code coverage for the controller, but this was lost in a project shuffle. This restores the summary table to `make -C controller/ test-unit`.
```
$ venv/bin/coverage report -m
Name                 Stmts   Miss  Cover   Missing
--------------------------------------------------
api/admin               47      0   100%   
api/authentication       5      0   100%   
api/fields              29      4    86%   29, 39, 43-47
api/middleware          17      0   100%   
api/models             662     90    86%   104-105, 111-112, 118-119, 196-197, 461-464, 478-484, 491-494, 499, 544, 632-633, 636-637, 706-719, 732, 754-756, 788, 817, 821, 856-857, 933-934, 939-944, 948-954, 958-960, 964-968, 972-975, 979-984, 988-990, 994-999, 1027-1035
api/permissions         43 …
```
> feat(controller): restore coverage.py report for unit tests

- controller/api/tests/test_limits.py
When merging #3484 I missed that the regular expression to be tested was duplicated.
> ref(controller/tests): import regex to be tested, don't copy it

- router/image/templates/generate-certs
closes #3483 
closes #3507
What's happening is that we are iterating through each cert twice. This is necessary to work around some boot issues with confd. However with the current logic, we're writing the last cert in each iteration to every file. By checking the domain with the etcd key, only the correct one will be written to the cert/key path.
> fix(router): write out only if cert matches the path

- Vagrantfile
- contrib/azure/azure-coreos-cluster
- contrib/ec2/deis.template.json
- contrib/rackspace/provision-rackspace-cluster.sh
- docs/installing_deis/baremetal.rst
- docs/installing_deis/gce.rst
https://coreos.com/releases/#633.1.0
Note that we really want ~~CoreOS >= 640.0.0 for Linux 3.19 for Ceph
and~~ fleet 0.9.2, but since at least Digital Ocean gets the latest
stable, we should do our best to bump to the latest stable
whenever possible.
replaces #3490
> chore(*): bump CoreOS to 633.1.0

- contrib/ec2/provision-ec2-cluster.sh
output remaining time for provisioning/waiting for health checks, and
explicitly declare giving up and why.
additionally, tear down the stack if it's failed.
> fix(contrib/ec2): improve timeout handling

- controller/api/tests/test_domain.py
- controller/api/views.py
The Django view helper method `get_object` was returning a queryset rather than the `Domain` model instance.
Thanks to @bacongobbler for starting this with a unit test. :green_heart: 
Closes #3475, refs #3499.
> fix(controller): return the correct domain from get_object()

- controller/api/models.py
- controller/api/serializers.py
- controller/api/south_migrations/0022_auto__add_field_key_fingerprint.py
- controller/api/south_migrations/0023_key_fingerprints.py
- controller/api/south_migrations/0024_auto__chg_field_key_fingerprint__del_unique_key_owner_id__add_unique_k.py
- controller/api/tests/test_key.py
Deis was using the `id` supplied by the `deis` CLI to determine if a key is unique. But that `id` usually contains the trailing email or comment, which may be common to several unique keys. The [key fingerprint should be used](https://github.com/deis/deis/issues/3444#issuecomment-91313029) instead to determine uniqueness.
These 3 [migration scripts](http://south.readthedocs.org/en/latest/tutorial/part3.html#data-migrations), in order:
- create a (nullable) fingerprint column
- populate the fingerprint from the public key material
- drop the old (owner, id) index and create a new (owner, fingerprint) one, making the fingerprint column unique
Closes #3444, closes #3285.
> fix(controller): use key fingerprint instead of id for uniqueness

- controller/api/tests/test_certificate.py
- controller/api/urls.py
One of the regular expressions for `Certificate` endpoints wasn't allowing `*` through, so wildcard certs could be created but not deleted. This relaxes the regex to allow such certs to be deleted. Thanks to @bacongobbler for the test! :green_heart: 
Note that wildcard certificates aren't fully supported yet, but users should still be able to delete them.
Closes #3533.
> fix(controller): allow "*" wildcard in cert REST URLs

- contrib/util/generate-changelog.sh
Instead of using individual commits to generate the changelog, we can use the merged PRs which better reflects the changes in a release. 
*Edit* by @mboersma:
Closes #1416.
refs #3509 
For example, the new output:
```
><> ./contrib/util/generate-changelog.sh v1.5.0
- [`fd3fc8e`](https://github.com/deis/deis/commit/fd3fc8e392e0abc361b77c51d1c5c23ebe4f0f3a) controller: add users:list endpoint
- [`4070755`](https://github.com/deis/deis/commit/4070755d502729e3a247c80176cb2d6e15908f65) contrib/azure/azure-coreos-cluster: add an https enddpoint on c… …reation
- [`ef3b89c`](https://github.com/deis/deis/commit/ef3b89c97e7be8fbb6c41f4f2bb4607b9ea3c2de) client: check controller before attempting to register. Fixes #3224
- [`8e960ca`](https://github.com/deis/deis/commit/8e960ca203bd5d8c48e129c4172dd2 …
```
> ref(contrib): use merges for changelog summmaries

- client/deis.py
- controller/api/authentication.py
- controller/api/permissions.py
- controller/api/tests/test_auth.py
- controller/api/views.py
- controller/bin/boot
- controller/migrations/data/0002.sh
- controller/templates/confd_settings.py
- docs/customizing_deis/controller_settings.rst
Use etcd key `/deis/controller/registrationMode` to manage registration mode, which can now be "enabled", "disabled", or "adminOnly".
If a user is logged into the deis client and tries to register, the token is now sent to the controller so that the controller can check if the current user is a admin and allow them to register if the registration mode is "adminOnly".
I also created a migration from `/deis/controller/registrationEnabled` to `/deis/controller/registrationMode`.
Fixes #3343
> feat(controller): Allow adminOnly registration

- client/deis.py
Implement #3423 allowing users to optionally specify a path to an environment file for config:push.
*edit carmstrong*
closes #3423
> feat(client): add optional path to config:push

- client/deis.py
- controller/api/models.py
- controller/api/tests/test_app.py
- controller/api/views.py
- docs/reference/api-v1.3.rst
- tests/apps_test.go
Usage: `deis apps:logs -n <number>`
I used a URL query parameter instead of a JSON body because that is generally considered better practice in a GET request. If you would like me to change to using a JSON body I can.
Do you want a API bump for this, or since 1.3 hasn't been released yet, add to that?
Closes #1264
> feat(controller): add a option to limit the number of log lines

- contrib/coreos/user-data.example
This was merged upstream, and is available as of
CoreOS 612.1.0: https://coreos.com/releases/#612.1.0
Edit by mboersma: refs #3311.
> chore(contrib/coreos): remove etcd LimitNOFILE

- router/image/Dockerfile
- router/image/templates/nginx.conf
The idea behind not including deis.conf was so that custom domains which
are different from the platform domain would not attach the platform SSL
certificate when it was enabled. However, this has the side effect of
not attaching domains which are subdomains of the platform domain, which
is intentional.
A better fix would be to check if the domain is a subdomain of the platform domain but text/template or confd doesn't have `strings.Contains` included as a function.
closes #3470
> fix(router): include deis.conf if no match with an SSL cert

- docs/customizing_deis/router_settings.rst
- router/image/templates/nginx.conf
The router was having different timeout values for keepalive_timeout
and for proxy timeouts.
This can cause issues with front facing load balancers in front of
deis-router (like Amazon ELB), and could be the cause of issue #3448
Timeout values should be greater than the timeout value of the front facing
load balancer. 
**Ref:**
> The keepalive timeout value on your backend server must be higher than that
> of your ELB connection timeout. If it is lower, the ELB will re-use the idle
> connection when your server has already dropped the connection, resulting in
> the client being served up a blank response.
http://engineering.chartbeat.com/2014/02/12/part-2-lessons-learned-tuning-tcp-and-nginx-in-ec2/
> The ELB timeout should be set to less then the backend server idle timeout. …
> fix(router): Unify timeout values

- client/Makefile
- client/deis.py
- client/deis.spec
- client/requirements.txt
- client/setup.py
- controller/dev_requirements.txt
- docs/docs_requirements.txt
- tests/bin/build-deis-cli.sh
Recently urllib3 began [emitting these warnings](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning) pointing to limitations in python's `ssl` that could create vulnerabilities. It's not easy to require Python 2.7.9 for all dev users and our build environment, so [using `pyOpenSSL`](https://urllib3.readthedocs.org/en/latest/security.html#pyopenssl) is the other recommended fix, which is what this PR does. 
This also moves `deis` CLI libraries to `client/requirements.txt` and cleans up a dead Makefile target and test script.
Closes #3253, refs #3512.
> fix(client): use pyOpenSSL for improved security features

- logger/README.md
- logger/image/Dockerfile
- logger/main.go
- logger/syslogd/syslogd.go
- logger/tests/logger_test.go
So I was trying to look around for a syslog server to store logs on some of my remote machines so I can test the Docker 1.6 changes and I thought to myself... "Hey, deis built one of those!" So this PR is a general enhancement to the logger itself. These enhancements are a no-op to the existing logger, but exposes flags to the end-user such that it's possible to extend the logger to the user's content.
Along with exposing common configuration as feature flags, this PR includes a feature flag for enabling/disabling publishing to service discovery (etcd). In some cases where you are running the logger in a local environment, you don't require the need to publish the logger to etcd. By default this is set to false, but I've enabled it in the Dockerfile so it's a no-op for Deis.
This doesn't …
> feat(logger): expose config as flags

- docs/using_deis/process-types.rst
Also states that Deis does not automatically migrate from web to
cmd process types when switching contexts.
closes #2861
> docs(using_deis): explain difference between web and cmd

- client/deis.py
- controller/api/serializers.py
- controller/api/tests/test_certificate.py
- docs/reference/api-v1.3.rst
This feature allows a user to specify a list of SubjectAltNames (SANs)
for a specified certificate. This has the effect of creating multiple
certificate entries in the database (one for each SAN), but it gives the
user the benefit to revoke the certficate for each custom domain.
By default, SANs are **not** added as new entries with `certs:add`. The
user will need to explicitly give each subject alt name they wish to add
as a certificate.
Usage:
```
$ deis certs:add ~/.openssl/star.fishworks.io.cert ~/.openssl/private.key.nopass --subject-alt-name foo.fishworks.io --subject-alt-name bar.fishworks.io
Adding SSL endpoint... done
*.fishworks.io
Adding SSL endpoint foo.fishworks.io...done
Adding SSL endpoint bar.fishworks.io...done
$ deis certs
Common Name       Expires
---------------- …
```
> feat(controller): support SAN certificates

- docs/customizing_deis/router_settings.rst
- router/image/templates/nginx.conf
Add method to customize the nginx error_log level via etcd. This helps when
debugging issues in deis-router.
Fixes #3560
Pretty easy to test:
```
deisctl config router set errorLogLevel=debug
deisctl config router set errorLogLevel=error
```
And check the log.
> feat(router): customize error_log level via etcd

- client/deis.py
Localized dates are 28 characters, pretty dates should be padded correctly to account for this.
Fixes #1507
> fix(client): Fix spacing of releases list

- store/base/build.sh
Install missing `lsb-package` to remote error in `deis-store-daemon`
```
Apr 25 20:07:14 nodo-2 sh[16765]: store-daemon: starting daemon on nodo-2...
Apr 25 20:07:14 nodo-2 sh[16765]: 2015-04-25 20:07:14.488531 7f152a06e900  0 ceph version 0.94.1 (e4bfad3a3c51054df7e537a724c8d0bf9be972ff), process ceph-osd, pid 1
Apr 25 20:07:14 nodo-2 sh[16765]: starting osd.2 at :/0 osd_data /var/lib/ceph/osd/ceph-2 /var/lib/ceph/osd/ceph-2/journal
Apr 25 20:07:14 nodo-2 sh[16765]: 2015-04-25 20:07:14.502673 7f152a06e900  0 filestore(/var/lib/ceph/osd/ceph-2) backend btrfs (magic 0x9123683e)
Apr 25 20:07:14 nodo-2 sh[16765]: 2015-04-25 20:07:14.508672 7f152a06e900  0 genericfilestorebackend(/var/lib/ceph/osd/ceph-2) detect_features: FIEMAP ioctl is supported and appears to work
Apr 25 20:07:14 nodo-2 …
```
> fix(store): install lsb-release package

- store/base/templates/ceph.conf
The current template generates `mon addr = :6789` instead of a list of ip:port of each ceph node.
> fix(store): change template to return ip address instead of :6789

- contrib/rackspace/provision-rackspace-cluster.sh
Manually verified:
```console
core@deis-1 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=633.1.0
VERSION_ID=633.1.0
BUILD_ID=
PRETTY_NAME="CoreOS 633.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
> chore(contrib/rackspace): bump CoreOS to 633.1.0

- controller/conf.d/gconf.toml
- controller/deis/gconf.py
- controller/templates/gconf.py
- docs/customizing_deis/controller_settings.rst
The hard-coded default of 8 python worker processes was a stab in the dark, and may use more resources than required in general. This change uses gunicorn's recommended default of (CPUs * 2 + 1), and allows a user to override that with `deisctl config controller set workers=N`.
> feat(controller): allow user to scale gunicorn worker processes

- database/build.sh
Updates the version of [wal-e](https://github.com/wal-e/wal-e) used by deis-database to v0.8.0, plus a commit by @aledbf that improves compatibility with alpine/busybox.
See https://github.com/wal-e/wal-e/compare/v0.8c2...c6dd4b1
> chore(database): update wal-e to v0.8.0 + busybox fix

- contrib/ec2/deis.template.json
- contrib/ec2/provision-ec2-cluster.sh
- docs/customizing_deis/router_settings.rst
- docs/installing_deis/aws.rst
- router/image/templates/deis.conf
- router/image/templates/nginx.conf
This PR is a proof-of-concept providing websocket support for deis on ec2 without further configuration.
To enable websockets and remote IPs, I used the proxy protocol as already proposed by @Blystad. The major difference is, that I forward 80 and 443 directly via TCP and do not terminate SSL at the ELB. SSL termination can now done by deis itself at the router (like on GCE or DO).
This approach has multiple advantages:
* apps still know the forward protocol
* spdy support for EC2
* paves the way for multi TLD SSL on EC2
* Simplifies deis as EC2 routing now works more like on GCE or DO
Alternative for https://github.com/deis/deis/pull/3095 #2717
When this concept is accepted, I'll merge the work from @Blystad into this PR and ensure that every commit is attributed correctly.
I tested this …
> WebSockets on EC2

- contrib/coreos/user-data.example
This workaround should be removed when a [newer CoreOS](https://coreos.com/releases/#647.0.0) makes it into the stable channel, but for now putting the `fleetd-0.9.2` binary and conf file under /opt ensures they will survive a reboot.
Tested with `make discovery-url && vagrant up`, then `vagrant reload deis-01 && vagrant ssh deis-01 -c 'ps faux | grep fleetd'`, which fails on Deis master but succeeds when provisioned from this PR. Also checked by hand that the `fleetd` binary disappeared before, but remains now after reboot.
Closes #3547.
> fix(user-data): update fleetd 0.92 to /opt so it survives reboots

- builder/image/bin/boot
- cache/README.md
- controller/bin/boot
- database/bin/boot
- registry/bin/boot
- store/gateway/bin/boot
- tests/fixtures/mock-store/bin/boot
The registry and gateway's boot relies on etcdctl for determining who has the master lock. Bumping to 20 seconds should prevent users from having their TTLs expire from latency issues.
closes #3563
> fix(registry): bump etcd ttl to 20 seconds

- controller/Makefile
`make -C controller postgres` will start up a PostgreSQL container you can use to run unit tests. Useful for people without PostgreSQL installed or who don't want to mess with their local database. Exporting the variables printed by the command will allow the controller to connect to the specified database.
> feat(Makefile): Add a command to start a local postgresql container for running unit tests

- controller/api/models.py
This change makes some scheduler-related code shorter and easier to read. Certain parts are also marginally more efficient since Python's [`any()`](https://docs.python.org/2/library/functions.html#any) will return on the first match, whereas the `set() != set()` comparisons iterated through all elements.
> ref(controller): simplify thread and set comparison code

- contrib/digitalocean/provision-do-cluster.sh
ams2 and sfo1 now do have metadata and private-networking support.
Replaces #3603.
> feat(contrib/digitalocean): enable ams2 and sfo1 datacenters

- builder/Makefile
- builder/image/Dockerfile
- builder/image/bin/boot
- builder/image/slugbuilder/Dockerfile
- builder/image/slugbuilder/README.md
- builder/image/slugrunner/Dockerfile
- builder/image/slugrunner/README.md
Heroku now officially maintains a Docker image for their cedar stack.
The maintainer of cedarish is deprecating it in favour of this image,
so we should migrate over such that we emulate their environment
perfectly.
Since we no longer build a root filesystem and package it into a tarball,
this speeds up development time when compiling builder dramatically
with the tradeoff of having to fetch heroku/cedar:14 on boot, which is
slightly slower than a `docker import`. However, the difference
between relying on your local connection to pull cedarish from S3
vs. relying on a cloud provider's bandwidth to pull the image on boot
is quite significant, so really it's a question of tomato vs. tomatoe.
> chore(builder): migrate to heroku's cedar stack

- contrib/README.md
Docker S3 cleaner removes orphaned image layers from S3 backed private docker registries. Packaged with Deis-specific unit file in [contrib/deis](https://github.com/myriadmobile/docker-s3-cleaner/tree/master/contrib/deis).
> docs(contrib): add link to Docker S3 Cleaner

- controller/bin/boot
- deisctl/units/deis-controller.service
This is a mini optimization. We have a function and a place which we
set up directories which components rely upon. Since the controller now
relies on /deis/scheduler, this moves it over there.
I found this because I wasn't following the upgrade docs to a tee, but it made more sense to put it where all the rest are initialized anyways :)
> ref(controller): move mkdir to bin/boot

- contrib/ec2/provision-ec2-cluster.sh
This envvar does not persist after the script is executed unless you
`source` it.
closes #3628
> fix(contrib): remove message to exporting DEISCTL_TUNNEL

- deisctl/units/deis-builder.service
Starting deis-builder shows lots of these warnings in the log:
```
/bin/sh: line 0: echo: write error: Broken pipe
```
Reworking the `ExecStartPost` line not to use a piped command silences this. Lots of users stare at the builder log, so it's worth cleaning it up.
> fix(builder): silence pipefail errors on boot

- logger/image/Dockerfile
- publisher/image/Dockerfile
Deis already uses the official Docker `busybox` image for logspout and swarm. This moves logger and publisher over to `busybox` from `ubuntu-debootstrap:14.04` as well, which may reduce `docker pull` times a bit:
```console
$ docker images
REPOSITORY            TAG          IMAGE ID            CREATED              VIRTUAL SIZE
deis/publisher        busybox      a25fcb101021        38 seconds ago       7.456 MB
deis/publisher        ubuntu       5c2426283d34        2 hours ago          92.06 MB
deis/logger           busybox      2dc3bd7e2d5e        About a minute ago   7.288 MB
deis/logger           ubuntu       2308c400b8c9        2 hours ago          91.9 MB
```
(It should be a trivial change from `busybox` to `alpine:3.1` if and when we get there.)
> ref(logger+publisher): use busybox as Docker base image

- contrib/azure/azure-coreos-cluster
Azure's load balancer has a default timeout of 4 minutes if there is
no activity on the connection. The deis builder sometimes can hold
a connection longer for 4 minutes without any getting any tcp packets
from the client causing a timeout. This extends the timeout to azure's
maximum of 30 minutes suitable for most application deployments.
> fix(contrib/azure/azure-coreos-cluster): extend load balancer timeout

- docs/_includes/_get-the-source.rst
- docs/contributing/releases.rst
This would have saved me a bit of heartache; the issue was finally identified by @bacongobbler .
As it stands, this tag name will very soon be out of date, leaving people blithely copy/pasting (I would *never* do that, right?) running an old version of Deis.  But I don't see an easy fix for that..
It looks like `|release|` is always the release from which the docs are built, which will not correspond to the most recently released tag.  I don't know if there's any other automated way to generate the correct tag name.
> Suggest checking out a tag when getting the source

- deisctl/backend/fleet/utils.go
- deisctl/backend/fleet/utils_test.go
Commands such as `deisctl stop platform` were doing wildcard searches for the short names of units, effectively telling fleet to find all `*registry*` units, for example. This changes that wildcard to `*deis-registry*` and adds a test to ensure `deisctl` won't find a random app unit with "registry" in its name in that case.
Closes #3497.
> fix(deisctl): prefix unit name with "deis-" before expanding

- docs/customizing_deis/controller_settings.rst
`/deis/controller/webEnabled` uses Python's `bool` to parse this
configuration value; `0` and `1` are handled correctly, but `false` and
`true` lead to NameError.
> fix(nonstring-default) numeric default for webEnabled

- contrib/ec2/deis.template.json
- contrib/ec2/gen-json.py
The ephemeral volume doesn't persist through host stop/start cycles.
/cc @jwaldrip
closes #3618
> fix(contrib/ec2): use EBS volume for etcd data

- controller/scheduler/fleet.py
- docs/using_deis/using-docker-images.rst
- docs/using_deis/using-dockerfiles.rst
- publisher/server/publisher.go
For buildpack apps, [$PORT is exposed][1] as part of slugrunner's job. For Dockerfile/Docker images, the internal port numbers are already known to the developer, so if they want to follow 12-factor best practices then they will have set up $PORT in their own image. I tried seeing if there was a way to work around the docker API's limitations but didn't find one, and then it dawned on me that this is only relevant for users which *do not have control over the exposed ports*. For Dockerfiles/Docker images, this is managed by them so this logic was over-engineered.
deis/publisher exposes the port with the lowest numerical value to the router (docker sorts the internal ports before exposing them in the API), which is why the documentation is reflected to show this.
[1]: …
> chore(controller): remove $PORT logic from fleet

- client/MANIFEST.in
Tested locally with `python setup.py sdist && pip install dist/deis-1.7.0-dev.zip`: broken before, works now.
Closes #3668.
> fix(client): add requirements.txt to pypi distribution

- contrib/coreos/user-data.example
This actually causes issues, as calling /usr/bin/timedatectl set-ntp true
actually starts systemd-timesyncd.service which stops ntpd.
We also suspect this logic is no longer necessary as
coreos/coreos-overlay#1142 has made its way to the stable channel.
fixes #3634
fixes #3386
closes #2900
replaces #3670
reverts #3300
reverts #2596
> fix(contrib/coreos): remove custom clock sync logic

- router/image/templates/generate-certs
Debugging an error I found this output from the router:
```
/bin/generate-certs: line 21: syntax error near unexpected token `done'
/bin/generate-certs: line 21: `done < /etc/ssl/deis_certs'
```
> fix(router): check if there is certificates to generate

- builder/image/bin/auplink
- builder/image/bin/boot
alpine do not provides support for aufs tools.
This is the removed warning:
```
Step 1 : RUN mkdir /app
time="2015-05-11T11:47:40Z" level="error" msg="[warning]: couldn't run auplink before unmount: exec: \"auplink\": executable file not found in $PATH" 
time="2015-05-11T11:47:40Z" level="error" msg="[warning]: couldn't run auplink before unmount: exec: \"auplink\": executable file not found in $PATH" 
```
> fix(builder): remove warning when docker uses the aufs driver

- database/build.sh
- database/templates/postgresql.conf
This is the error in jenkins:
```
...
database: expecting initialization id: none
database: no existing database found or it is outdated.
database: no backups found. Initializing a new database...
postgres: could not write external PID file "/var/run/postgresql/daemon.pid": Permission denied
2015-05-11 11:51:14 UTC LOG:  could not open usermap file "/etc/postgresql/main/pg_ident.conf": No such file or directory
2015-05-11 11:51:14 UTC LOG:  database system was shut down at 2015-05-11 11:51:13 UTC
...
```
> fix(database): remove postgres pid error from log

- store/monitor/bin/boot
In store-monitor's bin/boot script, we set default etcd keys that
are used to template ceph.conf for all store components. Previously,
this logic was inside the monitor setup lock logic, meaning it's only
executed once for the lifetime of a cluster. This breaks when adding new
keys to ceph.conf and this logic, since upgraded clusters will not
execute this logic a second time, thus skipping the creation of new
(and necessary) keys. The cluster will not come up on an upgrade
because confd cannot template ceph.conf in the store components.
Because *all* store monitors now set these defaults before checking
if they're the master, we have to ensure that all monitors are setting
the same default values and not writing over a different default set
by a competing monitor. We do this by removing …
> fix(store): fix shared etcd key defaults

- client/requirements.txt
- docs/docs_requirements.txt
pyOpenSSL only specifies `cryptography>=0.7`, but last night's release of cryptography 0.9 with [osrandom.h refactoring](https://github.com/pyca/cryptography/pull/1774) breaks our PyInstaller packaging for the `deis` CLI:
```
File "/var/lib/jenkins/jobs/test-ec2/workspace@2/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/cryptography.hazmat.bindings.openssl.osrandom_engine", line 10, in <module>
IOError: [Errno 2] No such file or directory: '/tmp/_MEIfxEnRz/cryptography/hazmat/bindings/openssl/src/osrandom_engine.h'
error at command wait
--- FAIL: TestGlobal (1.02s)
```
Note that this error shows up when running the packaged/compiled `deis` CLI, not during its build. All CI builds have been broken since cryptography made their 0.9 release.
Pinning the sub-requirement to the last …
> fix(client): pin cryptography library at 0.8.2

- publisher/image/Dockerfile
- publisher/main.go
This enables the golang [pprof](https://golang.org/pkg/net/http/pprof/) tool to get runtime profiling from the go publisher application
```
core@nodo-1 ~ $ docker exec -it deis-publisher /bin/sh
/ # curl http://localhost:6060/debug/pprof/goroutine?debug=2
goroutine 186 [running]:
runtime/pprof.writeGoroutineStacks(0x7f3c9ab15c40, 0xc208060000, 0x0, 0x0)
/usr/local/go/src/runtime/pprof/pprof.go:511 +0x8d
runtime/pprof.writeGoroutine(0x7f3c9ab15c40, 0xc208060000, 0x2, 0x0, 0x0)
/usr/local/go/src/runtime/pprof/pprof.go:500 +0x4f
runtime/pprof.(*Profile).WriteTo(0x9b6b20, 0x7f3c9ab15c40, 0xc208060000, 0x2, 0x0, 0x0)
/usr/local/go/src/runtime/pprof/pprof.go:229 +0xd5
net/http/pprof.handler.ServeHTTP(0xc2080cc071, 0x9, 0x7f3c9ab15b90, 0xc208060000, 0xc20803c1a0) …
```
> feat(publisher): add pprof to enable profiling

- controller/api/urls.py
`pylint` pointed out this module lacked a docstring, and that a certs URL was ignoring a format arg. Also switched single- to double-quotes for format strings to follow an unenforced convention in the codebase.
> ref(controller): add urls.py docstring and remove unused arg

- database/bin/backup
- database/bin/boot
- database/tests/recovery_test.go
Instead of running the backup in the publish loop, we can schedule the
backups on a timed interval. I tried to do this with cron, but I was
having trouble sending the output of the forked processes to
/dev/stdout, so instead I just forked a for loop in the background.
We can easily change this to remove the `for` loop and point cron at
/app/bin/backup if someone can figure that out :)
closes #2741
closes #3643
> fix(database): run backups in the background

- docs/using_deis/config-application.rst
The docs already give the `deis help config` usage string, which has a tidy summary of available options, so this is just a usage example rather than a complete reference.
Closes #3697.
> docs(config-application): add a config:push / pull example

- client/deis.py
This fix lets the `requests` library read configuration from environment
variables.
This is intended to fix a problem I had with being unable to
authenticate with deis when using a self-signed cert from a debian
system. By default, requests does not trust the system cert bundle on
debian systems and requires either `verify=/path/to/bundle` (as a config
value of requests.Session) or `REQUESTS_CA_BUNDLE=/path/to/bundle`. But,
in order for that environment variable to get read,
`requests.Session.trust_env` must be `True`.
> fix(client): let requests read env vars

- controller/api/models.py
- controller/api/tests/test_build.py
If the old structure contained values like {'web': 0}, the container
count would be zero, so the resulting vals structure would be an empty
dictionary. By taking the "requested" structure and updating it with
the actual container queryset, values like {'web': 0} will stay the
same. From that result, the structure will not be considered in an
["initial" state][1], which means that a new deploy will not cause the
containers to be accidentally scaled back up to one.
[1]: https://github.com/deis/deis/blob/ebc3df479a672acb4a81525ba1edd0fb4d70a6a9/controller/api/models.py#L605
closes #3494
> fix(controller): merge structure with new structure

- contrib/azure/azure-coreos-cluster
- docs/installing_deis/azure.rst
Added a the convenience of recreating azure-user-data for coreos with a new discovery
url. This prevents accidental cluster provisioning without creating a new url which
the user will only realize they did after the coreos has been provisioned and
attempts to connect with deisctl.
> feat(contrib/azure/azure-coreos-cluster): automatically create discovery url

- contrib/coreos/user-data.example
- docs/managing_deis/add_remove_host.rst
This is an attempt to add logic to gracefully remove a node from a cluster when halt, shutdown or reboot units are called on the host.
> feat(contrib): optional graceful shutdown

- client/README.rst
- client/deis.py
- docs/managing_deis/configure-dns.rst
- docs/using_deis/manage-application.rst
- docs/using_deis/using-buildpacks.rst
- docs/using_deis/using-dockerfiles.rst
- tests/utils/itutils.go
1-node clusters are not supported, but the "Configure DNS" docs still referred to them, and several places in the codebase still referred to "local.deisapp.com" instead of "local3".
> docs(configure-dns): drop references to local.deisapp.com

- deisctl/cmd/cmd.go
- deisctl/config/config.go
- deisctl/config/etcd.go
I went with `rm` over `unset` because `etcdctl` uses `rm`. I didn't add any test for this, as there doesn't seem to be any tests for this part of deisctl. If I overlooked where they were let me know. The tests in `config_test` seemed mostly to test the special behavior of keys and not the etcd integration.
Fixes #3515
> feat(deisctl): add config rm

- controller/api/models.py
initial is only equal to the time when the structure has no values, so
it makes no sense to check for initial in any other case.
> ref(controller): remove initial from .deploy()

- builder/rootfs/bin/boot
- builder/rootfs/bin/cleanup
- builder/rootfs/etc/confd/conf.d/check-repos.toml
- builder/rootfs/etc/confd/templates/check-repos
- publisher/server/publisher.go
This fixes two problems in Deis master:
- `deis destroy` leaves a git repo dropping in builder at `/home/git/appname.git`
- `deis scale cmd=0` deletes the `/deis/services/appname` dir after 20 seconds, but that causes the (fixed) `check-repos` script to purge its git repo prematurely
My assumption is that the templating for `check-repos` worked in earlier versions of `confd` that were more specific to `etcd` behavior. This PR switches to `etcd watch` in a loop rather than rely on `confd` templating to launch the script. It also reverts #3348 so that `/deis/services/appname` dirs don't have a TTL, since `deis destroy` deletes them reliably in my testing.
Closes #3249, refs #3348.
> Clean up old git repos and images on destroy

- Vagrantfile
- contrib/azure/azure-coreos-cluster
- contrib/ec2/deis.template.json
- contrib/rackspace/provision-rackspace-cluster.sh
- docs/installing_deis/baremetal.rst
- docs/installing_deis/gce.rst
Linux 4.0.1 kernel. See https://coreos.com/releases/#647.2.0
> chore(*): bump CoreOS to 647.2.0

- contrib/azure/azure-user-data-template
- contrib/ec2/gen-json.py
- contrib/gce/gce-user-data-template
Just specifying that the mount needs to be started before Docker is
insufficient - since Docker is socket activated, it has a chance
to start before the mount. This commit adds a new drop-in unit
which configures Docker to only start after its mount on providers
where we use a separate mount for Docker (AWS, Azure, and GCE).
/cc @jwaldrip
closes #3677
> fix(*): docker.service depends on its mount

- database/build.sh
Deis CI is currently stalled on wal-e/wal-e#181, so this is an attempt to work around the issue by pinning `pbr` to a last-known-good version.
> fix(database): work around wal-e error by pinning pbr lib

- logger/main.go
I was not able to reproduce but I assume there are some situations where the response can be nil (see [godoc](http://godoc/github.com/coreos/go-etcd/etcd#Client.Watch)) or the node in the response is nil (see [godoc](http://godoc/github.com/coreos/go-etcd/etcd#Response)). @bacongobbler can you please try to reproduce with this patch?
closes #3772 
closes #3773
> fix(logger): gracefully handle a nil return from etcd watch

- tests/fixtures/test-etcd/Dockerfile
The `Dockerfile` was incompletely converted over to use Alpine Linux. This fixes that and uses `$ETCD_VERSION` (default: v0.4.9) to download and unarchive `etcd` to /usr/local/bin.
> fix(tests/fixtures): use env var for test-etcd version

- builder/rootfs/bin/boot
- controller/bin/boot
- database/bin/boot
- registry/bin/boot
- store/monitor/bin/boot
refs #3790
This change is necessary as etcdctl globs all server errors as exit code 4, including the infamous `all the given peers are not reachable` as well as `Key already exists`. Instead of checking the error code, we can check what's on stderr so we can safely ignore `Key already exists` "errors".
> fix(*): check for key already exists errors only

- client/deis.py
Fixes a regression where starting up the client in windows would result in a crash, becuase windows does not have support for pipes, and so no SIGPIPE as well.
I didn't test if things still worked in Unix, but I assume they do...
> fix(client): Fix attribute errors on windows

- database/build.sh
This is a slightly better fix for the wal-e runtime error that was hampering CI testing last week.
Refs #3771. See wal-e/wal-e#183.
> fix(database): avoid pbr runtime error by pinning oslo-config

- client/Makefile
I bumped Pyinstaller to the latest commit ([diff](https://github.com/pyinstaller/pyinstaller/compare/7413317...32bbb954b355937ccfe377afbe56979db79a7b30)), to fix pyinstaller/pyinstaller#152, which prevents compilation if the python headers are in certain locations (in my case, where homebrew installed python was subject to this).
I'm not sure what your policy is on bumping Pyinstaller, but I tested the client and it seemed to work after the bump.
This is a major bump, with over 200 commits since the last pyinstaller update, so this definitely needs an careful test.
> fix(client): Bump pyinstaller to fix pyinstaller/pyinstaller#152

- router/image/templates/nginx.conf
Corrects placement of patch from #3768 since `set_random` is only defined within a `location` block.
> fix(router): set_random belongs in a `location` block

- deisctl/backend/backend.go
- deisctl/backend/fleet/journal.go
- deisctl/backend/fleet/ssh.go
- deisctl/client/client.go
- deisctl/cmd/cmd.go
- deisctl/cmd/cmd_test.go
- deisctl/deisctl.go
- docs/troubleshooting_deis/index.rst
**Todo**: You can't list machines or get a machine ID in `deisctl` at the moment, so this isn't useful until normal users can look up a machine ID, rather than use fleetctl to look them up.
We might want to expand this by allowing users to specify a unit, then ssh to the host running the unit, like `fleetctl` does.
``` shell
$ deisctl ssh controller
Last login: Wed Jun  3 02:55:49 2015 from 172.17.8.100
* *    *   *****    ddddd   eeeeeee iiiiiii   ssss
*   *  * *  *   *     d   d   e    e    i     s    s
* *  ***** *****     d    d  e         i    s
*****  * *    *       d     d e         i     s
*   * *   *  * *      d     d eee       i      sss
*****  * *  *****     d     d e         i         s
*   *****  * *      d    d  e         i          s
* *  *   * *   *     d   d   e    e    i …
```
> feat(deisctl): Add deisctl ssh

- tests/bin/test-setup.sh
This has burned me two times too many:
https://github.com/deis/deis/blob/master/tests/ps_test.go#L41
This fixes an issue where integration tests that would otherwise
succeed, locally, fail close to the end because the user executing
the tests has set the DEIS_DRINK_OF_CHOICE environment variable,
which interferes with the assertion that the default beverage to
be enjoyed whilst scaling is coffee.  This corrects that problem
by unsetting the DEIS_DRINK_OF_CHOICE environment variable prior
to testing.
> fix(tests): fix assertions on default beverage

- client/deis.py
- controller/api/__init__.py
- controller/api/permissions.py
- controller/api/tests/test_auth.py
- controller/api/urls.py
- controller/api/views.py
- docs/managing_deis/operational_tasks.rst
- docs/reference/api-v1.5.rst
- docs/reference/index.rst
- tests/auth_test.go
If a token was leaked, it could be regenerated with: `deis auth:regenerate`. Admin can regenerate a user's token with `deis auth:regenerate -u user` and could also regenerate everybody's auth token, in the event of a security breach, with `deis auth:regenerate --all=true`
> feat(controller): Add endpoint to regenerate tokens

- deisctl/cmd/cmd.go
Units were being refreshed without their extension, causing the fleet backend to be unable to find them when installing.
Fixes #3832
> fix(deisctl): Add extension when refreshing units

- deisctl/client/client.go
- deisctl/cmd/cmd.go
- deisctl/cmd/cmd_test.go
- deisctl/config/config.go
This abstracts the command line parsing away from the CMD package. Now the CMD package takes function arguments. The client package now transform the command line flags into function arguments.
Why do this?
1. This makes the CMD package much easier to test. Now you can pass function arguments rather than call the function with unparsed command line input.
2. Limits the scope of docopt. Now docopt only is part of the main and client package. If we decide to change the CLI framework, the majority of our code is now unaffected.
3. More idiomatic code. Instead of passing the command line input to every function, which contains an unknown amount of flags, we now pass sane arguments, making the code much more understandable and making function input much clearer.
> ref(deisctl): Move parsing from CMD package to client package

- client/Makefile
- contrib/util/add_server_dev_deps.sh
- controller/Makefile
- controller/build.sh
- database/build.sh
- docs/Makefile
- registry/build.sh
- tests/bin/test-integration-ec2.sh
The constant reminders that pip has a new version involve a network transaction and are not helpful to our build process, and some python libraries were being inadvertently cached at /root/.cache/ inside Docker images.
> ref(*): disable pip version check and caching

- builder/rootfs/etc/confd/templates/check-repos
The wildcard caused an off-by-one error where if no git repositories
existed, the wildcard was then interpreted, causing all images prefixed
with the registry IP address to be removed inside builder.
As an example:
$ for repo in *.git; do echo $repo; done
*.git
$ for repo in $(ls | grep .git); do echo $repo; done
$ mkdir foo.git
$ for repo in *.git; do echo $repo; done
foo.git
$ for repo in $(ls | grep .git); do echo $repo; done
foo.git
closes #3862
> fix(builder): call ls rather than using a wildcard

- deisctl/backend/fleet/create.go
- deisctl/backend/fleet/destroy.go
- deisctl/backend/fleet/fleet.go
- deisctl/backend/fleet/journal.go
- deisctl/backend/fleet/list_unit_files.go
- deisctl/backend/fleet/list_units.go
- deisctl/backend/fleet/registry.go
- deisctl/backend/fleet/ssh.go
- deisctl/backend/fleet/status.go
:fire: Some global variables in favor of member variables. It makes the code cleaner and easier to test.
> ref(deisctl): remove global variables in backend package

- deisctl/deisctl.go
> fix(deisctl): return 0 when only printing version

- builder/rootfs/etc/confd/templates/builder
When a Procfile isn't present in a `git push` operation, builder tries to extract or fabricate one, but the tar commands would fail with "invalid tar magic" since the compression flag "z" was missing.
I tested this by removing the Procfile from [example-play]() and committing it before `git push`. It failed before this change, but afterward the Procfile was correctly filled in (here's with debug output):
```console
Successfully built 39111ec4e108
+ puts-step 'Pushing image to private registry'
+ echo '-----> Pushing image to private registry'
-----> Pushing image to private registry
+ docker push 172.17.8.100:5000/ultima-underdog:git-f67f5ca1
+ echo
+ '[' -f Procfile ']'
+ '[' -f /home/git/ultima-underdog.git/build/tmp.B9dJa9cCgo/slug.tgz ']'
+ tar -tzf …
```
> fix(builder): add "z" flag for compressed tar archives

- controller/api/models.py
- controller/api/tests/test_scheduler.py
- controller/scheduler/swarm.py
fix(controller): roll back if scale fails
fixes #3605 
Log_event method was implemented in scheduler and app.id is passed to scheduler record logs to app logs. Rollback happens if any of the container state is not in created.  
```
$ deis scale cmd=7
Scaling processes... but first, coffee!
503 Service Unavailable
Detail:
aborting, failed to create some containers rolling back
reshut2-82-75-dhcp:example-dockerfile-http smothiki$ deis logs
2015-05-14T23:13:45UTC deis[api]: smothiki created initial release
2015-05-14T23:14:34UTC deis[api]: smothiki deployed 6578692
2015-05-14T23:14:35UTC deis[api]: smothiki scaled containers cmd=1
2015-05-14T23:15:54UTC deis[api]: smothiki changed limits for memory
2015-05-14T23:45:46UTC deis[api]: smothiki scaled containers cmd=5
2015-05-14T23:46:38UTC …
```
> fix(controller): Roll back scale on failure

- client/Makefile
- deisctl/Makefile
The ANSI color codes used in the "all done" installer messages won't print correctly on some platforms without using "echo -e", but the "-e" flag isn't recognized on all platforms.
Closes #3852.
> fix(client+deisctl): remove colors from installer messages

- docs/customizing_deis/router_settings.rst
- router/image/templates/deis.conf
- router/image/templates/nginx.conf
This allows a custom ordered ciphersuite list to be used. For recommendations, read [Mozilla's guide to Server Side TLS](https://wiki.mozilla.org/Security/Server_Side_TLS)
One might use their modern compatibility list like so:
```bash
deisctl config router set sslCiphers='ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DE …
```
> feat(router): read list of preferred ciphers

- deisctl/config/config.go
- docs/customizing_deis/router_settings.rst
- router/image/conf.d/dhparam.pem.toml
- router/image/templates/deis.conf
- router/image/templates/dhparam.pem
The openssl defaults for Ephemeral Diffie-Hellman exchange are considered by some to be inadequate.
Generate a 2048-bit key and upload to the cluster with:
```
openssl dhparam -out ./dhparam.pem 2048
deisctl config router set sslDhparam=./dhparam.pem
```
> feat(router): add Diffie-Hellman parameter for DHE ciphersuites

- builder/Makefile
- deisctl/Makefile
- logger/Makefile
- logspout/Makefile
- publisher/Makefile
- router/Makefile
- swarm/Makefile
- tests/Makefile
Many components have a Makefile with `GO_FILES` hard-coded to the list of .go files in the current directory. Using the `wildcard` func will stop the need for this maintenance.
I noticed we weren't linting `domains_test.go` and `users_test.go`, then decided to fix it in general rather than just add two more files to tests/Makefile.
> ref(Makefiles): use wildcard for GO_FILES

- docs/customizing_deis/router_settings.rst
- router/boot.go
- router/image/templates/nginx.conf
When browsers see the HSTS header on an HTTPS request then they rewrite
all links for the current domain that point at HTTP resources to point
to HTTPS resources. When /deis/router/enforceHTTPS is set, using HSTS
avoids the extranneous 301 redirect to the HTTPS resource and prevents
[some threats][1]. The HTTPS Strict Transport Security header mechanism
is defined in [RFC-6797][2]
[1]: https://www.owasp.org/index.php/HTTP_Strict_Transport_Security
[2]: https://tools.ietf.org/html/rfc6797
> feat(router): enable HSTS when enforceHTTPS is set

- deisctl/deisctl.go
- deisctl/deisctl_test.go
Note: `./deisctl` will trigger a docopt error because it wasn't given any command line arguments. However, this error is empty, so go just prints an empty line. I think it looks better, but it is a slight change in behavior.  The advantage is that if docopt has an actual error, instead of throwing it away like we currently do we print it.
Before:
``` shell
$ deisctl
Usage: deisctl [options] <command> [<args>...]
$
```
After:
``` shell
$ deisctl
Usage: deisctl [options] <command> [<args>...]
$
```
> ref(deisctl): clean up some parsing and error behavior

- contrib/linode/.gitignore
- contrib/linode/README.md
- contrib/linode/apply-firewall.py
- contrib/linode/create-linode-user-data.py
- contrib/linode/linode-user-data-template.yaml
- contrib/linode/provision-linode-cluster.py
- contrib/linode/requirements.txt
- docs/installing_deis/index.rst
- docs/installing_deis/linode.rst
- docs/installing_deis/quick-start.rst
Linode's recent switch to KVM gave me an added push to rewrite our team's provisioning tools to work with the new hypervisor as it makes running CoreOS much simpler. This time, I did so with the intention of fully documenting the process for the community and our team at Myriad Mobile as well as make our tools publicly available. So here's a stab at that!
> feat(contrib/linode): add Linode provision scripts and docs

- contrib/README.md
Add a link to my backup and restore tool. With it and a couple other tools I haven't cleaned up yet, I can restore a cluster from complete failure in under an hour. I hope to add the ability to encrypt backup data soon.
> docs(contrib): add link to Deis Backup and Restore

- deisctl/backend/fleet/fleet_test.go
- deisctl/backend/fleet/scale_test.go
- deisctl/backend/fleet/ssh_test.go
- deisctl/backend/fleet/status_test.go
- deisctl/backend/fleet/unit_test.go
- deisctl/backend/fleet/utils_test.go
- deisctl/cmd/cmd_test.go
The original code was very hackish. I discovered the `Error()` method and updated the code to use that. Sorry for the original horrible code :frowning:
> ref(deisctl): fix error to string conversion in tests

- deisctl/backend/fleet/create_test.go
- deisctl/backend/fleet/destroy_test.go
- deisctl/backend/fleet/fleet_test.go
- deisctl/backend/fleet/journal_test.go
- deisctl/backend/fleet/list_unit_files_test.go
- deisctl/backend/fleet/list_units_test.go
- deisctl/backend/fleet/registry_test.go
- deisctl/backend/fleet/scale_test.go
- deisctl/backend/fleet/ssh_test.go
- deisctl/backend/fleet/start_test.go
- deisctl/backend/fleet/status_test.go
- deisctl/backend/fleet/stop_test.go
- deisctl/backend/fleet/unit_test.go
- deisctl/backend/fleet/utils_test.go
- deisctl/cmd/cmd_test.go
- deisctl/config/config_test.go
- deisctl/utils/utils_test.go
In theory this should speed your builds up. We should test to confirm that there is a performance benefit.
``` shell
$ time make -C deisctl test
...
real 0m21.975s
user 0m15.506s
sys  0m4.569s
```
``` shell
$ GOMAXPROCS=4 time make -C deisctl test
...
15.98 real        15.70 user         6.10 sys
```
I'd appreciate it if anybody has any time to test this and report if this had enough impact to warrant merging
> test(deisctl): parallelize all of the things

- builder/rootfs/Dockerfile
- controller/Dockerfile
- database/Dockerfile
- registry/Dockerfile
- store/base/build.sh
See https://github.com/kelseyhightower/confd/releases/tag/v0.10.0
Tested manually to ensure no dotfiles were left in builder's `/home/git` directory. Note that router is still using a customized post-v0.9.0 version of `confd`, which I left intact for now. Thanks to @bacongobbler for making the `confd` release happen!
Closes #3570.
> chore(*): update confd to v0.10.0

- contrib/README.md
- docs/managing_deis/backing_up_data.rst
The page with contributed tools is a bit hard to find. Maybe include the backup/restore tools on the backup page?
> docs(backing_up_data): Add community tools for reference

- docs/_includes/_deis-pro.rst
- docs/installing_deis/aws.rst
- docs/installing_deis/quick-start.rst
Moves the link to Deis Pro to a snippet, and includes it on both the
Quick Start and AWS installation guides.
> docs(installing_deis): include Deis Pro in AWS docs

- docs/conf.py
- docs/docs_requirements.txt
ReadTheDocs.org doesn't have libldap2-dev installed in its build environment, which prevents python-ldap from building, which prevents generating Deis' [python autodocs](http://docs.deis.io/en/latest/reference/client/). This makes the dependency unnecessary by mocking the required modules.
Closes #3909, refs rtfd/readthedocs.org#1363
> fix(docs): mock out python ldap modules

- registry/bin/reload
The registry reload script had been broken since the busybox / alpine linux version of `pkill` didn't understand the `-u` flag. I tested this command interactively in a running `deis-registry` container, and `-f` is necessary to actually match the `gunicorn` processes as well.
This fixes this type of output (see line 3):
```
--- Run deisci/registry:jenkins-test-ec2-1546 at 10.164.164.159:57631
Error response from daemon: No such container: deis-registry-jenkins-test-ec2-1546
2015-06-30T18:09:43Z 5d0a83f3e232 confd[20]: ERROR "invalid option -- u\nBusyBox v1.22.1 (2015-03-20 11:09:37 GMT) multi-call binary.\n\nUsage: pkill [-l|-SIGNAL] [-fnovx] [-s SID|-P PPID|PATTERN]\n\nSend a signal to process(es) selected by regex PATTERN\n\n\t-l\tList all signals\n\t-f\tMatch against entire command …
```
> fix(registry): run pkill as registry user, removing "-u"

- builder/rootfs/bin/boot
On start, the slugbuilder and slugrunner images are built from
the builder's source directory. This is unnecessary on restarts,
and prevents optimizations where the slugbuilder and slugrunner images
are already pre-cached (for example, by bind-mounting a host volume
into builder with the images).
This commit simply wraps these `docker build` instructions in
`docker history` checks to see if the images exist before
attempting to build them.
/cc @iancoffey @technosophos
> fix(builder): only build slugbuilder/slugrunner when necessary

- logger/drain/drain.go
Sending a log to an external server should not kill the logger on an error. For example, if the host is down or unavailable, the logger should just log that the error message has been lost, but carry on.
> fix(logger): reduce severity of log failure

- docs/reference/server/api.authentication.rst
- docs/reference/server/api.middleware.rst
- docs/reference/server/api.permissions.rst
- docs/reference/server/api.viewsets.rst
- docs/reference/server/index.rst
- docs/reference/server/scheduler.rst
After #3935 fixed our Sphinx autodoc for python, I noticed several modules were missing and added them.
> docs(reference): add missing packages to autodoc

- deisctl/cmd/cmd.go
- deisctl/cmd/cmd_test.go
- deisctl/cmd/platform.go
- deisctl/units/deis-controller.service
- docs/_includes/_ceph-dependency-description.rst
- docs/managing_deis/index.rst
- docs/managing_deis/production_deployments.rst
- docs/managing_deis/running-stateless-cluster.rst
Adds support to `deisctl` so users can specify `stateless-platform` instead of `platform` for `deisctl install`, `deisctl start`, `deisctl stop`, and `deisctl uninstall`. This new command will skip `store-*`, `database`, and `logger` components.
Also adds documentation from @Blystad detailing how to run a stateless cluster, although the instructions have been adapted to make use of the new `stateless-platform` command in `deisctl`.
I think this is enough support to consider #2812 closed. We can probably refine this in the future, such as removing the dummy `deis-store-volume` component, but I think it's a good start.
replaces #3945
closes #2812 
/cc @Blystad @krancour @lazabogdan
> feat(deisctl): support stateless control plane without Ceph

- registry/build.sh
See https://github.com/deis/docker-registry/compare/new-repository-import-v091...deis:new-repository-import-master. It was suggested to me at DockerCon that some post-v0.9.1 fixes in classic registry could improve stability, and that `gevent` and/or `gunicorn` had been buggy, so this rebases our fork and updates those packages. If #3814 isn't ready for the next release, this is worth testing to see if it fixes classic registry stability issues.
Refs #3479.
> chore(registry): use updated registry V1 fork

- builder/rootfs/bin/boot
Tested interactively with `make -C builder/ build deploy`.
Closes #3958.
> fix(builder): set private key perms to 0600

- controller/api/models.py
- controller/api/tests/test_config.py
- controller/deis/settings.py
- docs/managing_deis/backing_up_data.rst
- docs/using_deis/config-application.rst
- publisher/server/publisher.go
- publisher/server/publisher_test.go
- tests/config_test.go
closes #3813 
Note that this is considered a breaking change as all apps are enforced to have a health check. By default this checks for a 200 OK response at the root URL, but users can configure this by setting HEALTHCHECK_URL and HEALTHCHECK_STATUS_CODE.
> feat(publisher): check app config for HTTP health check

- builder/rootfs/bin/cleanup
Changes to the builder `cleanup` script added uninformative log messages because `etcdctl watch` prints the value of the key that triggered it:
```console
$ etcdctl -C 10.21.2.201:4001 watch --recursive /deis/services
10.21.1.47:32788
$ etcdctl -C 10.21.2.201:4001 watch --recursive /deis/services > /dev/null
$
```
This redirects non-error output to `/dev/null`, which will clean up the builder log. Thanks to @bacongobbler for pinpointing the problem.
Closes #3986.
> fix(builder): ignore etcdctl stdout in cleanup script

- publisher/server/publisher.go
This fixes a confusing log message:
```
Jul 07 17:49:54 ip-10-21-1-91.us-west-2.compute.internal sh[3320]: 2015/07/07 17:49:53 healthcheck failed for http://10.21.1.91:32811/ (expected 200, got Get http://10.21.1.91:32811/: read tcp 10.21.1.91:32811: connection reset by peer)
```
Now it should read
```
Jul 07 17:49:54 ip-10-21-1-91.us-west-2.compute.internal sh[3320]: 2015/07/07 17:49:53 healthcheck failed for http://10.21.1.91:32811/ (Get http://10.21.1.91:32811/: read tcp 10.21.1.91:32811: connection reset by peer)
```
> fix(publisher): display http error if connection failed

- docs/managing_deis/index.rst
- docs/managing_deis/production_deployments.rst
- docs/managing_deis/running-deis-without-ceph.rst
@gabrtv pointed out that calling it a stateless platform isn't quite yet correct. Even though the `deisctl` command is `deisctl install stateless-platform`, clarifying the documentation should be sufficient.
> docs(managing_deis): rename stateless platform docs

- Vagrantfile
- contrib/azure/azure-coreos-cluster
- contrib/ec2/deis.template.json
- contrib/linode/provision-linode-cluster.py
- contrib/rackspace/provision-rackspace-cluster.sh
- docs/installing_deis/baremetal.rst
- docs/installing_deis/gce.rst
Newer CoreOS releases include Docker 1.6, which is fundaementally
broken for simultaneous pulls of the same filesystem layers -
see https://github.com/docker/docker/issues/9997
> chore(*): revert CoreOS to 647.2.0

- controller/api/models.py
- controller/api/tests/test_config.py
- controller/deis/settings.py
- docs/managing_deis/backing_up_data.rst
- docs/using_deis/config-application.rst
- publisher/server/publisher.go
- publisher/server/publisher_test.go
- tests/config_test.go
this new feature does not give the user a true zero-downtime effect as what was expected from #3813, so in order to ship 1.8 we're pulling it out and going to try again for v1.9. I'll also be closing #3982 and re-introducing a new PR for this.
re-opens #3813.
> fix(controller): revert HTTP healthcheck feature

- router/build.sh
The archive is downloaded over insecure connection. Added a SHA256 checksum verification. The checkum can be generated by person updating the scipt, after manually verifying their own downloaded nginx archive via provided PGP signature (http://nginx.org/download/$VERSION_NGINX.tar.gz.asc).
> Add verification of downloaded nginx archive.

- controller/scheduler/fleet.py
- deisctl/units/deis-builder.service
- deisctl/units/deis-cache.service
- deisctl/units/deis-controller.service
- deisctl/units/deis-database.service
- deisctl/units/deis-logger.service
- deisctl/units/deis-logspout.service
- deisctl/units/deis-publisher.service
- deisctl/units/deis-registry.service
- deisctl/units/deis-router.service
- deisctl/units/deis-store-admin.service
- deisctl/units/deis-store-daemon.service
- deisctl/units/deis-store-gateway.service
- deisctl/units/deis-store-monitor.service
- deisctl/units/deis-swarm-manager.service
- deisctl/units/deis-swarm-node.service
@jwaldrip reported in #3885 that we seemingly leave behind orphaned containers that are not cleaned up after they are removed. This PR ensures all unit files use `--rm` to automatically clean up the container (`database` was lacking it before). This also removes the unnecessary `ExecStopPost` to clean up the container, as this is seemingly unnecessary (and may not even work). A side benefit of this change is that we no longer see "container does not exist" in the Docker logs whenever a service is stopped (as the container is already cleaned up by the time the `ExecStopPost` hits).
Note that we don't change the run template in the fleet scheduler to use `--rm` since as @bacongobbler mentioned, we have to log in and perform a `docker inspect` to check on the success of the container. …
> fix(*): ensure container removal with --rm

- CONTRIBUTING.md
- docs/contributing/design-documents.rst
- docs/contributing/hacking.rst
- docs/contributing/index.rst
- docs/contributing/overview.rst
- docs/contributing/standards.rst
Please review and criticize. I tried not to overuse the term "changes", but I wanted a word that was general enough to include any sort of change: features, major bug fixes, refactors, etc.
All input is welcome!
> docs(contributing): add section on Design Documents

- router/build.sh
The commit c7c895c fixes the affinityArg hashing issue by using the
`set_random` directive on the nginx configuration, but forgets to
include the module in which it is declared. This commit fixes this,
while also tries to make the build script a little cleaner and
include integrity checks for all downloads.
Closes #3964.
Replaces #4008.
Includes (and extends) verifications added by #3954.
> fix(router): add set-misc module to nginx build

- controller/api/tests/test_key.py
- controller/api/views.py
Users were unable to remove their SSH keys. This PR fixes the Key management view configuration that was blocking the API access. The wrong view configuration was being inherited from `api.views.BaseDeisViewSet`. 
Error using API directly:
```
$ http DELETE deis.platform/v1/keys/rochacon@machine.local "Authorization:token <rochacon-token>"
HTTP/1.1 403 FORBIDDEN
Allow: GET, DELETE, HEAD, OPTIONS
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
DEIS_API_VERSION: 1.4
DEIS_PLATFORM_VERSION: 1.7.3
Date: Sat, 27 Jun 2015 00:58:41 GMT
Server: nginx/1.9.0
Transfer-Encoding: chunked
Vary: Accept-Encoding
X_DEIS_API_VERSION: 1.4
X_DEIS_PLATFORM_VERSION: 1.7.3
{
"detail": "You do not have permission to perform this action."
}
```
Error using the CLI:
```
$ deis keys
=== …
```
> fix(controller): allow non superusers to manage their keys

- pkg/prettyprint/colorizer.go
- pkg/prettyprint/colorizer_test.go
This provides pretty printing features for the following:
- Colorized Deis logos
- Colorized messages
- Line replacement messages (i.e. when one line overwrites the previous line)
> feat(pkg/prettyprint) support colorizing terminal text

- contrib/util/commit-msg
> fix(contrib): warn if commit subject is too long

- contrib/util/commit-msg
`git commit ammend` has comments about the files changed. If you had a comment longer than the limit the hook would throw an error. Now the hook ignores comments.
> fix(commit-msg): ignore comments in line count

- controller/requirements.txt
- docs/README.md
- docs/docs_requirements.txt
This warning text helped to build the python gevent library
when Apple's compiler first switched to clang, but has not
been necessary to build Deis on Mavericks or Yosemite 
for a long time now.
> docs(requirements): remove old warning about clang

- docs/understanding_deis/concepts.rst
The `the` was unlinked and I think it looks better missing. Feel free to close if others think it looks better unchanged.
> docs(concepts): remove unlinked 'the'

- logger/main.go
In a separate goroutine, we were sleeping for the exact same time as
publishInterval was set to. As @kalbasit mentioned in [a comment][1],
it's better to use a ticker anyways. This removes one extra underlying
system call to clock_gettime() by making both publishKeys() and the
log drain poll share the same ticker event.
refs #4030, as I found this using the .scap dump. I don't think this will
drop the CPU usage significantly, but it's a start.
[1]: https://github.com/deis/deis/pull/3795#discussion_r31878237
> fix(logger): use one ticker for all time-related operations

- builder/Makefile
- cache/Makefile
- logger/Makefile
- logspout/Makefile
- publisher/Makefile
- router/Makefile
The [`check-static-binary`](https://github.com/deis/deis/blob/master/includes.mk#L55) Makefile function echoes itself to stdout with every invocation. This silences it unless it actually finds an error.
ping @technosophos
> fix(Makefiles): silence static binary check

- client-go/controller/client/auth.go
- client-go/controller/client/http.go
If the request aborted due to an error the body didn't exist and
the deferred function would throw a nil pointer exception.
Reported by yebyen on IRC.
Example panic: http://pastebin.com/NsjfvEWf
> fix(client-go): defer deferred closing of body until after error check.

- docs/installing_deis/gce.rst
Resolves:
```
WARNING: Lists should be separated by commas, try "--metadata-from-file user-data=gce-user-data,sshKeys=/Users/Thijs/.ssh/deis.pub". If you intend to use sshKeys=/Users/Thijs/.ssh/deis.pub for positional arguments, put them before the flag.
WARNING: Lists should be separated by commas, try "--disk name=cored3,device-name=coredocker". If you intend to use device-name=coredocker for positional arguments, put them before the flag.
```
> fix(contrib/gce): updated GCE docs with new cloud dns config and commas

- controller/Dockerfile
- database/Dockerfile
- mesos/build-marathon
- mesos/template
- router/image/Dockerfile
The mesos components didn't all set `DEBIAN_FRONTEND` to `noninteractive`, so there were several build warnings about not finding a TTY. Additionally, some Alpine images still had a vestigial `DEBIAN_FRONTEND` statement.
> fix(Dockerfiles): silence apt-get TTY warnings

- builder/rootfs/bin/boot
Fix for random error:
```
Jul 21 22:46:12 ip-10-21-2-14.us-west-2.compute.internal systemd[1]: Starting deis-builder...
Jul 21 22:46:12 ip-10-21-2-14.us-west-2.compute.internal sh[26341]: deis-builder
Jul 21 22:46:12 ip-10-21-2-14.us-west-2.compute.internal sh[26370]: /dev/loop0
Jul 21 22:46:12 ip-10-21-2-14.us-west-2.compute.internal sh[26374]: Waiting for builder on 2223/tcp...
Jul 21 22:46:13 ip-10-21-2-14.us-west-2.compute.internal docker[26493]: 2015/07/21 22:46:13 docker-exec: failed to exec: exec: "/usr/local/bin/push-images": stat /usr/local/bin/push-images: no such file or directory
Jul 21 22:46:13 ip-10-21-2-14.us-west-2.compute.internal systemd[1]: deis-builder.service: control process exited, code=exited status=1
Jul 21 22:46:13 ip-10-21-2-14.us-west-2.compute.internal …
```
> fix(builder):wait until push-images script exists

- mesos/Makefile
The mesos binaries are built as static, so this adds the silent double-check that is done in all other cases.
> style(mesos): check for static go binaries

- mesos/Makefile
- mesos/build-marathon
- mesos/marathon
- mesos/master
- mesos/slave
- mesos/template
- mesos/zookeeper/Dockerfile
Ensure that the mesos-* and zookeeper images honor the same env vars used in other "make build" targets, and add the `DEIS_RELEASE` variable.
The `IMAGE_PREFIX` variable contains a trailing slash, so I used `@` as an alternate separator for `sed`.
ping @smothiki
> fix(mesos): build images with prefix and tag

- deisctl/units/deis-database.service
When performing an upgrade, any db records added since the last backup are lost. This becomes obvious when testing upgrades, but should occur anytime the database is stopped and started.
The thought here is that a backup be done proactively on stop to avoid it. Maybe theres a better place for it, but this does "work".
> feat(database): backup the db on unit stop

- deisctl/backend/fleet/fleet_test.go
- deisctl/backend/fleet/start.go
- deisctl/backend/fleet/start_test.go
- deisctl/backend/fleet/stop.go
- deisctl/backend/fleet/stop_test.go
This fixes issue #3880, where a failed start or stop command will hang
deisctl. The fix simply prints out an error message and exits from the
resolution loop.
> fix(deisctl): exit when stop/start fails

- Vagrantfile
- contrib/coreos/user-data.example
This is a minimal subset of #3868 with one critical difference: `--iptables=false` has been omitted from the drop-in for `docker.service`.  The result is that docker manages iptables rules _in addition_ to those that are managed by flannel.  The result is that port mappings continue to function as they always have-- the benefit of which is that no changes are required to any Deis components.  With no changes to components required, upgrades should work smoothly.
I'd appreciate any help I can get in verifying / validating those finding and / or making swiss cheese out of this approach.  :)
Majority credit to @aledbf!
> feat(platform): add overlay network

- deisctl/client/client.go
- deisctl/cmd/cmd.go
- deisctl/cmd/cmd_test.go
When installing the platform with deisctl, 3 routers are started by
default. This causes an annoying freeze when you use custom component
placement and you have less than 3 instances flagged as routerMesh.
Setting the $DEIS_NUM_ROUTERS variable prior calling "deisctl install
platform" will allow you to choose how many routers are to be installed
in your cluster.
> feat(deisctl): specify # of routers to install

- Vagrantfile
This fixes the "too many redirects" problem that seems to occur (particularly on Yosemite) during `docker pull`-- particularly when `deis-builder` is building the slugbuilder.
This issue discusses the problem and solution with respect to `boot2docker`:
https://github.com/boot2docker/boot2docker/issues/451
This PR merely applies the same fix to all our Vagrant-managed VMs via the `Vagrantfile`.
Ping @jchauncey-- I think you said you were having this issue too.  Can you confirm this helps you as well?
> fix(vagrant): fix too many redirects problem

- deisctl/backend/backend.go
- deisctl/backend/fleet/ssh.go
- deisctl/client/client.go
- deisctl/cmd/cmd.go
- deisctl/cmd/cmd_test.go
- deisctl/deisctl.go
- docs/troubleshooting_deis/index.rst
This feature extends 'deis ssh' to allow for an arbitrary command.
If specified, the command will be run as an SSH Exec call, instead
of opening a new shell.
Further, this adds 'deis dock', which is a convenience wrapper
for 'deis ssh THING docker exec -it THING COMMAND'. This now
becomes 'deis dock THING COMMAND'.
Testing:
After installation, you should be able to run all of the following commands:
- `deis ssh deis-builder`: Works as normal.
- `deis ssh deis-builder ls -la`: Runs `ls -la` on the host that is running builder.
- `deis dock deis-builder sh`: Starts a shell on the `deis-builder` container.
> feat(deisctl): extend SSH to allow exec and docker

- client-go/cmd/apps.go
- client-go/controller/client/git.go
> fix(client-go): make output from apps:destroy match python client

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/coreos/fleet/unit/fake.go
- Godeps/_workspace/src/github.com/coreos/fleet/unit/manager.go
Doesn't seem like anything too important, but it's probably a good idea to keep the vendored fleet up to date with the version on CoreOS.
> chore(deisctl): update vendored fleet code to 0.9.2

- contrib/coreos/user-data.example
Current versions of CoreOS (including 647.2.0) don't need any help: docker starts with overlayfs as its backend storage driver regardless. I verified this on Vagrant and AWS.
Replaces #4128. It's easier to do this as smaller PRs.
Refs #3975, since we need to shrink user-data a bit to accomodate those changes. *Edit*: never mind, #3975 shrunk itself enough to pass without other changes.
> ref(user-data): remove load-overlay-module

- tests/utils/itutils.go
var Deis will always have at least one space.
> fix(tests): fixup deis binary lookup

- docs/managing_deis/production_deployments.rst
This commit adds a section to the managing_deis/production_deployment documentation
that explains how to disable or set registrations to adminOnly.
> docs(managing_deis): add section for registrationMode

- controller/scheduler/__init__.py
- controller/scheduler/chaos.py
- controller/scheduler/fleet.py
- controller/scheduler/k8s.py
- controller/scheduler/mesos_marathon.py
- controller/scheduler/mock.py
- controller/scheduler/swarm.py
Defines a `SchedulerClient` class to represent the interface that schedulers should implement, and subclasses existing schedulers from that. `attach` was unimplemented anywhere, so I removed it.
Also normalizes some code comments and removes extra code.
> ref(controller): share common scheduler code

- controller/bin/boot
Corrects an error that crept in to bin/boot from #4126 which I saw in the controller logs:
```
Jul 30 19:29:23 deis-01 sh[15058]: grep: ]]: No such file or directory
Jul 30 19:29:23 deis-01 sh[15058]: grep: ]]: No such file or directory
Jul 30 19:29:23 deis-01 sh[15058]: grep: ]]: No such file or directory
Jul 30 19:29:23 deis-01 sh[15058]: grep: ]]: No such file or directory
Jul 30 19:29:24 deis-01 sh[15058]: grep: ]]: No such file or directory
Jul 30 19:29:24 deis-01 sh[15058]: grep: ]]: No such file or directory
```
> fix(controller): remove extra bracketing

- deisctl/client/client.go
"deisctl ssh" and "deisctl dock" need open-ended command-line parsing to allow unquoted commands to be run. But this short-circuits the normal way docopt would print the usage string.
Currently `deisctl help dock` or `deisctl --help ssh` or variants won't display their detailed usage strings. This fixes that, but still allows those two commands to swallow everything that follows on the command line.
The code compares `target` only to "--help" because earlier parsing code translated "help" and "-h" to "--help"
> fix(deisctl): allow help for ssh and dock

- controller/templates/gconf.py
This prevents a negative number being used for deis-controller gunicorn workers:
```console
$ deisctl config controller set workers=-1
```
Otherwise, the above command leads to the controller spawning no workers and effectively becoming unresponsive:
```
Jul 30 19:28:04 deis-01 sh[9745]: [2015-07-30 19:28:04 +0000] [119] [INFO] Handling signal: hup
Jul 30 19:28:04 deis-01 sh[9745]: [2015-07-30 19:28:04 +0000] [119] [INFO] Hang up: Master
Jul 30 19:28:04 deis-01 sh[9745]: Invalid value for workers: -1
Jul 30 19:28:04 deis-01 sh[9745]: Error: Value must be positive: -1
```
> fix(controller): prevent < 1 gunicorn workers

- contrib/linode/provision-linode-cluster.py
> fix(contrib/linode): Install CoreOS from the stable channel

- mesos/build-marathon.sh
Fixes a shell quoting bug introduced by #4154 that silently broke `ls` in building the mesos-marathon image.
Closes #4190.
> fix(mesos): quote properly in marathon build

- controller/scheduler/mesos_marathon.py
Creating the app by default starts an instance of container. Scaling down to zero doesn't destroy app container. this fixes that by creating an APP with zero instances.
> fix(mesos-marathon): change instances to zero instead of scale to zero

- docs/customizing_deis/router_settings.rst
- router/image/conf.d/ssl.conf.toml
- router/image/templates/deis.conf
- router/image/templates/nginx.conf
- router/image/templates/ssl.conf
This pull will enable ssl session caching by default and reduce the ssl_buffer size to 4k to slightly increase the time-to-first-byte. Additionally it makes ssl_protocols configurable.
I split out the SSL configuration to a separate config file. As a side effect, the ssl_dhparam option is now affecting domain certificates, as it was likely intended to.
With the current SSL settings and these, it's now possible to score an A+ on https://www.ssllabs.com/ssltest.
> feat(router): enable ssl caching and expose ssl_protocols for configuration

- builder/rootfs/usr/local/src/slugbuilder/builder/build.sh
SSH is now configured regardless of whether a custom buildpack was specified.
Fixes #4172.
> fix(builder): always configure SSH key

- contrib/coreos/user-data.example
Hitting the /v2/stats/leader endpoint would only work on the etcd
leader. Instead, we hit /v2/stats/self which will always work.This
doesn't show stats from the other members, but a user could start
the service on all hosts.
> fix(contrib): fix debug-etcd

- deisctl/units/deis-kube-apiserver.service
- deisctl/units/deis-kube-controller-manager.service
- deisctl/units/deis-kube-kubelet.service
- deisctl/units/deis-kube-proxy.service
- deisctl/units/deis-kube-scheduler.service
The various kube-* binaries all exit with a return code of 2 on CTRL+C / SIGQUIT|TERM|KILL. This change considers 2 to be a successful k8s service exit as well, to avoid systemd failures on `deisctl stop k8s`.
See http://www.freedesktop.org/software/systemd/man/systemd.service.html#SuccessExitStatus= for background docs.
Closes #4213.
> fix(deisctl/units): stop k8s services without errors

- .gitignore
- client-go/cmd/auth.go
- client-go/cmd/keys.go
- client-go/controller/client/client.go
- client-go/controller/client/home_unix.go
- client-go/controller/client/home_windows.go
- client-go/controller/client/utils.go
- client-go/controller/client/webbrowser_windows.go
- client-go/make.bat
This PR adds very minimal windows support to client-go.
1. Add a batchfile so it can be built on windows.
2. `apps:open` launches the default web browser.
3. Uses `%HOMEDRIVE%` and `%HOMEPATH%` on windows instead of `$HOME`.
Current issues:
1. Test will not pass on windows, as tests expect unix behavior.
> feat(client-go): add minimal windows support

- Makefile
The swarm-* components, like mesos-*, are optional and not installed by default. This removes swarm from `COMPONENTS` in the root Makefile, so that it must be built or installed explicitly: `make -C swarm/ build`.
Closes #4156.
> fix(Makefile): don't build swarm by default

- deisctl/units/deis-controller.service
Fixes #4209 
`deis-controller.service` mounts `/var/run/fleet.sock` as a volume, but wasn't previously expressing `fleet.socket` as a dependency.  The result was that if `fleet.socket` wasn't up, `/var/run/fleet.sock` would get created as an _empty directory_ when the `deis-controller.service` started.  Obviously, that's A Bad Thing™ for `deis-controller`.
This fixes that.  :)
Thanks @ineu for finding this problem!
> fix(controller): require fleet.socket

- router/build.sh
Includes `ssl_stapling` fixes possibly relevant to #3900. See http://nginx.org/en/CHANGES.
> chore(router): update nginx to 1.9.3

- client-go/pkg/webbrowser/webbrowser_windows.go
The webbrowser code was moved to it's own package, but the windows fix pr was created from a point in time before that, so while the PR merged properly it didn't take the move into account.
> fix(client-go): fix webbrowser merge error

- contrib/aws/provision-aws-cluster.sh
If ssh auth fails for `deisctl` during AWS provisioning, the user sees a red warning followed by a green success message followed by another red warning, with little help on what actions to take.
This moves the success message last and suggests checking ssh-agent for the proper key.
Closes #4198.
Closes #4199.
> fix(contrib/aws): clarify proxy protocol error

- client-go/pkg/git/git.go
This matches the behavior of the python client, required to pass integration tests.
> fix(client-go): fall back on directory name if remote can't be detected

- client-go/cmd/auth.go
This could cause problem when registering with a fresh cluster before logging out of a old one. Registration doesn't care if the token is valid (it only cares when registration is set to admin only), but login requires no token or a valid token, so it has to be unset.
> fix(client-go): unset token before logging in

- contrib/coreos/user-data.example
The manage_etc_hosts cloud config was added so that instances with hostnames that did not resolve correctly could still use the graceful shutdown logic. I personally only observed this issue with vagrant.
This seems to cause issues on GCE though, and should probably be removed.
https://github.com/coreos/bugs/issues/425
> fix(contrib): remove manage_etc_hosts from example user-data

- docs/managing_deis/running-deis-without-ceph.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/deis/deis/4288)
> docs(managing_deis): remove a space from a bash substitution

- docs/installing_deis/baremetal.rst
- docs/installing_deis/openstack.rst
Saying that Deis runs on CoreOS 494.5.0 is a bit misleading,
because a lot of recent improvements require newer versions.
Additionally, we remove the reference for bare metal to
contrib/bare-metal since there are no scripts there.
> docs(installing_deis): clean up old references

- router/build.sh
- router/image/templates/nginx.conf
Replace the default status page with one that provides more details using the [nginx-module-vts](https://github.com/vozlt/nginx-module-vts) module.
By default `/status` returns html but is possible to get a json representation using the `/status/format/json` path
> feat(router): improve nginx status page

- docs/managing_deis/isolating-etcd.rst
This confused me at first since I have been using my own cloud-config for a while.
> docs(isolating-etcd): add link to user-data.example

- logspout/attacher.go
Fixes #3633 
This isn't guaranteed to be a magic bullet that solves every logging-related issue, but we have uncovered deadlock that can occur when logspout attempts attaching to containers.  At several points in this process, a lock on a mutex is acquired and released.  At one such point, after acquiring a lock, a message is written to an unbuffered channel.  Since writes to an unbuffered channel will block until another goroutine receives the message, and since sometimes there is no one listening, execution can block indefinitely at this point while holding on to the lock that other goroutines are waiting for.  Using a buffered channel seems to alleviate this issue.
Thanks to @aledbf and @technosophos for help in diagnosing the issue.
N.B.: Longer term, we might consider adopting a …
> fix(logspout): fix deadlock when attaching

- Makefile
- controller/Makefile
- docs/contributing/hacking.rst
- docs/contributing/testing.rst
Issue #4266 notes how boot2docker is now deprecated. This commit
changes documentation and Makefile notices to recommend using
Docker Toolbox and Docker Machine instead.
Closes #4266.
> chore(docs): use Docker Toolbox, not boot2docker

- controller/api/fixtures/test_sharing.json
- controller/api/tests/test_perm.py
- controller/api/views.py
- tests/perms_test.go
This allows finer grained control over permission checking, with the added side effect of allowing users to remove their own app access.
> fix(controller): don't check permissions with @permissions_classes

- docs/managing_deis/security_considerations.rst
reST requires 2 backticks, not 3
> chore(docs): Fixed rendering of a few code snippets

- contrib/coreos/user-data.example
- tests/fixtures/test-etcd/Dockerfile
https://github.com/coreos/etcd/releases/tag/v2.1.2
> chore(*): bump etcd to 2.1.2

- Godeps/Godeps.json
- docs/contributing/hacking.rst
- tests/Makefile
- tests/bin/setup-node.sh
Since some integration tests will fail with concurrent goroutines, this change also sets GOMAXPROCS=1 when running them. Big improvements to runtime GC should speed up our components somewhat.
Closes #4308.
Note that this will not automagically put Go 1.5 on all CI test boxen; we need to do that manually once we verify this doesn't break things. I've run it locally against vagrant using Go 1.5 without problems.
> chore(tests): use go 1.5 toolchain

- contrib/aws/gen-json.py
The `with` statement ensures that files will be always be closed, this also switches from the deprecated `file` to `open`.
Also use `yaml.safe_load` in favor of `yaml.load`, which can execute arbitrary code.
> style(contrib/aws): Ensure that files are closed and use yaml.safe_load

- docs/managing_deis/running-deis-without-ceph.rst
- logspout/logspout.go
- logspout/types.go
I'm using AWS' Elastic Load Balancer in front on my logstash server, however ELBs don't support UDP. So here's a quick fix to add TCP support.
> feat(logspout): support sending log via tcp

- docs/installing_deis/azure.rst
This is required to ensure that the nodes get a static IP address.  If a virtual network is not used, the nodes get a dynamic private IP address that can change when rebooted.  This causes problems with etcd.
From @mdolian.
Closes #4329.
> docs(azure): add vnet creation instructions

- logger/syslogd/syslogd.go
Our custom `deis-logspout` does some work to resolve "application name" and "pid" from the name of each container it's attached to and includes these in the log messages it sends to `deis-logger`.  If the container's name doesn't match the usual format expected for a deis application, then the app name is simply the name of the container and the pid is simply 1.
Where this fails is if a container name has an underscore in it-- and Docker containers, if not explicitly named, use generated names that _do_ container underscores.  In such a case, the app name component of the message coming _from_ `deis-logspout` will contain an underscore, but on the `deis-logspout` side, the message gets rejected because, per a regex, it doesn't appear to contain an app name.
This change updates that regex …
> fix(logger): allow underscores in container names

- docs/managing_deis/platform_monitoring.rst
NewRelic now reports individual docker container cpu and memory usage under the Docker tab of a server.
> fix(docs): update NewRelic section.

- builder/env/envvar.go
- builder/env/envvar_test.go
- builder/rootfs/etc/confd/conf.d/check-repos.toml
- builder/rootfs/etc/confd/templates/check-repos
- builder/routes.go
Per #4338, I have replaced the script and toml file that I overzealously
removed in an earlier builder revision.
closes #4338
> fix(builder): added back the check-repos script

- logspout/logspout.go
fixes #4271 
2015-08-26T23:32:15UTC wiggly-buttress[web.97nsr]: 2015/08/26 23:32:15 listening on 5000...
2015-08-26T23:37:34UTC deis[api]: sm scaled containers web=3
2015-08-26T23:37:48UTC wiggly-buttress[web.po4k7]: 2015/08/26 23:37:48 listening on 5000...
2015-08-26T23:37:49UTC wiggly-buttress[web.7wb4n]: 2015/08/26 23:37:49 listening on 5000...
container name of the application: k8s_wiggly-buttress-web.7ee905fa_wiggly-buttress-v2-web-97nsr_wiggly-buttress_a7ae5889-4c4a-11e5-b18a-06842b0bdcf9_bf8b9b46
> fix(logger): add unique id for each app name in logs

- client-go/deis.go
- client-go/deis_test.go
- client-go/parser/apps.go
- client-go/parser/auth.go
- client-go/parser/builds.go
- client-go/parser/certs.go
- client-go/parser/config.go
- client-go/parser/domains.go
- client-go/parser/git.go
- client-go/parser/keys.go
- client-go/parser/limits.go
- client-go/parser/perms.go
- client-go/parser/ps.go
- client-go/parser/releases.go
- client-go/parser/tags.go
- client-go/parser/users.go
- client-go/parser/utils.go
- client-go/parser/utils_test.go
Fixes #4357 
This change got fairly in depth because of the new matching that had to be done to separate invalid commands from arguments passed to `command:list`.
> fix(client-go): pass arguments when using root command to list

- router/Dockerfile
- router/cmd/boot/boot.go
Nginx cannot log to a device for some reason, so this will have to stay. Why this works for `nginx` and not for `deis/router` is a little odd  (perhaps something to do with back-grounding nginx?)
> fix(router): revert symlink to /dev/stdout

- client/deis.go
Also return 1 for consistency with the python `deis` CLI. Output is now the same:
```console
$ ./deis badcommand
Found no matching command, try 'deis help'
Usage: deis <command> [<args>...]
$ ./deis 
Usage: deis <command> [<args>...]
$ echo $?
1
```
Closes #4364.
> fix(client): print usage if no args were given

- .gitignore
- client/Makefile
I forgot to bring this machinery along with the go CLI migration in #4341.
> feat(client): add makeself installer

- swarm/Dockerfile
A minor update for Go 1.5 that should have been included with #4309. I tested this on vagrant.
[skip ci]
> chore(swarm): update to go 1.5

- client/Makefile
This updates the `install` target in the Go-based client's `Makefile` to fulfill the reasonable expectation a contributor may have that `make -C client/ build install` will actually install a `deis` binary.  It does so by copying the built binary to `$GOPATH/bin`.
> fix(client): fix make install

- deisctl/backend/fleet/journal.go
```console
$ deisctl journal store-volume
Unable to get journal for global unit deis-store-volume.service. Check on a host directly using journalctl.
$ deisctl journal controller
-- Logs begin at Fri 2015-08-28 16:59:47 UTC. --
Aug 28 17:17:36 deis-01 sh[3237]: > api:0017_auto__del_cluster__del_field_app_cluster
Aug 28 17:17:37 deis-01 sh[3237]: > api:0018_drop_field_release_image__chg_field_release_build
...
```
Closes #4361.
> fix(deisctl): error when journaling a global unit

- client/cmd/auth.go
- client/controller/client/http.go
- client/controller/client/http_test.go
- client/controller/client/utils.go
This changes the new CLI to display the raw response body and status code for HTTP 40x and 50x errors if JSON decoding fails. It also moves the HTTP status line first for any error displayed, to match the old python CLI.
> fix(client): show non-JSON HTTP errors

- logspout/logspout.go
During v1.10.0 testing, I have been observing issues with `deis-logspout`.  They are most easily replicable when scaling to many containers quickly.  (Using k8s as the scheduler helps.)
The issue seems to be deadlock and is observable when the Docker event stream normally visible in each `deis-logspout` instance's own logs grinds to a halt.  If this sounds familiar, it is different, but similar to the root cause of #3633 which was closed by #4291
After much observation and testing, I realized I was never able to reproduce this issue if I built the `deis-logspout` container myself.  A variable I eventually realized was in play was that I was building `deis-logspout` using Go 1.4, whilst the images used for release testing where built using Go 1.5.
@gabrtv and @mboersma pointed me in the …
> fix(logspout): set GOMAXPROCS=1

- database/bin/boot
When troubleshooting failed database recovery on Azure, it seems we are failing to pull the `/deis/database/initId` from etcd even when it is populated.  Upon closer inspection I noticed we are not passing in the list of etcd hosts to etcdctl.  This PR passes `-C $ETCD` which seems to resolve the issue.  This will require manual database failover testing.
Reminder: all of these boot scripts need to be rewritten in Go. :wink:
> fix(database): use ETCD host during database recovery detection

- database/bin/boot
I tested by hand and verified this fixes the syntax error introduced by #4402.
> fix(database): arrange etcdctl arguments properly

- tests/bin/setup-node.sh
This PR syncs up the versions of [vagrant](https://www.vagrantup.com/downloads.html) and [VirtualBox](https://www.virtualbox.org/wiki/Downloads) with those used on node2 and node4 currently.
[skip ci]
> chore(tests): update virtualbox and vagrant

- controller/api/permissions.py
Changes the error message from the generic "You do not have permission to perform this action" when registration is disabled.
```console
$ deisctl config controller get registrationMode
disabled
$ deis register http://deis.local3.deisapp.com --username=test2 --password=asdf1234 --email=just@testing.thanks
Registration failed: Error: 
detail: Registration is disabled
403 FORBIDDEN
```
Closes #4371.
> fix(controller): clarify error if registration is disabled

- database/bin/boot
- database/templates/reload
The previous check using `netstat` was not specific enough and could return 1 before postgres starts.
> fix(database): improve postgres ready checks

- client/cmd/apps.go
- client/controller/api/apps.go
- client/controller/models/apps/apps.go
- client/controller/models/apps/apps_test.go
- client/parser/apps.go
- controller/api/__init__.py
- controller/api/fixtures/tests.json
- controller/api/tests/test_app.py
- controller/api/tests/test_users.py
- controller/api/urls.py
- controller/api/views.py
- docs/reference/api-v1.7.rst
- docs/reference/index.rst
- tests/apps_test.go
- tests/utils/itutils.go
- version/version.go
This is really useful if a user needs to delete their account, but they have apps that their company depends on attached to it. A user can use `apps:transfer` to transfer ownership of the app before deleting their account.
> feat(controller): allow users to transfer app ownership.

- Makefile
Without this change:
```
registry
To use a local registry for Deis development:
/bin/bash: docker-machine: command not found
export DEV_REGISTRY=:5000
```
This change returns `dev-registry` to the old behavior:
```
registry
To use a local registry for Deis development:
export DEV_REGISTRY=:5000
```
This is useful on Linux where it's common to use docker natively.
> fix(Makefile): silence docker-machine warning when it isn't installed

- deisctl/cmd/cmd.go
Fixes default `Stdout` pointing to `os.Stderr` and vice versa
> fix(deisctl): default stdout and stderr are reversed

- client/cmd/apps.go
- client/cmd/apps_test.go
The client code behind `deis apps:logs` referenced the second element of a string array without checking its length. This could cause a panic in some cases when the log line wasn't similar to:
```
2015-09-10T16:38:41UTC zaftig-occupant[web.1]: 2015/09/10 16:38:41 listening on 5000...
```
Now such unexpected log lines will get a category of "unknown". Logs with embedded newlines may still look a bit odd on your screen, but at least they will print successfully now.
I broke out part of the code into a `printLogs` func to make it easier to write a regression test.
Closes #4420.
> fix(client): print logs that lack a category prefix

- docs/customizing_deis/router_settings.rst
- docs/managing_deis/security_considerations.rst
- router/cmd/boot/boot.go
- router/rootfs/etc/confd/conf.d/nginx.conf.toml
- router/rootfs/etc/confd/templates/nginx.conf
This is a new security feature for the router. This is useful if you run internal applications on Deis and want to restrict access to specific range of IPs.
> feat(Router): IP whitelisting for apps and controller

- controller/api/admin.py
[`Container.state`](https://github.com/deis/deis/blob/master/controller/api/models.py#L579) isn't a concrete model field therefore can't be used in an admin `list_filter`.  The desired functionality would have to be implemented via a custom `django.contrib.admin.SimpleListFilter`, but it's unclear to me how to efficiently query the scheduler for all containers in a given state.
Currently trying to browse to `/admin/` raises `ImproperlyConfigured` with the following error:
`'ContainerAdmin.list_filter[2]' refers to 'state' which does not refer to a Field.`
> fix(controller): state property can't be used in a list_filter in the Django web admin

- docs/_includes/_get-the-source.rst
- docs/installing_deis/quick-start.rst
I went through the Quick Start steps (AWS path) and because I hadn’t yet installed deisctl the provision script barfed. I noticed that the "install deisctl" is listed at the bottom of the Quick Start docs, suggesting that it's something you do after a successful Quick Start install. It makes more sense to instead make a deisctl install a sort of prereq step at the top of the Quick Start doc.
> docs(quickstart): added install deisctl step at top of quick start docs

- Makefile
- Vagrantfile
- contrib/aws/gen-json.py
- contrib/azure/azure-coreos-cluster
- contrib/coreos/user-data.example
- deisctl/units/deis-logspout.service
- deisctl/units/deis-publisher.service
- docs/managing_deis/isolating-etcd.rst
This refactors and hopefully simplifies the thorny cloud-config Deis has in user-data.example. It uses the native CoreOS flanneld.service and etcd2.service--currently v2.1.2, same as Deis v1.10--and minimizes the differences with a [stock CoreOS user-data](https://github.com/coreos/coreos-vagrant/blob/master/user-data.sample). Also removes `etcd` timing tweaks which seemed to be unneeded based on my testing for v1.10--see #4384.
Also moves Docker `--insecure-registry` config into a unit drop-in and removes the cruft from the graceful-shutdown script. I've tested this against vagrant with Deis v1.10, Deis master, and Deis v1.8 upgraded to v1.10 + this PR. Also tested k8s, v1.9.1 upgrade, and the graceful-shutdown.sh script.
Closes #4384.
Closes #4409.
> ref(user-data): use default etcd2 and flannel services

- deisctl/deisctl.go
Status command exists but is missing from the initial help screen
> fix(deisctl): add status command to help screen

- docs/installing_deis/aws.rst
Two reasons for this:
- More likely than not, a modern OS will have a separate ssh-add utility installed (and some, e.g., Mac OS X, does not have an "add" option as a a part of the installed ssh-agent binary.
- "ssh-add" is referenced in several other places in the docs, while "ssh-agent add" is only referenced in this one place. We should aim for consistency, and "ssh-add" seems to have momentum on its side.
> (docs)aws: replace "ssh-agent add" with "ssh-add"

- contrib/coreos/user-data.example
We need to mask etcd.service to prevent in from starting in place
of etcd2.service
closes #4490
I'd like @sgoings to test this on whatever provider he was seeing it on in #4490.
> fix(contrib/coreos): mask etcd.service

- contrib/aws/deis.template.json
- deisctl/units/deis-kube-proxy.service
- deisctl/units/deis-router.service
- router/Dockerfile
- router/rootfs/etc/confd/templates/nginx.conf
Fixes #4344 
This improves confd templates for the router's Nginx configuration such that if the k8s scheduler is in use, the _existing_ `/health-check` endpoint on the router's default virtual host is enhanced to proxy `deis-kube-proxy`'s own health check endpoint.
__tl;dr:__ I also added a second healthcheck endpoint specifically for use with AWS ELBs.
Since we use `proxy_protocol` when the routers are behind an AWS ELB and ELBs do not include proxy protocol headers when initiating a healthcheck request over HTTP ([a bug, IMO](https://forums.aws.amazon.com/message.jspa?messageID=633016)) we have historically resorted to simpler healthchecks that only assert something is listening on port 80.  That is inadequate to make use of the enhanced healthcheck endpoint.
To fix this, I wanted to …
> feat(router): improve healthcheck

- client/cmd/apps.go
```console
$ deis create
Creating Application... done, created madras-yachting
fatal: remote deis already exists.
To replace the existing git remote entry, run:
git remote rename deis deis.old && deis git:remote -a madras-yachting
Error: exit status 128
```
Closes #4455.
cc: @michelleN, let me know if this is what you had in mind.
> fix(client): suggest help when git remote creation fails

- contrib/openstack/provision-openstack-cluster.sh
This changes the way awk is used to separate fields so that it works on non-GNU awk.
This changes the field separator from '| ' to '|' and use gsub to strip whitespace.
The actual code, when used on OSX to provision deis on openstack result in the following error:
```
awk: illegal primary in regular expression |  at
input record number 1, file
source line number 1
```
The change was tested on OS X and CentOS 6. The risk of it breaking critical stuff is very low IMO.
(first PR so I've tried to follow the contribution guidelines to the best of my understanding. please let me know if there's anything that should be changed)
> Fix awk field separator not working on non-GNU awk

- docs/managing_deis/running-deis-without-ceph.rst
Adding a bash var for S3 region in the example code block under "configure registry". I think this will avoid future implementers from accidentally pasting in the sample "eu-west-1" s3region value into the "deisctl config registry" statement. It tripped up yours truly, at least!
> docs(running-deis-without-ceph): s3 region var

- controller/api/serializers.py
- controller/api/tests/test_config.py
Config keys are currently only validated in the `deis` client.  By using the REST API directly it's possible to write invalid config keys, potentially overwriting other keys in `etcd`.
> fix(controller): validate config keys at the api level

- contrib/aws/gen-json.py
The `urllib.urlopen(url)` call consistently hangs while `wget` and
`curl` succeed to the same URL for retrieving the AMIs. Tested use
of `urllib2` on Ubuntu Trusty (py 2.7.6) and CentOS 7 (py 2.7.5).
> fix(contrib): urlopen call hangs

- client/cmd/config.go
- tests/config_test.go
The client will now accept multi line configuration variables with `config:set`. Note: this will not work with `config:push` as it uses newlines as a config variable separator.
What now works is: 
```
config:set TEST="MULTI
LINE VAR"`
```
ref #4512
> fix(client): accept multi line config vars.

- docs/docs_requirements.txt
Missed a spot when #4341 was merged: these packages are no longer needed to build the Sphinx docs.
> ref(docs): remove old py client requirements

- docs/customizing_deis/registry_settings.rst
- docs/managing_deis/running-deis-without-ceph.rst
- registry/templates/config.yml
- registry/templates/create_bucket
As described in [AWS best practises](http://docs.aws.amazon.com/IAM/latest/UserGuide/IAMBestPractices.html#use-roles-with-ec2), application running on EC2 should not use hard coded Access Key and Secret Key and instead use  attached IAM roles to authenticate to Amazon web services. 
Here's some fixes I had to made for boto to connect using IAM roles. I've tried to be as backward compatible as possible but I did not test other workflows (help needed :pray:). 
I've also updated the *customizing deis -> registry settings* doc to include the keys that were added with the *Running Deis without Ceph* feature and the new `s3assumeRole` key.
> feat(Registry): add support for IAM role authentication

- contrib/aws/provision-aws-cluster.sh
- contrib/aws/stack_policy.json
- contrib/aws/update-aws-cluster.sh
Use Stack Policy to prevent updated AMIs from CoreOS causing instance replacements.
When running update-aws-cluster.sh and the CoreOS version has been bumped then a
running machines will be replaced due to CF default behaviour
The Stack Policy is automatically applied on create and update
> ref(aws): Ensure CloudFormation does not replace running instances on AMI changes.

- contrib/aws/check
- contrib/aws/provision-aws-cluster.sh
Fully utilise the power of aws cli query instead of piping various AWS commands into cut, head and other programs
> ref(aws): Improve AWS queries instead of piping output.

- tests/bin/test-latest.sh
Minor fix to put test binaries in the correct directories.  This doesn't actually affect anything since `deis` and `deisctl` are executed via `PATH`, which still correctly finds them.
> fix(tests): binaries are installed in the wrong directories

- controller/Makefile
- controller/api/models.py
- controller/api/tests/__init__.py
- controller/api/tests/test_app.py
- controller/api/tests/test_build.py
- controller/api/tests/test_config.py
- controller/api/tests/test_container.py
- controller/api/tests/test_hooks.py
- controller/api/tests/test_release.py
- controller/api/tests/test_scheduler.py
- controller/deis/settings.py
- controller/dev_requirements.txt
- controller/registry/__init__.py
- controller/registry/mock.py
- controller/templates/confd_settings.py
- docs/reference/server/registry.rst
While working on #3814 I ran into issues trying to use python's `mock` module in controller/registry unit tests. Turns out the local mock.py module there and associated hackery are not needed, so I PR'ed these changes separately.
Removes the REGISTRY_MODULE machinery, adds verbosity to `flake8` errors that are caught, and updates the python `coverage` library.
> ref(controller): remove REGISTRY_MODULE hack

- controller/bin/boot
- tests/bin/setup-node.sh
`brew install shellcheck` now produces version 0.4.1, which finds an additional error that needs to be ignored.
> chore(tests): update shellcheck to 0.4.1

- deisctl/client/client.go
These commands do not have any option flags, so this wil clear up
any confusion when a user expects the help command to display its
flags.
closes #4452
> fix(deisctl): remove unused options docstring

- contrib/azure/arm-template.json
- contrib/azure/parameters.json
- docs/installing_deis/azure.rst
I got this idea from @sgoings. Being able to toggle the version in `parameters.json` is a lot easier for users (and us when we bump the CoreOS version).
> ref(contrib/azure): specify CoreOS version as a parameter

- database/templates/create_bucket
- docs/managing_deis/running-deis-without-ceph.rst
- registry/templates/create_bucket
Use s3.lookup method to identify bucket name instead of list and expose all bucket names to deis cluster.
> ref(registry/database): change the create_bucket script to avoid allow 'ListAllMyBuckets' on S3 Policy

- builder/README.md
- builder/rootfs/Dockerfile
- controller/Dockerfile
- controller/README.md
- controller/requirements.txt
- controller/templates/gconf.py
- database/Dockerfile
- database/README.md
- deisctl/units/deis-builder.service
- deisctl/units/deis-database.service
- deisctl/units/deis-mesos-master.service
- deisctl/units/deis-store-daemon.service
- deisctl/units/deis-store-monitor.service
- deisctl/units/deis-zookeeper.service
- logger/README.md
- logger/image/Dockerfile
- logspout/image/Dockerfile
- mesos/zookeeper/Dockerfile
- publisher/image/Dockerfile
- router/Dockerfile
- router/README.md
- store/README.md
- swarm/image/Dockerfile
- tests/bin/prime-docker-images.sh
- tests/fixtures/mock-store/Dockerfile
- tests/fixtures/test-etcd/Dockerfile
Updates all components to the current [3.2.3 release](http://alpinelinux.org/posts/Alpine-3.2.3-released.html) in the official Docker [`alpine:3.2` image](https://hub.docker.com/_/alpine/), except the store-* components which use Ubuntu.
Includes openssl 1.0.2, a prerequisite for #4542. 
I spent quite a while trying, but the python `setproctitle` library just won't compile on alpine:3.2 due to expectations about the location of `sasl.h`. It was really a cosmetic nice-to-have (see #3094), so I removed it.
Registry uses M2Crypto for python, which just won't build with swig 3.0.5, so I left deis-registry at alpine:3.1. (It will likely be replaced by my v2 registry container soon anyway, which already uses alpine:3.2.)
> chore(*): update Docker base image to alpine:3.2

- docs/managing_deis/upgrading-deis.rst
Graceful upgrade in stateless mode has been fixed in #4506 and the option `--stateless` has been added to `upgrade-prep` and `upgrade-takeover` subcommands.
Update documentation for warning user to use this option.
> docs(upgrading-deis): graceful upgrade in stateless mode

- deisctl/units/deis-logspout.service
- deisctl/units/deis-publisher.service
- deisctl/units/deis-store-admin.service
- deisctl/units/deis-store-daemon.service
- deisctl/units/deis-store-gateway.service
- deisctl/units/deis-store-metadata.service
- deisctl/units/deis-store-monitor.service
Fixes #4584 by serializing `docker pull` among units pulling images with layers in common.  This is applied only to global units that are most likely to start in parallel as the result of a new node being added to a cluster.
Attn: @mboersma @carmstrong @gabrtv
> fix(*): use flock to serialize certain pulls

- controller/Makefile
- controller/web/tests.py
The minimal web pages in deis-controller are an optional feature that can't properly be removed from the code in a backward-compatible release, so they deserve to have their tests included again.
> fix(controller/web): enable unit tests

- docs/contributing/hacking.rst
I needed these before I could run `make -C router test`. It might help to document that for others.
> docs(contributing): add optional pre-reqs

- CONTRIBUTING.md
The instructions aren't in `README.md` they are in `hacking.rst`.
> docs(contributing): update where build instructions are

- contrib/coreos/user-data.example
Reverts this networking configuration to the interface it used previous to the v1.11.0 release, which was changed in 445dbaecfadb1e2690734413cc43f30abcb13b21.
Closes #4594.
Closes #4608.
> fix(user-data): use $private_ipv4 for fleet

- contrib/aws/stack_policy.json
This builds on #4534 to also prevent the replacement of the auto scaling group, which will also replace all of the EC2 instances in the ASG.
> ref(aws): prevent replacement of ASG in CF update

- contrib/aws/gen-json.py
Not needed anymore due to #4444 and moving away from containerized etc2
> ref(contrib/aws): remove disk replacements that were forgotten in #4444

- registry/bin/boot
I was confused by registry start because it was blocking on the store to become available. Last thing I saw was "registry running".
So I thought I'd add more information to the startup process to clear up any confusion.
After:
```
Sep 29 23:29:07 ... systemd[1]: Started deis-registry.
Sep 29 23:29:07 ... sh[30838]: registry: environment ETCD=10.21.2.206:4001 ETCD_PATH=/deis/registry HOST_ETCD_PATH=/deis/registry/hosts/10.21.2.206 ETCD_TTL=20 REGISTRY_PORT=5000 EXTERNAL_PORT=5000 BUCKET_NAME=registry
Sep 29 23:29:28 ... sh[30838]: registry: creating bucket
Sep 29 23:29:28 ... sh[30838]: registry: bucket created
Sep 29 23:29:28 ... sh[30838]: registry: starting registry
Sep 29 23:29:28 ... sh[30838]: registry: docker registry started in background with pid: 39
[...]
Sep 29 23:29:29 ... …
```
> feat(registry) add more information on during startup process

- builder/rootfs/bin/entry
deis-builder currently fails to start on CoreOS beta 835.0.0 and later with the error mentioned in  jpetazzo/dind#89:
`Oct 23 13:52:57 nodo-2 sh[1573]: ln: failed to create symbolic link ‘/sys/fs/cgroup/systemd/name=systemd’: Operation not permitted`
Updating the docker-in-docker wrapper script to [the current `docker:dind` version](https://raw.githubusercontent.com/docker/docker/master/hack/dind) fixes this. I've tested this on CoreOS beta (835) and alpha (845).
Closes #4655.
ping @aledbf.
> fix(builder): update d-in-d wrapper for newer Docker

- builder/rootfs/etc/confd/templates/builder
Add a `SOURCE_VERSION` environment variable to slub builds which represents the git commit SHA-1 of the source being built. 
Mirrors this Heroku feature: https://devcenter.heroku.com/changelog-items/630
Fixes issue #4491
> feat(builder): make SOURCE_VERSION env variable

- contrib/coreos/user-data.example
- contrib/util/custom-firewall.sh
CoreOS has included `/usr/bin/jq` v1.4 since [release 717.0.0](https://coreos.com/releases/#717.0.0). This removes some cruft from when it was necessary to install it to `/opt/bin/jq`.
> ref(contrib): assume jq utility is available

- builder/docker/docker.go
- builder/rootfs/Dockerfile
This should be the final change necessary to future-proof Deis against the [disabling of the V1 API](http://blog.docker.com/2015/10/docker-hub-deprecation-1-5/) at Docker Hub on December 7.
Now that #4581 is merged, `deis pull` does not depend on the extended V1 registry-to-registry transfer API and works with images built by any version of Docker. The "last-mile" layer of ENV variables is also done by Docker now and doesn't depend on the V1 registry API. Bumping Docker up to the current 1.8.3 in deis-builder should ensure that new or upgraded Deis clusters can survive December 7.
Docker registry V2 work for deis-registry is also close to completion, but needs a migration tool and further testing: see #4641.
Refs #4636.
TODO:
> chore(builder): update Docker to 1.8.3

- contrib/azure/create-azure-user-data
closes #4679 
Fix bug related to a null value discovery URL that was blocking deployment of Deis to Azure
> fix(contrib/azure)-replace discovery url

- contrib/azure/create-azure-user-data
- contrib/gce/create-gce-user-data
Replaces `#DISCOVERY_URL` explicitly to fix GCE provisioning. See #4680--thanks @ritazh!
Closes #4588.
> fix(contrib/gce): replace discovery url properly

- contrib/digitalocean/config.sh
- contrib/digitalocean/create
- contrib/digitalocean/destroy
- contrib/digitalocean/variables.tf
I'd like to get these changes in (rigger specific, no changes to terraform or docs) for the Digital Ocean deploy day. It makes the tutorial more dead-simple, as in the user is only asked for:
- DO_TOKEN
- ssh private key to use with Digital Ocean
```
~/go/src/github.com/deis/rigger  ⑂ master +    ./rigger configure --provider "digitalocean" --version 1.12.0
DEIS_SOURCE already set to 1. Skipping prompt.
VERSION already set to 1.12.0. Skipping prompt.
DEIS_GIT_REPO already set to https://github.com/deis/deis.git. Skipping prompt.
DEIS_GIT_VERSION already set to 1.12.0. Skipping prompt.
GOPATH already set to /Users/sethgoings/.rigger/d9915759a0/go. Skipping prompt.
DEIS_ROOT already set to /Users/sethgoings/.rigger/d9915759a0/go/src/github.com/deis/deis. Skipping prompt.
Cloning Deis at …
```
> feat(contrib/digitalocean): improve Digital Ocean provisioning workflow

- Vagrantfile
On Ubuntu (and possibly other Linux distros) backticks create a subshell
that's not bash (just regular old sh). This causes issues when loading
information from contrib/utils.sh.
Fixes #4691
> fix(Vagrantfile): specifically use bash to source utils.sh

- contrib/linode/linode-user-data-template.yaml
Disable DHCP and mark the connection as critical on Linode. This has completely removed the network drops I was experiencing.
> fix(contrib/linode): fix issues with DHCP on Linode

- docs/roadmap/schedule.rst
These bullet points have always been the unstated release criteria for Deis, so let's make them plain.
Closes #4426.
> docs(roadmap): add release criteria

- client/cmd/builds.go
This fixes an "invalid memory address" panic on Mac OS X that probably began with #4606. Thanks to @Joshua-Anderson for suggesting this change.
Closes #4698.
> fix(client): init procfileMap in "deis pull"

- builder/etcd/etcd.go
If deis-builder is unable to update etcd with its ssh server host and port, the `UpdateHostPort` task exits and the service must be restarted. Logging the error but continuing to try to update etcd should be more robust behavior. @rvadim has been running Deis with this patch for over a month and it seems to have helped in his situation.
Closes #4495.
ping @technosophos for builder review.
> fix(builder): continue updating etcd after errors

- router/rootfs/bin/build
- router/rootfs/etc/confd/templates/deis.conf
- router/rootfs/etc/confd/templates/nginx.conf
See http://nginx.org/en/CHANGES
spdy is gone is favor of http2 as of 1.9.5, but it's unclear to me if that would be a breaking change since Deis didn't advertise the availability of the `spdy` protocol. ping @helgi and @aledbf for review.
> chore(router): update nginx to 1.9.6

- database/templates/create_bucket
- registry/templates/create_bucket
There are small implications between `if not x` and `if x is None` in
Python:
- `if not x` checks if the value is false (empty list, `None`, `False`)
- `if x is None` checks if x is equal to the literal value `None`.
conn.lookup returns `None` if no bucket exists. This code is explicitly
stated in their docs as the proper way to check if a bucket does not
exist.
See: http://boto.readthedocs.org/en/latest/s3_tut.html
I'm not sure how the original issue is caused, but this will likely
resolve it.
closes #4713 
ping @lukasmartinelli and @afterthought. Would you mind verifying that this patch works for you?
> fix(create_bucket): check for existence of None

- docs/contributing/hacking.rst
The missing step can cause `make dev-registry` to fail further down in the doc.
> docs(hacking): add docs to show how to use the docker-machine env

- builder/git/git.go
Resolve #3458
Just handle situation when /home/git/app.git/ contains only cache and build dir.
> fix(buidler): Fix problem with missed git repos after builder restart

- registry/templates/create_bucket
The create_bucket script in the registry has some incompatibilities with
s3. In 1.12 deis is using the boto `lookup` function to determine
whether a bucket exists or not.  The boto s3 connection is created using
an OrdinaryCallingFormat, for ceph compatibility.  Unfortunately, S3
returns a 301 when lookup is called with OrdinaryCallingFormat, which
causes the lookup function to return None.
Prior to 1.12 the boto `get_all_buckets` function was used to determine
whether a bucket existed or not, which does not seem to have this
problem.
I've fixed it by updating the create_bucket script to not pass an
OrdinaryCallingFormat if the `/deis/registry/s3bucket` setting is
present, which fixes this issue.  I've also omitted the
`is_secure=False` setting, which would cause boto to use s3 over http. …
> fix(registry): fix create_bucket s3 compatability

- contrib/utils.sh
- docs/roadmap/releases.rst
Without this COREOS_VERSION and COREOS_CHANNEL aren't picked up by sourcing or external scripts
> ref(contrib): expose COREOS ENV vars via export in utils.sh. Add DEIS_RELEASE

- deisctl/config/config.go
- deisctl/config/config_test.go
> fix(deisctl): don't panic when config key/value is malformed

- MAINTAINERS.md
This steals the language for contributing maintainers from the Helm
project. We have many contributing maintainers who aren't enumerated
here.
> chore(MAINTAINERS): don't enumerate maintainers

- contrib/coreos/user-data.example
This clears up a race condition where docker can be socket-activated _before_ flannel has finished starting-- in which case docker appears to assign VIPs to containers that are in the 10.1.0.0/16 range instead of the 10.244.0.0/16 range that flannel manages iptables rules for.
The issue essentially breaks the k8s tech preview.  It manifests as 502s from the router when attempting to access an app.  The router sees the upstream as a bad gateway.  What is really happening is that the router is proxying traffic to the application's service endpoint (which is a VIP in an entirely different range with iptables rules managed by kube-proxy), and the traffic gets there no problem, but then cannot reach any pod that the service proxies because all the pods are in the 10.1.0.0/16 range and are not …
> fix(contrib): Add drop-in to make docker require flannel

- contrib/coreos/user-data.example
This is no longer necessary with the introduction of
`etcdctl cluster-health` in etcd 2.
> chore(contrib/coreos): remove debug-etcd service

- router/rootfs/etc/confd/templates/nginx.conf
using k8s scheduler apps with names which share a common prefix, e.g.
myapp, myapp1, myapp2, failed to get published to the router component.
This fix enforces dir etcd listing of discovered apps. Without the fix,
when apps share a common prefix, multiple non existent entries are
returned causing confd failures.
> fix(router): fix router common prefix app publishing

- database/templates/WALE_S3_ENDPOINT
I use deis in stateless mode, in fact, in semi-stateless mode. It is not documented.
Here the situation:
- Standard stateless deployment
- Added a deis-database.service manually and necessary keys:
```
etcdctl set /deis/store/gateway/accessKey "key"
etcdctl set /deis/store/gateway/secretKey "secret"
etcdctl set /deis/store/gateway/host s3-eu-west-1.amazonaws.com
etcdctl set /deis/store/gateway/port 80
```
This working perfectly! Better than using RDS which is slower and really too expensive!
---
Everything worked properly in `v1.11.1` but not with latest version `v1.12.1`.
**Explanation:**
- Keys `/deis/store/gateway/*` are shared between `database` and `registry` component.
- https://github.com/deis/deis/commit/89027a8e725a5c5197230905708c2e1caaf433f0#diff-800e0a4a3663e2bebfb83d42572b310f …
> feat(database): supports HTTPs as S3 endpoint

- controller/scheduler/fleet.py
Legacy tag based placement now gets messed up unless we enable placement options on the platform. I don't believe this was supposed to be a breaking change.
> Enable placement options should not effect legacy tag placement.

- docs/customizing_deis/registry_settings.rst
- registry/templates/create_bucket
OrdinaryCallingFormat is important for any bucket with dot in it, no matter the region. Fixes bug introduced by #4729
> fix(registry): disallow dots in s3 buckets

- contrib/azure/parameters.json
- contrib/linode/provision-linode-cluster.py
- contrib/utils.sh
- docs/installing_deis/baremetal.rst
- docs/installing_deis/gce.rst
Various bug fixes and an OpenSSL security fix.
See: https://coreos.com/releases/#835.9.0
> chore(*): bump to CoreOS 835.9.0

- tests/fixtures/mock-store/Dockerfile
- tests/fixtures/mock-store/build.sh
- tests/fixtures/mock-store/mock-s3-patch.diff
This removes the download and application of a gisted diff during building of the mock-store test fixture.  Downloading this file has long resulted in intermittent 503s, and as of recently, have broken the build consistently because the diff no longer applies.
Even if this passes CI, we should still circle back to verify it does not affect #3128
> fix(tests): use and patch known "good" version of mock-s3

- tests/bin/test-integration-aws.sh
- tests/bin/test-integration.sh
Since we're now using the golang client, printing that we were running the integration tests with the python client is wrong. :smiley:
> fix(tests): remove reference to python client

- docs/customizing_deis/router_settings.rst
- router/rootfs/etc/confd/templates/nginx.conf
This change makes the size in the `vhost_traffic_status_zone` directive
configurable. See also https://github.com/deis/deis/issues/4828.
> feat(router) make vhost_traffic_status_zone configurable

- contrib/linode/linode-user-data-template.yaml
In order to allow for "separating of the planes", and to keep up with `/contrib/coreos`, I added the proper metadata tags to `/contrib/linode`.
Without this addition, when you set `deisctl config platform set enablePlacementOptions=true`, you will be unable to perform the deis platform installation because none of the deis components will be able to be placed.
> Add metadata to linode cloud init template.

- contrib/aws/provision-aws-cluster.sh
This makes it easier to change the number of attempts by changing `ATTEMPTS=60`.
I ran into this because my provisioning seems to take longer than 10 minutes.
> aws: refactor magic sleep constants

- contrib/linode/apply-firewall.py
- contrib/linode/create-linode-user-data.py
- contrib/linode/linodeapi.py
- contrib/linode/linodeutils.py
- contrib/linode/provision-linode-cluster.py
- docs/installing_deis/linode.rst
1. I added the option to open ports 2379 and 2380 during cluster expansion. This is useful due to [the new nodes being added as proxies within etcd when using a public discovery URL that has reached it's size limit](https://coreos.com/etcd/docs/latest/clustering.html#public-etcd-discovery-service).
2. I standardized and normalized the python functions used during CoreOS provisioning (i.e. Linode API calls and logging).
3. I added multiple methods of providing IPs when applying a firewall to the cluster. Namely, IPs can now be provided via a Linode display-group, manually, or using the discovery URL. This is useful particularly when running this command outside of the CoreOS cluster, but also when adding nodes to an existing cluster because (as noted above) the new nodes will be added as …
> feat(contrib/linode): allow for cluster expansion and standardize scripts

- database/bin/boot
This change separates the command responsible for getting a list of backups from the `wc -l` it is piped in to. This way, when the wal-e command fails, script pipefail is triggered and the boot script exits, as it should.
fixes #4748
> fix(database): bail out if unable to check for existing backups

- contrib/coreos/user-data.example
- docs/managing_deis/add_remove_host.rst
This introduces the ability to handle the shutdown and cleanup of a nodes etcd member when the node is not running the Deis store components. Right now, if a node isnt a normal control plane node, the process cant happen.
It does so by making use of separate units for etcd and ceph graceful shutdown. This is because the systemd units need to ``Require`` different units - the Ceph stuff requires all the store stuff and needs to order itself after it while the etcd unit does not.
In the future, when this no longer experimental, we could remove the need for manual start up and enabling of the units by having etcd and/or the store units ``Want`` these units - therefore starting them they activate.
Another change is that these units make use of ``RefuseManualStop``, which should make it …
> feat(contrib): graceful shutdown for non-ceph nodes 

- controller/scheduler/fleet.py
When trying to modify the unit_tags, the following error occurs:
`TypeError: dict_items object does not support item assignment`.
This is because it is a view and not a dict. You have to modify
the dict directly in order for this to work.
> fix(controller): legacy fix should modify dict instead of dict view

- router/rootfs/etc/confd/templates/deis.conf
- router/rootfs/etc/confd/templates/nginx.conf
Fixes #4869 
When PROXY protocol is not in use, this change will attempt to get the end client's IP form the `X-Forwarded-For` HTTP header.  If that header doesn't exist, perhaps because there is no load balancer or proxy in play, as in the case of Vagrant, for instance, there is no harm.
I have confirmed that this fixes #4869 and allows the use of whitelists _without_ PROXY protocol.  This is extremely useful to anyone terminating SSL at the load balancer.
This change should be ported forward to the Deis v2 router.
__EDIT:__ Also, this PR fixes some additional bugs and redundancies relating to PROXY protocol and/or the `X-Forwarded-For` header and the proper determination and use of the real end-client IP.
For instance, in the file `deis.conf`, the strategy used for determining whether …
> fix(router): Fix issues establishing real end-client IP

- logspout/logspout.go
- tests/apps_test.go
> fix(logspout): Truncate lines too big for a single UDP packet

- docs/managing_deis/running-deis-without-ceph.rst
The registry will fail to template the config if /deis/store/gateway
is not set. This workaround works for users running Deis v1 without
Ceph.
closes #4568
> docs(managing_deis): add workaround for cephless cluster

- controller/api/tests/test_users.py
- controller/api/urls.py
Documentation includes sample code for listing all users using API. It
shows `GET /v1/users` endpoint which did not work. API required a slash
character at the end of URL:
```bash
$ curl -I -H "Authorization: token ..." -H "Content-Type: application/json" https://...co/v1/users
HTTP/1.1 404 NOT FOUND
Server: nginx/1.9.6
Date: Wed, 03 Feb 2016 10:55:02 GMT
Content-Type: text/html
Connection: keep-alive
Vary: Accept-Encoding
X_DEIS_API_VERSION: 1.7
DEIS_PLATFORM_VERSION: 1.12.1
X_DEIS_PLATFORM_VERSION: 1.12.1
DEIS_API_VERSION: 1.7
$ curl -I -H "Authorization: token ..." -H "Content-Type: application/json" https://....co/v1/users/
HTTP/1.1 200 OK
Server: nginx/1.9.6
Date: Wed, 03 Feb 2016 10:55:39 GMT
Content-Type: application/json
Connection: keep-alive
Vary: Accept-Encoding …
```
> fix(controller): do not require slash at the end of the `GET /v1/users`

- client/deis.go
- client/parser/version.go
This feature flips docopt-go's version parsing logic switch off
in favour of our own in-house version parsing lib. This has the
following side-benefits, all of which are valid commands:
- `deis -v`
- `deis version`
- `deis help version`
fixes #4674 
TODO:
> feat(client): document deis version

- contrib/azure/parameters.json
- contrib/linode/provision-linode-cluster.py
- contrib/utils.sh
- docs/installing_deis/baremetal.rst
- docs/installing_deis/gce.rst
Fixes a high severity OpenSSL vulnerability: https://coreos.com/releases/#835.12.0
> chore(*): bump CoreOS to 835.12.0

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
Updates all eligible buildpacks to their latest tagged versions. ~~Needs to be tested with all Deis example apps on Deis v1~~ I tested with all Deis example apps on Deis v1:
See also deis/slugbuilder#23.
> chore(buildpacks): update all Heroku buildpacks

- contrib/azure/parameters.json
- contrib/linode/provision-linode-cluster.py
- contrib/utils.sh
- docs/installing_deis/baremetal.rst
- docs/installing_deis/gce.rst
Patches the glibc CVEs: https://coreos.com/releases/#835.13.0
> chore(*): bump CoreOS to 835.13.0

- client/pkg/git/git.go
Backported fix from deis/workflow#425.
> fix(client): strip controller port when parsing git remotes

- docs/reference/terms/build.rst
You can now push to any branch, which will trigger a build.
closes #4870
> docs(reference): remove sidenote about pushing only to master

- builder/sshd/server.go
It's okay for connections to probe the server without initiating
a handshake, but it's still useful for developers to see when incoming
connections are not connecting.
closes #4431
> fix(builder): demote handshake failure log to debug

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
Adds Go 1.6 support.
See https://github.com/heroku/heroku-buildpack-go/compare/v30...v31
> chore(buildpacks): update heroku-buildpack-go to v31

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
Adds SBT 0.13.11 support.
See https://github.com/heroku/heroku-buildpack-scala/compare/v65...v66
> chore(buildpacks): update heroku-buildpack-scala to v66

- Vagrantfile
This change allows Vagrant to work properly when the path to the
location of the clone of this repo contain spaces. For example, if this
repo were cloned to this path:
```
/users/userA/path with spaces/code/deis
```
`vagrant up` would fail. This change fixes that.
> fix(vagrant): fix Vagrantfile to handle spaces

- contrib/README.md
docs(contrib): add link to deis-phppgadmin
Add deis-phppgadmin (An addon for deis-databas) to contrib/README.md (custom components)
[deis-phppgadmin](https://github.com/HeheCloud/deis-phppgadmin) by [hehecloud](https://github.com/HeheCloud) - An addon for deis-database (phpPgAdmin)
> docs(contrib): add link to deis-phppgadmin

- client/cmd/apps.go
Go's net/url package returns malformed urls when a port is specified to `url.Parse()`.
For example, given "kiddie-armchair.192.168.64.2.xip.io:31258", `deis open` would call this `AppOpen` func and open a browser to "http:31258". The code appears to intend just to ensure a URL scheme prefix, so string manipulation should be adequate.
See deis/workflow#426.
> fix(client): simplify URL prefixing

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
This is the same as the previous SHA 26fa21a, but tidier.
> chore(buildpacks): update heroku-buildpack-multi to v1.0.0

- builder/rootfs/bin/boot
- builder/rootfs/bin/entry
This exports the proxy environment variables, which should make
child processes like the docker daemon to have its proxy information
set up.
closes #4494 
ping @benbarclay and @rcreasey if you could please test this and verify, that would be most appreciated. Unfortunately I do not have a proxy network set up over here so I cannot manually verify this fix with a local Deis cluster.
> fix(builder): source proxy envvars

- router/rootfs/etc/confd/templates/nginx.conf
Fixes #4997
This will _also_ have the actual protocol used trump whatever the `X-Forwarded-Proto` header says about whether the request is a secure one or not.
> fix(router): Allow for comma-delimited X-Forwarded-Proto

- tests/bin/setup-node.sh
[skip ci]
The tests/bin/setup-node.sh script is called from ansible, but won't currently run on a new EC2 node since it tries to downgrade the docker-engine without a `--force-yes` flag. I've run this script by hand on a new CI node and it fixes things up, but it needs to be committed to master before ansible will see it.
cc: @vdice @sgoings
> fix(setup-node.sh): update packages for a Jenkins node

- controller/api/models.py
- controller/api/tests/test_certificate.py
since #4762 isn't likely to be added to the LTS release due to some changes still required, this PR disables users from adding wildcard certificates by accident.
closes #4685
> fix(api): disable adding wildcard certificates

- controller/registry/dockerclient.py
- controller/registry/tests.py
This fixes an issue with Docker's build system.
The following does not work:
```
><> cat Dockerfile
FROM busybox
ENV POWERED_BY='can\'t compute'
><> docker build .
Sending build context to Docker daemon 109.6 kB
Error response from daemon: Syntax error - can't find = in "compute'". Must be of the form: name=value
```
However, subbing the single quotes for double quotes works:
```
><> vim Dockerfile
><> docker build .
Sending build context to Docker daemon 109.6 kB
Step 1 : FROM busybox
---> 307ac631f1b5
Step 2 : ENV POWERED_BY "can\"t compute"
---> Using cache
---> 7b505fc9ce12
Successfully built 7b505fc9ce12
><> docker run 7b505fc9ce12 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=c4d9a9278acd
POWERED_BY=can"t compute
HOME=/root
```
fixes #4796
> fix(controller): use double quotes to escape ENV values

- client/cmd/apps.go
- controller/api/tests/test_app.py
- controller/api/views.py
- docs/reference/api-v1.7.rst
Django Rest Framework will wrap the string with quotes because
of the JSONRenderer. Django's HttpResponse class handles the
application logs as we expect it to; unmolested and untouched.
This scrubs the "No logs for appname" message we would display when
there are no logs to show, but in reality this is the correct way to
return a 204, and that message was never displayed to users because
we inject "user created initial release" when a user first runs
`deis apps:create`. Django scrubs the response content if the
status code is a 204 to comply with RFC 2616, section 4.3.
See https://github.com/django/django/blob/53ccffdb8c8e47a4d4304df453d8c79a9be295ab/django/http/utils.py#L13-L16
fixes #4657
fixes #4658
> fix(controller): use django HttpResponse for logs

- builder/etcd/etcd.go
- builder/rootfs/Dockerfile
- controller/Dockerfile
- controller/build.sh
- database/build.sh
- logger/image/Dockerfile
- logspout/image/Dockerfile
- publisher/image/Dockerfile
- registry/Dockerfile
- registry/build.sh
- router/Dockerfile
- router/rootfs/bin/build
- tests/fixtures/mock-store/Dockerfile
- tests/fixtures/mock-store/build.sh
- tests/fixtures/test-etcd/Dockerfile
Updates Docker base images to `alpine:3.3` to benefit from current code and fixes.
Closes #4904.
TODO:
> chore(*): update base to alpine:3.3

- controller/api/tests/test_config.py
- controller/api/views.py
- controller/requirements.txt
Uses a file lock to ensure that multiple gunicorn processes can be coordinated in the container. If a `deis config:set` is in progress, another client attempting `config:set` will try to obtain the lock for 5 seconds, then return an error:
```
$ deis config:set POWERED_BY=Second
Creating config... Error: 
409 CONFLICT
error: Config changes already in progress.
[Errno 11] Resource temporarily unavailable
```
Closes #4746.
Closes #4758.
> fix(controller): prevent overlapping config:set operations

- controller/requirements.txt
The Mesos / Marathon tech preview scheduler was removed from Deis after the 1.12 release, in #4861.
> chore(requirements): remove obsolete marathon lib

- controller/build.sh
Controller doesn't require the django-fsm fork any longer. Not since [this change](https://github.com/deis/deis/pull/2993/files#diff-521da416471aa0210eb6bb14d746c5abL7) in #2993.
> chore(build.sh): remove unused git install

- logspout/logspout.go
Logspout would only discover the logger's host/port information at
boot. When the logger is rebooted and is re-scheduled onto another
host, the logspout agents were not updated. This change makes the
agent check etcd every 10 seconds and updates the logger route
information to ensure it's sending logs to the right address.
fixes #4293
> fix(logspout): discover logger connection continuously

- client/controller/client/http.go
This PR improves the resultant client error message they get when the returned response is
incorrect. This is especially important for determining the error message
Old message when using a v1 client with a v2 cluster:
```
http://deis.10.245.1.3.xip.io does not appear to be a valid Deis controller. Make sure that the
Controller URI is correct and the server is running.
```
New message:
```
http://deis.10.245.1.3.xip.io/v1/ does not appear to be a valid Deis controller. Make sure that the
Controller URI is correct and the server is running.
```
Notice the appended /v1/ path, which users can assume this is a v1 client.
> ref(client): improve client error message

- publisher/server/publisher.go
I've noticed that my apps could take a very long time before getting published to the router. After investigation, I found that it was caused by the cumulation of all the HEALTHCHECK_INITIAL_DELAY.
For exemple, let's say all my apps have an initial delay of 1 minute. If I have 100 apps, it will take 1 minute to publish the first one, 2 minutes for the second, and so on. The last one will be published only after 100 minutes.
This PR fixes the issue
> imp(publisher): concurrent polling

- tests/fixtures/test-etcd/Dockerfile
This matches the version shipped in CoreOS 899.15.0.
> chore(tests): update test-etcd to v2.2.3

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
See https://github.com/heroku/heroku-buildpack-python/compare/v78...v80
I tested this with [example-python-flask](https://github.com/deis/example-python-flask) and [example-python-django](https://github.com/deis/example-python-django) on Vagrant with 1.13.1+.
> chore(buildpacks): update heroku-buildpack-python to v80

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
See https://github.com/heroku/heroku-buildpack-php/compare/v102...v105
I tested this with [example-python-php](https://github.com/deis/example-python-php) on Vagrant with 1.13.1+.
> chore(buildpacks): update heroku-buildpack-php to v105

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
See https://github.com/heroku/heroku-buildpack-scala/compare/v67...v70
I tested this with [example-python-scala](https://github.com/deis/example-python-scala) on Vagrant with 1.13.1+.
> chore(buildpacks): update heroku-buildpack-scala to v70

- controller/api/models.py
Should result in a single large SQL `DELETE` statement rather than many small ones in a loop.
> ref(models): optimize container delete statement

- docs/managing_deis/upgrading-deis.rst
I've clarified the AWS notes to highlight that updating proxy protocol support will only be necessary when upgrading from Deis versions that are older than v1.6.
I've also changed the ELB health check note to recommend to not change it—your instances will simply return anyway, you just need to wait. I'm not sure if this is the best way to go, but I've tried *changing health checks from HTTP to TCP* (as noted in the current documentation), but I wasn't sure what port to set it to; I tried setting it to port 80 and it marked my instances as `OutOfService` anyway.
Also see #5035.
> docs(upgrading): clarify AWS-specific instructions

- contrib/azure/parameters.json
- contrib/linode/provision-linode-cluster.py
- contrib/utils.sh
- docs/installing_deis/gce.rst
This reverts commit 0d6475f60207cfcd41349782d411b3b22f371403 from #5042. Note that it leaves e8bcd6f4cf43d4afceff98f6bd526c10f5fc974f intact however, since that is a backward-compatible fix that allows the controller to run on CoreOS 1010.5.0: future-proofing seems prudent since users will likely provision from newer versions regardless.
As discussed in #5042, issue coreos/bugs#1301 is likely to crop up when using Deis v1. That issue is now fixed by coreos/coreos-overlay#2006 but may not appear in the CoreOS stable channel for a while.
So after reverting this, we can create a 1.13.2 release, and later create a 1.13.3 updating to a current CoreOS when the fix is available.
> Revert "chore(*): bump CoreOS to 1010.5.0"

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
See 
https://github.com/heroku/heroku-buildpack-go/compare/v41...v42
https://github.com/heroku/heroku-buildpack-php/compare/v107...v108
https://github.com/heroku/heroku-buildpack-nodejs/compare/v90...v91
https://github.com/heroku/heroku-buildpack-python/compare/v80...v81
https://github.com/heroku/heroku-buildpack-scala/compare/v70...v71
> chore(buildpacks): update go, php, nodejs, python, and scala buildpacks

- contrib/util/reset-ps-all-apps.sh
This is usefull after a reinstall of a cluster with stateless storage.
When the new cluster is started it will still remember the requested
scale of all applications, but all containers will be in "destroyed"
state.
This means that a `deis ps:restart` does not work and so manual
rescaling needs to be done.
This is a tedious and error-prone task if you have many applications,
so this little script takes care of that.
> feat(contrib): Add script to restart all apps.

- builder/Makefile
- controller/Makefile
- database/Makefile
- logger/Makefile
- logspout/Makefile
- publisher/Makefile
- registry/Makefile
- router/Makefile
- store/Makefile
Removes the `-f` flag from `docker tag` commands,  since it is an error as of Docker v1.12.
See also deis/controller#827 (for example).
> ref(Makefiles): remove obsolete "docker tag -f" flag

- controller/Dockerfile
- controller/build.sh
- logger/image/Dockerfile
- logspout/image/Dockerfile
- publisher/image/Dockerfile
- registry/Dockerfile
- router/Dockerfile
- tests/fixtures/mock-store/Dockerfile
- tests/fixtures/mock-store/build.sh
- tests/fixtures/test-etcd/Dockerfile
Updates Docker base images to `alpine:3.4` to benefit from current code and fixes.
Leaves database intact, since upgrading to a new version of postgresql isn't a smooth upgrade path.
Mea culpa: I'm having problems with Go builds locally so I'm tossing this to Jenkins so I can test with the images it builds.
> chore(*): update base to alpine:3.4

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
See https://github.com/heroku/heroku-buildpack-go/compare/v42...v44
and https://github.com/heroku/heroku-buildpack-scala/compare/v71...v72
and https://github.com/heroku/heroku-buildpack-php/compare/v108...v109
> chore(buildpacks): update go, scala, and php buildpacks

- database/build.sh
> fix(database/build.sh): refer to stable pv package location

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
See https://github.com/heroku/heroku-buildpack-go/compare/v44...v46 and deis/slugbuilder#101.
> chore(buildpacks): update heroku-buildpack-go to v46

- client/controller/client/client.go
Settings files contain auth tokens and should not be world-readable.
Backport of https://github.com/deis/workflow-cli/pull/251
> fix(perms): user-only settings file permissions

- client/deis.go
- client/deis_test.go
We have a private PaaS with multiple Deis clusters (staging + two productions at the moment). We have also a tool that allows us to manage all clusters from a single web panel. It also connects other APIs such as servers provider and DNS provider. As the result we can perform actions that touches many parts of the system (for example create DNS records for all Deis workers and make CNAME to use with `DEISCTL_TUNNEL` or create a database and assign `DATABASE_URL` for a given application). We have also created plugins to extend Deis CLI. For example there is a support for database (+backups) management and easy SSH access for our developers.
We have `deis backups:[create|show|restore|list]` commands and we want to show usage help if user tries `deis backups`. There is a problem in such case …
> fix(client): do not add top level command to cmdArgs

- docs/theme/deis/layout.html
Previously this was a link to the doc source. A Container
Days conference attendee just pointed out that it would
be more convenient to be linked to the published docs
instead. I think he's right.
> docs(layout): Update notice with URL for published v2 docs

- builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks
See https://github.com/heroku/heroku-buildpack-go/compare/v46...v54
and https://github.com/heroku/heroku-buildpack-php/compare/v109...v117
and https://github.com/heroku/heroku-buildpack-python/compare/v81...v97
and https://github.com/heroku/heroku-buildpack-ruby/compare/v146...v150
and https://github.com/heroku/heroku-buildpack-nodejs/compare/v91...v93
Brings things close to parity with current [deis/slugbuilder](https://github.com/deis/slugbuilder/blob/c40c6a04b3c6a62b27ad739b9e7f25c23aa2380a/rootfs/builder/install-buildpacks).
> chore(buildpacks): update several buildpacks
