deis/deis

controller/README.md

chore(controller): Fix typo on README.md

---

contrib/ec2/gen-json.py

coreos-cloudinit processes units as they are listed in the cloud-config
file, so even though `prepare-etcd-data-directory.service` asks to be
started before etcd with `Before=etcd.service`, etcd has already
been started by the time this unit is encountered.
This commit prepends the Docker volume and etcd data volme preparation
to the main unit list, so they are started before etcd/fleet.
TESTING: Provision an EC2 cluster. You should notice that
`/media/ephemeral/etcd` has `log` and `conf` files, as well as a
`snapshots` directory. The lack of a snapshots directory is what
resulted in a panic when etcd tried to write a snapshot to disk.

fix(contrib/ec2): prepare etcd before starting etcd

---

builder/image/Dockerfile
builder/image/slugbuilder/Dockerfile
builder/image/slugrunner/Dockerfile
cache/Dockerfile
controller/Dockerfile
database/Dockerfile
docs/contributing/releases.rst
logger/image/Dockerfile
logspout/image/Dockerfile
publisher/image/Dockerfile
registry/Dockerfile
router/image/Dockerfile
store/base/Dockerfile

feat(docker): add env DEIS_RELEASE

---

controller/requirements.txt
docs/docs_requirements.txt

See https://www.djangoproject.com/weblog/2015/jan/13/security/

chore(controller): update Django to 1.6.10 security release

---

controller/scheduler/fleet.py

This PR fixes #2655 by monitoring for errors during container creation and container start.  While normal error cases (i.e. `exit 1`) were being caught and handled properly, in the case of #2655 the binary we were executing did not exist.  This caused the container to fail at create-time, which caused hangs during state polling.

fix(controller): track create and start separately to catch early errors

---

controller/requirements.txt
docs/docs_requirements.txt

Many months of changes, see https://github.com/paramiko/paramiko/compare/v1.14.1...v1.15.2

chore(controller): update paramiko to 1.15.2

---

client/Makefile
client/setup.py
controller/dev_requirements.txt
docs/docs_requirements.txt
tests/bin/build-deis-cli.sh

See https://github.com/dateutil/dateutil/compare/e49a25913...2.4.0

chore(client): update python-dateutil to 2.4.0

---

controller/requirements.txt
docs/docs_requirements.txt

See https://github.com/lukaszb/django-guardian/compare/v1.2.4...v1.2.5

chore(controller): update django-guardian to 1.2.5

---

database/templates/postgresql.conf

For context, please refer to https://github.com/deis/deis/issues/2923

fix(database): increases max_connections to 250

---

controller/api/tests/test_app.py
controller/api/tests/test_container.py
controller/api/views.py

closes #2858 
rebased off of #2898 since those are the main blockers for this change.

fix(controller): return 403 when a user does not have permission

---

client/deis.py

fix(client): check for expected destroy response

---

controller/api/__init__.py
controller/api/tests/test_app.py
controller/api/tests/test_auth.py
controller/api/tests/test_container.py
controller/api/tests/test_release.py
controller/api/tests/test_scheduler.py
controller/api/views.py
controller/scheduler/chaos.py
docs/reference/api-v1.1.rst

fix(controller): return proper json messages on error

---

client/deis.py

Resolves #1499. Addresses the issue when a user may not be using a proper 
certificate in their deis environment. This change allows the user to disable SSL
verification via a command line option during auth:login. The result is saved in the
user's client.json and is passed in subsequent commands made via the
client.

feat(client): add flag to disable SSL certificate verification

---

controller/api/models.py
controller/api/tests/test_key.py

fix(controller): validate key material on upload

---

docs/managing_deis/add_remove_host.rst
docs/managing_deis/index.rst
docs/managing_deis/recovering-ceph-quorum.rst
docs/troubleshooting_deis/index.rst
docs/troubleshooting_deis/troubleshooting-store.rst

Note that PR also includes the doc change from #2951.
closes #2926

docs(*): add Ceph quorum documentation

---

builder/bin/publish-release-controller.go

refs https://github.com/deis/deis/issues/2960#issuecomment-71518301

fix(builder): correctly handle error on request timeout

---

builder/image/slugbuilder/builder/install-buildpacks

bump heroku-buildpack-php to v57

---

docs/installing_deis/aws.rst

Add a section to the installing_deis/aws page describing the
behavior of the update_ec2_cluster script including the parameters
that can be changed without replacing the resources in the
CloudFormation stack and a link to the pertinent AWS documentation.

docs(ec2): Document update_ec2_cluster.sh

---

controller/requirements.txt
docs/docs_requirements.txt

See https://github.com/tomchristie/django-rest-framework/compare/3.0.3...3.0.4

chore(controller): update djangorestframework to 3.0.4

---

Vagrantfile

There were a few minor changes in our upstream [`Vagrantfile`](https://github.com/coreos/coreos-vagrant/blob/master/Vagrantfile); this minimizes the diff between the two.

chore(Vagrantfile): sync with changes in coreos-vagrant

---

router/image/templates/nginx.conf

Improve monitoring of the deis cluster
* Added stub_status
* More stats in the log
* request_time
* upstream_response_time

feat(router) nginx status; log http_host, upstream and request times

---

controller/api/serializers.py
controller/api/tests/test_domain.py

fix(controller): improve domain name validation per RFC 1123

---

builder/image/templates/builder
tests/config_test.go

fix(builder): properly escape backticks

---

builder/Makefile
logger/Makefile
logspout/Makefile

chore(builder, logger, logspout): remove unused references to BUILD_IMAGE

---

docs/installing_deis/baremetal.rst
docs/managing_deis/disk_usage.rst
docs/managing_deis/index.rst

closes #2559 
refs #1678 
refs #2886

docs(*): add disk usage docs

---

controller/requirements.txt
docs/docs_requirements.txt

See http://docs.gunicorn.org/en/19.2.1/news.html#id1

chore(controller): update gunicorn to 19.2.1

---

client/Makefile
controller/dev_requirements.txt

See https://gitlab.com/pycqa/flake8/blob/master/CHANGES.rst

chore(client+controller): update flake8 code checker to 2.3.0

---

.gitignore
contrib/azure/README.md
contrib/azure/azure-coreos-cluster
contrib/azure/azure-user-data-template
contrib/azure/cert.conf
contrib/azure/create-azure-user-data
contrib/azure/generate-mgmt-cert.sh
docs/installing_deis/azure.rst
docs/installing_deis/index.rst

~~Note that to test this, a custom builder component will need to be used until #2891 is merged and baked into images pushed to Docker Hub.~~
replaces #2824
closes #802 
refs #2891

feat(contrib): add Microsoft Azure provision scripts and documentation

---

controller/scheduler/fleet.py

We can't reliably guess how long this will take.
closes #3054

fix(controller): remove timeout on container launch

---

controller/requirements.txt

See http://initd.org/psycopg/articles/2015/02/09/psycopg-26-and-255-released/

chore(controller): update PostgreSQL driver to 2.6

---

client/deis.py

This makes it easier to transfer configs from one app to another.
See: #3016 for reference.

feat(deis/config): remove "===" when listing configs with --oneline

---

controller/build.sh

The deis user does not need sudo

chore(controller): No sudo for deis

---

controller/requirements.txt
docs/docs_requirements.txt

See http://www.django-rest-framework.org/topics/release-notes/

chore(controller): update djangorestframework to 3.0.5

---

contrib/ec2/deis.template.json
contrib/ec2/gen-json.py
docs/installing_deis/aws.rst

feat(contrib/ec2): add support for internal ELBs

---

registry/build.sh

chore(registry): bump docker-registry

---

docs/customizing_deis/router_settings.rst
docs/managing_deis/ssl-endpoints.rst
router/image/templates/nginx.conf

feat(router): add optional HTTPs redirect

---

controller/build.sh
database/build.sh
registry/build.sh
tests/bin/setup-node.sh
tests/fixtures/mock-store/build.sh

See https://github.com/pypa/pip/releases/tag/6.0.8

chore(*): update pip installer tool to 6.0.8

---

deisctl/Makefile
deisctl/backend/fleet/destroy.go
deisctl/backend/fleet/start.go
deisctl/backend/fleet/stop.go
deisctl/backend/fleet/unit.go
deisctl/backend/fleet/utils.go
deisctl/backend/fleet/utils_test.go
deisctl/cmd/cmd.go
deisctl/cmd/cmd_test.go
deisctl/utils/utils.go
registry/Makefile
router/Makefile
store/Makefile

Start all installed units using `deisctl start router@*`. This works for start, stop and restart.
Fixes https://github.com/deis/deis/issues/2995

feat(deisctl): start / stop all installed units

---

contrib/README.md

docs(contrib): link to community projects

---

controller/scheduler/fleet.py

If a controller task times out during `deis run`, the cleanup code to destroy its fleet unit isn't called. This wraps the important code in a try/finally to ensure the unit is destroyed even when the code doesn't follow the happy path.
I tested by first setting the [worker timeout](https://github.com/deis/deis/blob/master/controller/deis/gconf.py#L4) to 20, then running `deis run sleep 30`, waiting until it fails and then looking at the output of `fleetctl list-units`. Before this change, a deis run unit was orphaned each time; after the change, the unit is removed.
In conjunction with #3084 (merged), closes #3022.

fix(controller): ensure cleanup of "deis run" fleet units

---

deisctl/backend/fleet/journal.go
deisctl/backend/fleet/status.go

Fixes https://github.com/deis/deis/issues/2917

fix(deisctl) : deisctl Journal and status custom error message for global units

---

builder/Makefile
cache/Makefile
contrib/bumpver/Makefile
deisctl/Makefile
logger/Makefile
logspout/Makefile
publisher/Makefile
router/Dockerfile

fix(go): go 1.4 static binaries

---

controller/scheduler/fleet.py

Aiming for Heroku parity, closes #3086

feat(scheduler): graceful shutdown with SIGTERM

---

builder/bin/get-app-values.go
builder/image/templates/builder
builder/utils.go
builder/utils_test.go

for real this time!
closes #3078

fix(builder): properly escape backticks in envvars

---

builder/image/slugbuilder/builder/build.sh
docs/using_deis/using-buildpacks.rst
tests/config_test.go
tests/utils/itutils.go

closes #3042
also fixes an issue in master when BUILDPACK_URL is present: #3078

lock buildpack url to revision

---

docs/managing_deis/backing_up_data.rst

This wasn't addressed as part of #2993 - see https://github.com/deis/deis/pull/2993#issuecomment-76298399

docs(managing_deis): remove scale note on backup/restore

---

docs/using_deis/install-client.rst

docs(using_deis): clarify proxy for Vagrant

---

docs/reference/api-v1.0.rst
docs/reference/api-v1.1.rst

docs(reference): email is a mandatory parameter

---

docs/managing_deis/platform_monitoring.rst

fixes #3221 - service file surviving hard resets

---

controller/api/serializers.py
controller/api/tests/test_domain.py

fixes #3270 
pinging @mboersma -- do you know if I should be checking that `domain1` is still considered invalid, or is this now a valid domain?

fix(controller): allow labels with trailing numbers

---

controller/requirements.txt
docs/docs_requirements.txt

See http://docs.gunicorn.org/en/19.3/news.html#id1

chore(controller): update gunicorn to 19.3.0

---

client/Makefile
client/setup.py
controller/dev_requirements.txt
docs/docs_requirements.txt
tests/bin/build-deis-cli.sh

See https://github.com/dateutil/dateutil/releases/tag/2.4.1

chore(client): update python-dateutil to 2.4.1

---

client/deis.py

feat(client): add discrete git:remote command

---

controller/api/models.py

When logging events to the application, it does not need to know
which app it came from... That information is redundant. Also, the
developer does not need to know the internal UUIDs of the builds, config
and releases being created, as the relevant information will be in the
release summary.
From one of the unit tests:
```
$ cat logs/actual-frosting.log
2015-03-04T18:37:54UTC deis[api]: autotest created initial release
2015-03-04T18:37:54UTC deis[api]: autotest added POWERED_BY
2015-03-04T18:37:54UTC deis[api]: autotest changed POWERED_BY
2015-03-04T18:37:54UTC deis[api]: autotest added INTEGER
$ cat logs/hungry-macaroni.log
2015-03-04T18:37:59UTC deis[api]: autotest created initial release
2015-03-04T18:37:59UTC deis[api]: autotest deployed qwerty
```
`qwerty` in this case is an …

fix(controller): do not log to app in log_event

---

docs/customizing_deis/router_settings.rst
router/image/templates/nginx.conf

fix(router): allow customization of connection limits

---

builder/Makefile
cache/Makefile
includes.mk
logger/Makefile
logspout/Makefile
publisher/Makefile
router/Makefile

Check to avoid problems like https://github.com/deis/deis/pull/3133

feat(makefile): check that generated go binaries are statically linked

---

publisher/server/publisher.go

The reason of `/deis/publisher/containers/<id container> -> <app name>/<app type instance>` is required because in the docker stop event only the id of the stopped container is available.
closes #3176

feat(publisher): remove application when is stopped

---

router/image/templates/nginx.conf

for more see http://wiki.nginx.org/Pitfalls#Taxing_Rewrites

feat(router): avoid regex-based taxing rewrites

---

client/deis.py

I've just copied and pasted from deis login command.

feat(deis client): add ssl-verify parameter to deis register command

---

docs/installing_deis/gce.rst

Move to `us-central1-c` [Haswell zone](https://cloud.google.com/compute/docs/zones#available) as `us-central1-a` will be announced as
deprecated soon and increase disk size to 256GB ($30 USD/month) since
32GB does not provide sufficient IOPS for ceph.
continuation of #3252, #3123

feat(docs): gcutil is deprecated; convert all calls to gcloud compute

---

tests/bin/setup-node.sh

And remove wget progress output

feat(setup-node.sh): remove user intervention setting up new nodes

---

router/image/templates/nginx.conf

style(router): include naxsi rules only once

---

controller/api/tests/test_domain.py
controller/api/views.py

fix(controller): retrieve requested domain from .get_object

---

builder/image/Dockerfile
builder/image/bin/boot
builder/image/slugbuilder/builder/install-buildpacks

chore(builder): bump heroku-buildpack-ruby to v134

---

contrib/coreos/user-data.example
docs/managing_deis/index.rst
docs/managing_deis/production_deployments.rst

Also adds a new documentation section for production-ready recommendations.

feat(contrib/coreos): add preseed script for Deis components

---

contrib/azure/azure-coreos-cluster

replaces #3104 
Skipping Jenkins, as we won't test this.

fix(contrib/azure): fix virtual network name

---

controller/deis/settings.py
controller/requirements.txt
controller/scheduler/fleet.py
deisctl/units/deis-controller.service
docs/docs_requirements.txt

This change requires docker 1.5.0
closes #3205

feat(controller): disable swap usage if there is a memory limit

---

tests/config_test.go
tests/utils/itutils.go

test(tests/config_test.go): add DEIS_APP and DEIS_RELEASE tests

---

client/deis.py

fix(client): read response from DELETE /v1/auth/cancel

---

controller/dev_requirements.txt
docs/docs_requirements.txt

See https://github.com/sphinx-doc/sphinx/compare/1.3...1.3.1

chore(docs): update Sphinx to 1.3.1

---

client/Makefile
controller/dev_requirements.txt

See https://gitlab.com/pycqa/flake8/blob/2.4.0/CHANGES.rst

chore(client+controller): update flake8 to 2.4.0

---

controller/build.sh
controller/deis/settings.py
controller/requirements.txt
controller/templates/confd_settings.py
docs/customizing_deis/controller_settings.rst
docs/docs_requirements.txt
docs/using_deis/register-user.rst
tests/bin/setup-node.sh

This is the Pull Request for the Proposal that we discussed at #3135 using the [PoC in the gist](https://gist.github.com/phspagiari/76165b35bae1b8e5a891).
I didn't write any test because I imagine that it's not good have specific tests for auth with ldap, so my opinion is that if the actual auth tests pass its good enough.
If sounds good I will make a doc with the README content and create another PR.

feat(controller): Adding LDAP/AD auth support

---

docs/installing_deis/install-deisctl.rst

docs(installing): revise deisctl install to use sudo on CoreOS

---

builder/image/bin/boot
controller/bin/boot
database/bin/boot
registry/bin/boot
store/admin/bin/boot
store/gateway/bin/boot

feat(*): use confd --watch

---

contrib/coreos/user-data.example

there was a iteration bug .. it just preseeded the builder

fix(contrib): preseed all images

---

tests/bin/test-integration-ec2.sh

This change [modifies `cloudformation.json`](http://docs.deis.io/en/latest/installing_deis/aws/#customize-cloudformation-json) temporarily to use `m3.medium` instances during integration tests. If it works reliably, we can reduce our EC2 charges for [CI](https://ci.deis.io/). :moneybag: 
Deis still recommends (and defaults to) `m3.large` instances on EC2.

feat(tests): use m3.medium instances for ec2 integration tests

---

publisher/server/publisher.go

fix(publisher): use TTL in services application etcd directories

---

tests/bin/test-integration-ec2.sh
tests/bin/test-setup.sh
tests/integration_test.go

Builds on #3367, thanks again @a-saad. See http://docs.deis.io/en/latest/using_deis/install-client/#multiple-profile-support
Closes #3332.

fix(tests): allow concurrent client tests with DEIS_PROFILE

---

builder/image/slugbuilder/builder/build.sh
client/deis.py
docs/using_deis/using-buildpacks.rst

Just reopened because a merge mess.
Ref: #3259

feat(builder): add ssh key variable to support private repositories

---

contrib/rackspace/provision-rackspace-cluster.sh

See https://coreos.com/docs/running-coreos/cloud-providers/rackspace/

chore(contrib): update Rackspace to CoreOS 607.0.0

---

docs/installing_deis/aws.rst
docs/installing_deis/index.rst

Also cleans up language in "Installing Deis" index doc to mention 3 machines as the minimum, not 1.

fix(docs): update example output from provision-ec2-cluster.sh

---

docs/faq.rst

docs(faq): summarize difference between deis and deisctl clients

---

client/deis.py

This sends a request to `\v1` and sees if it returns as a 401 and has the same api version before starting the registration request.
I chose to check the url `\v1` because it is the top level api and it returns a `401`, which is more rare than a `200` and therefore is less likely to be matched by accident. If you guys want to use another url to check I'm open to that.
Closes #3224.

feat(client): check controller before attempting to register. Fixes #3224

---

contrib/azure/azure-coreos-cluster

Adds a load balanced https endpoint on creation

feat(contrib/azure/azure-coreos-cluster): add an https enddpoint on c… …reation

---

client/deis.py
controller/api/__init__.py
controller/api/tests/__init__.py
controller/api/tests/test_users.py
controller/api/urls.py
controller/api/views.py
docs/reference/api-v1.3.rst
docs/reference/index.rst
tests/Makefile
tests/users_test.go

Fixes #2006 
Once this api gets the OK, I will implement it.

feat(controller): add users:list endpoint

---

docs/managing_deis/add_remove_host.rst
docs/troubleshooting_deis/troubleshooting-store.rst
store/base/build.sh

See http://ceph.com/docs/master/release-notes/

chore(store): bump Ceph to "hammer" release

---

controller/api/models.py

deis domains:remove was removing all domains instead of single one

fix(controller) : remove domain

---

builder/image/Dockerfile
builder/image/bin/boot
builder/image/bin/check
builder/image/conf.d/authorized_keys.toml
builder/image/conf.d/builder.toml
builder/image/conf.d/check-repos.toml
builder/image/conf.d/gitreceive.toml
builder/image/conf.d/push-images.toml
builder/image/conf.d/receiver.toml
controller/Dockerfile
controller/bin/boot
database/Dockerfile
database/bin/boot
registry/Dockerfile
registry/bin/boot
store/admin/bin/boot
store/base/build.sh
store/daemon/bin/boot
store/gateway/bin/boot
store/metadata/bin/boot
store/monitor/bin/boot

I've also cleaned up some of the flags like `--interval` which is only used when `--watch` is not present.
closes #3436

chore(*): bump confd to v0.9.0

---

controller/api/serializers.py
controller/api/tests/__init__.py
controller/api/tests/test_limits.py
tests/limits_test.go

fixes https://github.com/deis/deis/issues/3354
make  deis client regex compatible to docker memory limits

fix(controller) : fix regex for deis limits

---

contrib/ec2/provision-ec2-cluster.sh

add checks to provision script to make sure the stack is either in the creating or created state.  otherwise, error out and show all resources that failed
Closes #3481

bug(contrib): check for cloudfront errors on stack creation

---

builder/image/bin/boot
controller/bin/boot
database/bin/boot
registry/bin/boot
store/admin/bin/boot
store/gateway/bin/boot

*edit - carmstrong*
See the discussion in #3505 for why this was necessary. 
closes #3505
closes #3501 
*/edit*

fix(*): use "confd --interval 5" instead of "--watch"

---

contrib/README.md

Adds a link to the F# "Hello World" app for Deis written by @haf.
Closes #3288.

feat(contrib): list Melano, an example F#/Suave app for Deis

---

router/build.sh

Changes: http://nginx.org/en/CHANGES-1.8

chore(router): update nginx to 1.8

---

docs/customizing_deis/router_settings.rst
router/build.sh
router/image/templates/nginx.conf

http://nginx.org/en/docs/stream/ngx_stream_core_module.html

feat(router): nginx 1.9.0. Remove third party tcp module

---

client/deis.py
controller/api/models.py
controller/api/tests/test_container.py
controller/api/tests/test_scheduler.py
controller/api/urls.py
controller/api/views.py
controller/scheduler/fleet.py
controller/scheduler/mock.py
controller/scheduler/states.py
docs/reference/api-v1.3.rst
tests/ps_test.go

feat(controller): add ps:restart command

---

router/image/templates/nginx.conf
tests/apps_test.go

fix(router): return 404 for non-existing app

---

deisctl/units/deis-publisher.service
publisher/README.md
publisher/main.go
publisher/server/publisher.go
publisher/server/publisher_test.go

This PR implements the first point as per [3577#issuecomment-97982351](https://github.com/deis/deis/pull/3577#issuecomment-97982351)
closes #3552

feat(publisher): expose config as flags

---

contrib/ec2/provision-ec2-cluster.sh
contrib/ec2/update-ec2-cluster.sh

feat(contrib): AWS cli profile param

---

docs/customizing_deis/controller_settings.rst
docs/managing_deis/operational_tasks.rst

docs(customizing_deis): clarify usage of registrationMode

---

controller/api/models.py

fix(controller): force uniqueness for default app name.

---

client/deis.py

fix(deis): validate the syntax of the environment file

---

docs/using_deis/process-types.rst

Noticed a minor typo in the process types docs.

s/deis push/deis pull/

---

contrib/ec2/deis.template.json
docs/installing_deis/aws.rst

feat(contrib/ec2): add support for custom volume sizes

---

deisctl/cmd/cmd.go

fix(deisctl): include swarm in refresh-units command

---

client/deis.py
controller/api/models.py
controller/api/serializers.py
controller/api/tests/test_app.py
controller/api/tests/test_auth.py
controller/api/tests/test_build.py
controller/api/tests/test_config.py
controller/api/tests/test_domain.py
controller/api/tests/test_scheduler.py
controller/api/views.py
controller/registry/private.py
controller/scheduler/fleet.py
controller/scheduler/swarm.py

This change prefers Python 2.7 [dict views](https://docs.python.org/2/library/stdtypes.html#dictionary-view-objects), [`xrange`](https://docs.python.org/2/library/functions.html#xrange) to `range`, and iterating over dicts directly without calling [`keys()`](https://docs.python.org/2/library/stdtypes.html#dict.keys). These idioms avoid unnecessary copying and are generally more efficient.

More efficient iteration

---

controller/api/middleware.py

Adds docstrings as recommended by `pylint`.

ref(controller): add docstrings to middleware module

---

cache/main.go
logger/main.go
router/boot.go
swarm/swarm.go

fix(*): suppress "Key already exists" errors

---

logger/drain/drain.go
logger/main.go
logger/syslogd/syslogd.go

fixes #3657
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/deis/deis/3660)

fix(logger): avoid hitting etcd for each log line

---

tests/bin/test-integration-ec2.sh
tests/bin/test-setup.sh

feat(tests): keep test instances with SKIP_CLEANUP=true

---

tests/config_test.go

Uses a map of deis example app name to buildpack url for the custom buildpack test, and skips it if `DEIS_TEST_APP` doesn't have a map entry.
```console
$ DEIS_TEST_APP=example-ruby-sinatra ./tests/bin/test-integration.sh
>>> Preparing test environment <<<
...
config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-ruby#e99ccea --app=configsample
Creating config... done, v3
=== configsample
BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-ruby#e99ccea
POWERED_BY: the Deis team
ok
git push deis master
Warning: Permanently added '[deis.local3.deisapp.com]:2222,[172.17.8.101]:2222' (RSA) to the list of known hosts.
-----> Fetching custom buildpack        
-----> Ruby app detected        
-----> Compiling Ruby/Rack        
-----> Using Ruby version: ruby-1.9.3 …
```

fix(tests): test custom buildpacks for example Procfile apps

---

docs/roadmap/planning.rst

from a comment made by @carmstrong in slack

docs(roadmap): link to maintainers.md

---

deisctl/Makefile
deisctl/backend/fleet/list_units.go
deisctl/backend/fleet/utils_test.go
deisctl/cmd/cmd.go
deisctl/units/units.go

fix(deisctl): hide random "deis-" services from "deisctl list"

---

client/deis.py

ref(client): clarify usage of ps:restart

---

client/deis.py
controller/api/fixtures/test_auth.json
controller/api/tests/test_auth.py
controller/api/views.py
docs/reference/api-v1.4.rst

feat(client): add --username flag to auth:passwd

---

controller/api/models.py
controller/api/tests/test_app.py
controller/deis/settings.py
controller/templates/confd_settings.py
docs/customizing_deis/controller_settings.rst
docs/using_deis/register-user.rst
router/image/templates/nginx.conf

feat(router): allow customizing controller subdomain

---

docs/managing_deis/backing_up_data.rst

docs(managing_deis): update backup/restore docs

---

docs/managing_deis/upgrading-deis.rst

docs(managing_deis): Add notes on persisting CoreOS upgrades

---

client/deis.py

fix(client): require the tag for builds:create

---

client/deis.py

Fixes issue #3764. Dont throw IOError when pipe closes.

---

router/image/templates/nginx.conf

Sorry this was so slow.
closes #3508

fix(router): avoid consistently hashing on empty string

---

MAINTAINERS.md

docs(MAINTAINERS): add Matt Butcher as a core maintainer

---

builder/rootfs/Dockerfile
controller/Dockerfile
database/Dockerfile
registry/Dockerfile
store/base/build.sh
tests/fixtures/mock-store/build.sh

See https://github.com/coreos/etcdctl/compare/v0.4.6...v0.4.9

chore(*): update etcdctl to v0.4.9

---

logger/main.go

refs #3790 
Part 1 of 2. We've seen watch thrash the etcd cluster which could explain why we're seeing a lot of `501: All the given peers are not reachable` during stress tests.

fix(logger): poll etcd rather than use etcd watch

---

docs/roadmap/planning.rst
docs/roadmap/roadmap.rst

This updates the open roadmap based on the items from the June open roadmap planning meeting.

docs(roadmap): update roadmap

---

router/README.md

small change so the markdown table is correctly rendered by github

fix(router): fix markdown table rendering

---

deisctl/cmd/cmd.go

closes #3793 
related technosophos/deis#1
```
$ ./deisctl stop swarm
● ▴ ■
■ ● ▴ Stopping Swarm...
▴ ■ ●
swarm nodes and swarm manager
could not find unit: deis-swarm-node.service
could not find unit: deis-swarm-manager.service
Done.
```

fix(deisctl): avoid blocking if output is empty

---

docs/contributing/hacking.rst
docs/installing_deis/aws.rst

As I went through the process of configuring my workstation, I updated
the documentation accordingly.
**Note:** This pull request supersedes #3787.

docs(hacking, aws): Update to latest installation process.

---

docs/roadmap/releases.rst

Some minor changes since last patch release that are worthy of noting.

docs(roadmap): update release checklist

---

Vagrantfile
contrib/azure/azure-coreos-cluster
contrib/ec2/deis.template.json
contrib/rackspace/provision-rackspace-cluster.sh
docs/installing_deis/baremetal.rst
docs/installing_deis/gce.rst

See https://coreos.com/releases/#681.0.0

chore(*): bump CoreOS to 681.0.0

---

controller/build.sh
database/build.sh
registry/build.sh
tests/bin/setup-node.sh
tests/fixtures/mock-store/build.sh

See https://github.com/pypa/pip/blob/develop/CHANGES.txt

chore(*): update python installer tool pip to 7.0.3

---

logger/main.go

fix(logger): adjust publish and ttl times to seconds

---

tests/bin/test-integration-ec2.sh

Attempts to push three times. I hope that is enough :scream_cat: 
Fixes #3845

feat(tests): retry push to dockerhub

---

router/build.sh
router/image/templates/nginx.conf

http://nginx.com/blog/socket-sharding-nginx-release-1-9-1/

feat(router): use new reuseport option

---

builder/rootfs/Dockerfile
builder/rootfs/bin/boot

fix(builder): generate key on boot

---

controller/requirements.txt

Just bug fixes, see http://pythonhosted.org/psycopg2/news.html#what-s-new-in-psycopg-2-6-1

chore(controller): update psycopg2 to 2.6.1

---

client/Makefile
controller/dev_requirements.txt

See https://gitlab.com/pycqa/flake8/blob/master/CHANGES.rst

chore(client+controller): update flake8 to 2.4.1

---

docs/installing_deis/aws.rst
docs/installing_deis/azure.rst
docs/installing_deis/openstack.rst
docs/installing_deis/rackspace.rst
docs/installing_deis/system-requirements.rst

docs(installing_deis): etcd doesn't require an odd # of nodes

---

Vagrantfile
contrib/azure/azure-coreos-cluster
contrib/ec2/deis.template.json
contrib/rackspace/provision-rackspace-cluster.sh
docs/installing_deis/baremetal.rst
docs/installing_deis/gce.rst

See https://coreos.com/releases/#681.1.0 and https://coreos.com/releases/#681.2.0

chore(*): bump CoreOS to 681.2.0

---

docs/installing_deis/digitalocean.rst

DO now has support for SFO1 and FRA1, so this updates the docs accordingly.

docs(installing_deis): update DO supported regions

---

docs/understanding_deis/components.rst

fix(docs): Correct and clarify description of builder component

---

database/build.sh

See https://github.com/wal-e/wal-e/compare/c6dd4b1...v0.8.1

chore(database): update wal-e to 0.8.1

---

docs/customizing_deis/router_settings.rst
docs/managing_deis/ssl-endpoints.rst
docs/managing_deis/upgrading-deis.rst

Closes #3829, #3863.
ping @crigor @johanneswuerbach @jwaldrip @jeff-lee

docs(router+upgrading): clarify EC2 PROXY protocol use

---

controller/scheduler/fleet.py

This is an attempt to fix #3913. It's difficult to reproduce, so this is based on Googling similar issues, reading the paramiko source code, and some guesswork.

fix(controller): test that RC is available before accesing it

---

docs/reference/api-v1.5.rst

Run returns a dynamic array :anguished:, not a json object as documented.

docs(reference): Fix response of /v1/apps/<app id>/run endpoint

---

Makefile
contrib/util/commit-msg
docs/contributing/standards.rst

This is a script that automatically checks to see if your commits fit the deis commit style.

docs(contributing): add commit-message hook

---

client/README.rst
client/setup.py
docs/managing_deis/configure-dns.rst

We added Linode support. I updated the lists so they are the same
everywhere.

chore(*): update lists of supported providers

---

client-go/controller/client/auth.go
client-go/controller/client/auth_test.go
client-go/controller/client/client.go
client-go/controller/client/client_test.go
client-go/controller/client/utils.go
client-go/controller/client/utils_test.go
client-go/parser/apps.go
client-go/parser/auth.go
client-go/parser/keys.go
client-go/parser/users.go

I missed some statements when I fixed this in the original PR.

style(client-go): make if statements to adhere to go style guide

---

swarm/README.md

docs(swarm): add a basic README.md

---

deisctl/backend/backend.go
deisctl/backend/fleet/create.go
deisctl/backend/fleet/create_test.go
deisctl/backend/fleet/destroy.go
deisctl/backend/fleet/destroy_test.go
deisctl/backend/fleet/fleet_test.go
deisctl/backend/fleet/list_unit_files_test.go
deisctl/backend/fleet/list_units_test.go
deisctl/backend/fleet/scale.go
deisctl/backend/fleet/scale_test.go
deisctl/backend/fleet/ssh_test.go
deisctl/backend/fleet/start.go
deisctl/backend/fleet/start_test.go
deisctl/backend/fleet/status.go
deisctl/backend/fleet/status_test.go
deisctl/backend/fleet/stop.go
deisctl/backend/fleet/stop_test.go
deisctl/backend/fleet/unit_test.go
deisctl/backend/fleet/utils_test.go
deisctl/cmd/cmd.go
deisctl/cmd/cmd_test.go
deisctl/cmd/platform.go
deisctl/cmd/swarm.go
deisctl/deisctl.go
deisctl/utils/utils.go

Fixes issue #3971 
deisctl used channels to send output and errors to a goroutine which
then wrote them. This patch replaces that with simpler code that simply
writes messages to Stdout and Stderr (configurable for outher writers).

fix(deisctl): Switch from channels to io.Writers.

---

deisctl/cmd/mesos.go

The mesos start/stop/install code needed to change from using channels to io.Writers in order to compile.
Tested manually with `make -C deisctl/ build && deisctl install|start|etc mesos`.
Refs #4025.

fix(deisctl): update mesos code to use io.Writer

---

controller/api/serializers.py
controller/api/tests/test_config.py

config.cpu will always be a integer
config.memory, config.values, and config.tags will always be
a string
Previously the controller would take and save any type,
provided it passed validation. This was problematic because
it could lead to mixed or unexpected types.
Examples:
This config would be valid:
```
{
"values": {
"TEST1": true,
"TEST2": 123,
"TEST3": "test"
}
}
```
You could get a response like this:
```
{
"cpu": {
"web": 1024,
"worker": "512"
}
}
```
Fixes #4070

fix(controller): convert config to correct types

---

client-go/cmd/limits.go
client-go/deis.go
client-go/parser/limits.go

feat(client-go): add limits endpoint

---

contrib/aws/deis.template.json
contrib/aws/gen-json.py
contrib/aws/provision-aws-cluster.sh
contrib/aws/update-aws-cluster.sh
contrib/utils.sh

replaces #4032 
Thanks @fabiob!

feat(contrib/ec2): allow easier selection of CoreOS version

---

.gitignore
router/Makefile

godeps walks up the directory tree to find a Godeps folder.

feat(router): don't copy Godeps, godeps can find it automatically.

---

deisctl/backend/fleet/fleet_test.go
deisctl/backend/fleet/scale.go
deisctl/backend/fleet/ssh.go
deisctl/backend/fleet/status.go
deisctl/client/client.go
deisctl/cmd/cmd.go
deisctl/cmd/cmd_test.go
deisctl/config/config.go

ref(deisctl): replace if/else trees with switch

---

client-go/cmd/certs.go
client-go/controller/api/certs.go
client-go/controller/models/certs/certs.go
client-go/controller/models/certs/certs_test.go
client-go/deis.go
client-go/parser/certs.go

After this PR, client-go will be feature complete. \o/

feat(client-go): add certs endpoint

---

client/deis.py

fix(client): remove nonexistant certs:update

---

contrib/util/commit-msg

That way you don't loose an entire commit msg if you make a mistake.

feat(commit-msg): don't prevent a commit, only warn

---

docs/_includes/_isolating-etcd-description.rst
docs/managing_deis/index.rst
docs/managing_deis/isolating-etcd.rst
docs/managing_deis/production_deployments.rst
docs/understanding_deis/architecture.rst

docs(platform): document how to isolate etcd

---

builder/Makefile
cache/Makefile
contrib/coreos/user-data.example
controller/Makefile
database/Makefile
docs/contributing/testing.rst
logger/Makefile
registry/Makefile
router/Makefile
store/Makefile
tests/Makefile
tests/bin/prime-docker-images.sh
tests/dockercli/dockercli.go
tests/fixtures/test-etcd/Dockerfile
tests/mock/mock.go

Bump to etcd 2.1.1; properly test it with Jenkins

---

client-go/controller/client/auth.go
client-go/controller/client/http.go
client-go/controller/client/http_test.go
client-go/controller/models/apps/apps.go
client-go/controller/models/builds/builds.go
client-go/controller/models/certs/certs.go
client-go/controller/models/config/config.go
client-go/controller/models/domains/domains.go
client-go/controller/models/keys/keys.go
client-go/controller/models/perms/perms.go
client-go/controller/models/ps/ps.go
client-go/controller/models/releases/releases.go
client-go/controller/models/users/users.go

feat(client-go): decode json error messages

---

client-go/controller/client/http.go

fix(client-go): accept all non error HTTP codes

---

controller/api/exceptions.py
controller/api/models.py
controller/api/tests/test_config.py
docs/managing_deis/backing_up_data.rst
docs/using_deis/config-application.rst
publisher/server/publisher.go
publisher/server/publisher_test.go
tests/Makefile
tests/bin/test-setup.sh
tests/healthcheck_test.go
tests/utils/itutils.go

More documentation is forthcoming.
closes #3813 
closes #4045

feat(platform): add http liveness and readiness health checks

---

tests/utils/itutils.go

fix(tests): abort if warning is found in output

---

client-go/cmd/auth.go
client-go/controller/api/auth.go
client/deis.py
controller/api/__init__.py
controller/api/tests/test_auth.py
controller/api/views.py
docs/reference/api-v1.6.rst
docs/reference/index.rst
version/version.go

Now they no longer need to know a user's password.

feat(controller): allow admins to change a user's password.

---

Vagrantfile
contrib/coreos/user-data.example

fix(flannel): use default iface for starting flannel except vagrant

---

deisctl/backend/fleet/unit.go
deisctl/backend/fleet/unit_test.go

Addresses #4201 
Ping @technosophos

fix(deisctl): fix how target names resolve

---

controller/api/models.py
controller/api/tests/test_config.py

Small improvements over the changes made in #4127. These are small enhancements so there's no rush on these.

ref(controller): code quality enhancements

---

publisher/server/publisher.go

publisher would do a lazy check and convert the etcd keys to an integer.
However, these keys are optional, so if they are unset, an empty string
would be returned from getEtcd(). By explicitly checking if the keys are
set, this will circumvent the strconv errors.
closes #4227

fix(publisher): ignore healthcheck values if unset

---

docs/managing_deis/isolating-planes.rst

Fixes #4240 
Nice catch, @rimusz

docs(deisctl): correct isolation doc mistake

---

client-go/cmd/auth.go
client-go/controller/api/auth.go
client-go/controller/models/auth/auth.go
client-go/controller/models/auth/auth_test.go
client/deis.py
controller/api/tests/test_auth.py
controller/api/views.py
docs/reference/api-v1.6.rst
tests/auth_test.go

feat(controller): allow admins to delete users

---

client-go/deis.go

I used https://github.com/fishworks/deis-accounts/ to test.

feat(client-go): support deis plugins

---

deisctl/backend/fleet/ssh.go

fix(deisctl): fix deisctl ssh <cmd> output

---

docs/installing_deis/aws.rst

docs(aws): require deisctl before provisioning

---

deisctl/backend/backend.go
deisctl/backend/fleet/dock.go
deisctl/cmd/cmd.go
deisctl/cmd/cmd_test.go

fix(deisctl): improve dock name match

---

deisctl/cmd/platform.go

fix(deisctl): clarify registration message

---

docs/installing_deis/baremetal.rst

docs(installing_deis): specify CoreOS for bare metal

---

contrib/aws/provision-aws-cluster.sh

If you're creating an aws stack in a VPC, then your instances may not
have a publicly accessible IP. This caused the fleet check to hang, and
the proxyProtocol setting to fail.
This fixes the provision-aws-cluster script to prefer the public IP if
available, but also try connecting to the private IP.

fix(contrib) AWS instances may only have a private IP

---

docs/managing_deis/production_deployments.rst
docs/understanding_deis/failover.rst
docs/understanding_deis/index.rst

Fixes #3743 
Note we should probably also document how to manually remove ceph and etcd nodes.
Please let me know if I got anything wrong or missed anything.

docs(understanding_deis): add documentation on node failover

---

router/rootfs/bin/build

See http://nginx.org/en/CHANGES.

chore(router): update nginx to 1.9.4

---

contrib/aws/gen-json.py
contrib/coreos/user-data.example

@krancour please test this - I haven't been able to get my local environment set up for ec2 again.
closes #4310

fix(contrib): fix etcd2 data directory on AWS

---

builder/rootfs/etc/confd/templates/builder
builder/rootfs/usr/local/share/shim.dockerfile
builder/rootfs/usr/local/src/slugrunner/Dockerfile

Instead of using a shim Dockerfile, use ONBUILD directives in
slugrunner.

feat(builder): remove Dockerfile shim

---

docs/contributing/hacking.rst
docs/contributing/overview.rst

Your first Deis PR can get you free credit at DigitalOcean. Submit code and send an email to deis@engineyard.com to enter.

docs(hacking): offer DigitalOcean credits to new contributors!

---

Makefile

We've had some failures contacting discovery.etcd.io, leading to a blank discovery-url entry in user-data. This will try up to five times with a 3-second pause in between before giving up.
Thanks to @sgoings for pairing on this!
```console
$ make discovery-url
Wrote https://discovery.etcd.io/25afd6b8c114cc0e7b67a8f4aaac5405 to contrib/coreos/user-data
$ make discovery-url
Failed to contact https://discovery.etcd.io
```

feat(Makefile): retry discovery-url five times

---

builder/docker/docker.go
builder/etcd/etcd.go
builder/rootfs/usr/local/src/slugrunner/runner/init
builder/sshd/server.go

Addresses a few comments from [the rewrite of deis-builder in Go](https://github.com/deis/deis/pull/4273). 
cc @kalbasit @technosophos

style(builder): incorporate remaining code comments

---

database/bin/boot

fix(database): fix db init file perms

---

client/cmd/config.go
client/cmd/limits.go
client/cmd/tags.go

fix(client-go): error deserializing json

---

deisctl/units/deis-builder.service
deisctl/units/deis-cache.service
deisctl/units/deis-controller.service
deisctl/units/deis-database.service
deisctl/units/deis-logger.service
deisctl/units/deis-logspout.service
deisctl/units/deis-mesos-slave.service
deisctl/units/deis-publisher.service
deisctl/units/deis-registry.service
deisctl/units/deis-router.service
deisctl/units/deis-store-admin.service
deisctl/units/deis-store-daemon.service
deisctl/units/deis-store-gateway.service
deisctl/units/deis-store-metadata.service
deisctl/units/deis-store-monitor.service
deisctl/units/deis-swarm-manager.service
deisctl/units/deis-swarm-node.service
deisctl/units/deis-zookeeper.service

fix(*): ensure component containers stop

---

controller/api/models.py

This should fix https://github.com/deis/deis/issues/4377.

fix(controller): healthcheck no longer check non-web processes

---

controller/api/models.py
controller/api/tests/test_app.py
controller/api/tests/test_config.py
logspout/logspout.go

Fixes #3963 
This works by allowing `deis-controller` to write log messages on behalf of an application simply by prefixing them with `[app-name]:`.  `deis-logspout` has been enhanced to recognize such messages and treat the application as the source instead of the `deis-controller`.  `deis-controller` will be treated as the "pid" instead.
Given the following sequence of events:
```
$ deis create arrogant-kirk
$ git push deis master
$ deis logs
```
Old output would have looked like this:
```
2015-09-08T22:02:32UTC deis[api]: kent created initial release
2015-09-08T22:03:49UTC deis[api]: kent deployed 14fb753
2015-09-08T22:03:49UTC deis[api]: kent scaled containers web=1
2015-09-08T22:04:07UTC arrogant-kirk[web.1]: 2015/09/08 22:28:17 listening on 5000...
```
New output looks like this: …

fix(controller): write app event logs via logspout

---

contrib/util/custom-firewall.sh

This also removes `iptables: No chain/target/match by that name.` when the script is executed the first time (is not an error)
closes #4281

fix(firewall): check etcd is running

---

contrib/vagrant/check
contrib/vagrant/config.sh
contrib/vagrant/create
contrib/vagrant/destroy
contrib/vagrant/install
contrib/vagrant/rigger/config.sh

Makes improvements to #4437 and aligns to new interface set forth by https://github.com/deis/rigger/issues/15

contrib(vagrant): move scripts to root vagrant contrib dir

---

controller/api/management/commands/load_db_state_to_etcd.py
controller/api/models.py
controller/bin/boot
docs/managing_deis/backing_up_data.rst

Fixes #4355 
Much thanks to @jgmize for the management command.

feat(controller): publish etcd keys at controller start

---

deisctl/units/units.go

refresh-units seems broken on master.
https://gist.github.com/iancoffey/e44456474718c6bbd91d

fix(deisctl): fix refresh-units as cache is now missing

---

deisctl/client/client.go
deisctl/cmd/cmd_test.go
deisctl/cmd/upgrade.go

- fix stateless upgrade handling
- stop extra router cycling

fix(deisctl): fixes for graceful upgrades.

---

client/cmd/auth.go
client/deis.go
client/parser/utils.go

feat(client): print error messages to stderr

---

contrib/aws/gen-json.py

Less things in the global scope and all the fetching / mapping logic is now together

ref(contrib/aws): wrap coreos ami fetching into a function

---

client/deis.go

fix(client): add newline for usage message

---

builder/rootfs/usr/local/src/slugbuilder/builder/build.sh

Increase timeout for fetching buildpacks

---

router/rootfs/etc/confd/templates/nginx.conf

These config values are dead, they are confusing that they are there. Let's remove them.

Cleanup dead config

---

deisctl/deisctl.go

This commit addresses issue #4627.

style(deisctl): alphabetize deisctl commands

---

client/cmd/builds.go

This was the behavior of the python client.
Fixes #4605

fix(client): read procfile from PWD when pulling

---

Vagrantfile

`COREOS_CHANNEL` and `COREOS_VERSION` are the variables of
particular interest.
fixes #4556

feat(contrib): vagrantfile sources utils.sh

---

contrib/azure/arm-template.json
contrib/azure/parameters.json
docs/installing_deis/azure.rst

Working with Microsoft, we suspect that cluster issues are due to poor disk performance.
/cc @sgoings

fix(contrib/azure): use Azure premium storage

---

client/cmd/apps.go

fix(client): catch and propagate client errors

---

docs/customizing_deis/cli-plugins.rst
docs/customizing_deis/router_settings.rst
docs/installing_deis/baremetal.rst
docs/installing_deis/gce.rst
docs/managing_deis/recovering-ceph-quorum.rst
docs/managing_deis/upgrading-deis.rst
docs/using_deis/deploy-application.rst

Hello!
This PR just fixes a bunch of spelling errors in the docs. 
Thanks!

Common spelling error fixes

---

contrib/linode/apply-firewall.py
contrib/linode/create-linode-user-data.py

Fix discovery url replacement and detection caused by user-data changes.

fix(contrib/linode): fix discovery url issues in deployment scripts

---

database/Dockerfile

wal-e failed to restore from version 9.3.7 in alpine:3.1 to version 9.4.4 in alpine:3.2.
Refs #4708.

fix(database): revert to alpine:3.1 for PostgreSQL

---

contrib/aws/gen-json.py

Fix what #4669 and #4444 broke

fix(contrib): re-introduce data dir mapping for etcd

---

contrib/azure/parameters.json
contrib/linode/provision-linode-cluster.py
contrib/utils.sh
docs/installing_deis/baremetal.rst
docs/installing_deis/gce.rst

chore(*): bump CoreOS to 835.8.0

---

controller/requirements.txt
docs/docs_requirements.txt

See https://github.com/docker/docker-py/blob/master/docs/change_log.md#160

chore(controller): update docker-py to 1.6.0

---

deisctl/cmd/platform.go

`deis logs` works using the in memory logger component

chore(deisctl): update stateless warning message

---

docs/installing_deis/aws.rst

This happened to me, thought I'd contribute a short guide.

Installing on AWS docs: clarify steps after a failure

---

docs/installing_deis/azure.rst

All deployments will be failed if publicDomainName was brank.

docs(installing_deis): Add parameter description about publicDomainName.

---

contrib/azure/parameters.json
contrib/linode/provision-linode-cluster.py
contrib/utils.sh
docs/installing_deis/baremetal.rst
docs/installing_deis/gce.rst

https://coreos.com/releases/#835.11.0

chore(*): bump to CoreOS 835.11.0

---

client/pkg/git/git.go
client/pkg/git/git_test.go

original bug at deis/workflow#279
ref #4858 
ref deis/workflow#280

fix(client): backport deis/workflow#280 to v1

---

contrib/README.md
docs/managing_deis/platform_monitoring.rst

docs(managing_deis): update Sematext agent name and URL

---

docs/customizing_deis/router_settings.rst
router/rootfs/etc/confd/templates/nginx.conf

ref(router): force users to opt into router-nginx-status

---

contrib/coreos/user-data.example
deisctl/units/deis-router.service
logspout/logspout.go
router/cmd/boot/boot.go
router/rootfs/etc/confd/conf.d/nginx.conf.toml
router/rootfs/etc/confd/templates/nginx.conf

This code is now considered dead for v1.13.0 LTS, so let's remove it.
ref #4860 
closes #4882

chore(*): remove k8s scheduler code

---

builder/rootfs/etc/confd/templates/builder

fix(builder): remove empty newline

---

controller/api/tests/__init__.py
controller/api/tests/test_healthcheck.py
controller/api/views.py
controller/bin/boot
controller/deis/urls.py

rebases #4457, changing the URL to /healthz
closes #4219

feat(controller): add simple health check view

---

controller/requirements.txt
docs/docs_requirements.txt

See https://github.com/docker/docker-py/blob/master/docs/change_log.md#170
See also deis/dockerbuilder#20 and deis/workflow#378.

chore(requirements): update docker-py to 1.7.0

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-nodejs/compare/v87...v88

chore(buildpacks): update heroku-buildpack-nodejs to v88

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-php/compare/v92...v94

chore(buildpacks): update heroku-buildpack-php to v94

---

controller/web/static/css/main.css
docs/theme/deis/layout.html

V1 pair to deis/docs-v2#71.
I made it pink rather than blue, because different. Also linking to
gh/deis/workflow until we have a forever home for the v2 documentation.

doc(versions): add version notice for deis docs

---

builder/sshd/server.go

fix(builder): log env tcp requests information to debug

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-python/compare/v77...v78

chore(buildpacks): update heroku-buildpack-python to v78

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-nodejs/compare/v88...v89

chore(buildpacks): update heroku-buildpack-nodejs to v89

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-scala/compare/v66...v67

chore(buildpacks): update heroku-buildpack-scala to v67

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-grails/compare/v19...v20

chore(buildpacks): update heroku-buildpack-grails to v20

---

builder/rootfs/etc/confd/templates/builder

fix(builder): remove temporary build dir on success

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-ruby/compare/v144...v145

chore(buildpacks): update heroku-buildpack-ruby to v145

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-php/compare/v94...v97

chore(buildpacks): update heroku-buildpack-php to v97

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-java/compare/v43...v44

chore(buildpacks): update heroku-buildpack-java to v44

---

builder/git/git.go
builder/sshd/server.go

manually tested.
fixes #4695
fixes #4820

fix(builder): fail on piped command

---

controller/api/serializers.py

for example `deis tags:set dataPlane=true`
refs testing in #4964

fix(controller): tag keys can be lowercase or capital

---

docs/managing_deis/running-deis-without-ceph.rst

docs(managing_deis): recommend m3.medium for RDS

---

contrib/azure/parameters.json
contrib/linode/provision-linode-cluster.py
contrib/utils.sh
deisctl/units/deis-store-volume.service
docs/installing_deis/baremetal.rst
docs/installing_deis/gce.rst

Includes #4985.
Closes #4937.
Refs coreos/bugs#1092

chore(*): bump CoreOS to 899.13.0

---

client/cmd/auth.go
client/controller/models/auth/auth_test.go
controller/api/tests/test_auth.py
controller/api/views.py

Closes #4909.
Backported from deis/controller#391. Thanks @helgi!

fix(auth): return a 409 if a user is cancelled that has apps

---

controller/api/tests/test_app.py

This covers more test cases such as when a user changes the log level.

test(controller): increase app.log() test coverage

---

client/cmd/auth.go
tests/auth_test.go

fix(client): only delete local ~/.deis/client.json if cancelling logged in user

---

controller/requirements.txt

See https://github.com/docker/docker-py/blob/master/docs/change_log.md#172 and deis/controller#427 and deis/dockerbuilder#42.

chore(reqs): update docker-py to 1.7.2

---

contrib/azure/parameters.json
contrib/linode/provision-linode-cluster.py
contrib/utils.sh
docs/installing_deis/baremetal.rst
docs/installing_deis/gce.rst

See https://coreos.com/releases/#899.15.0

chore(*): bump CoreOS to 899.15.0

---

controller/api/management/commands/load_db_state_to_etcd.py

Fix #5017: only load latest config for each app from db to etcd on boot

fix(controller): only load latest config

---

contrib/azure/parameters.json
contrib/linode/provision-linode-cluster.py
contrib/utils.sh
docs/installing_deis/baremetal.rst
docs/installing_deis/gce.rst

See https://coreos.com/releases/#899.17.0

chore(*): bump CoreOS to 899.17.0

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-go/compare/v31...v34

chore(buildpacks): update heroku-buildpack-go to v34

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-nodejs/compare/v89...v90

chore(buildpacks): update heroku-buildpack-nodejs to v90

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-php/compare/v97...v102

chore(buildpacks): update heroku-buildpack-php to v102

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-nodejs/compare/v145...v146

chore(buildpacks): update heroku-buildpack-ruby to v146

---

contrib/azure/parameters.json
contrib/linode/provision-linode-cluster.py
contrib/utils.sh
controller/bin/boot
docs/installing_deis/gce.rst

See https://coreos.com/releases/#1010.5.0

chore(*): bump CoreOS to 1010.5.0

---

builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks

See https://github.com/heroku/heroku-buildpack-go/compare/v34...v41

chore(buildpacks): update heroku-buildpack-go to v41

---

deisctl/units/deis-builder.service

fix(deisctl): replace -c with --cpu-shares

---

docs/using_deis/using-docker-images.rst
docs/using_deis/using-dockerfiles.rst

https://github.com/deis/deis/issues/5064
Also fix mark up for the requirements list.

docs(dockerfiles): Make Bash requirement explicit in the documentation

---

docs/customizing_deis/router_settings.rst
router/rootfs/etc/confd/templates/nginx.conf

Adding the options to turn server tokens on/off and the ability to prevent click-jacking with the `X-Frame-Options` header being present.

feat(router): Add server_tokens option

---

README.md

doc(workflow): add information about workflow

---

logspout/attacher.go

Fixes #5077 
When looking at `docker events` I suspect the culprit is network events which don't have an ID
~~~
core@eu1-cloud-worker-01 ~ $ docker events
2016-08-06T10:28:06.778797416Z container kill 33d983e95a5b5b4521135dc578891f6e113efb752adfa372169aab03609e4903 (image=10.133.20.195:5000/errbit:v3, name=errbit_v3.web.1)
2016-08-06T10:28:07.044499686Z container die 33d983e95a5b5b4521135dc578891f6e113efb752adfa372169aab03609e4903 (image=10.133.20.195:5000/errbit:v3, name=errbit_v3.web.1)
2016-08-06T10:28:07.279972839Z network disconnect db40f046c9996eaea47e48f5f1baa8260f2a1add73dba4e9f91dead80e5edf7d (container=33d983e95a5b5b4521135dc578891f6e113efb752adfa372169aab03609e4903, name=bridge, type=bridge)
2016-08-06T10:28:07.342164511Z container stop …

WIP: fix(logspout): Ignore events with short ID

---

router/rootfs/bin/build

See http://nginx.org/en/CHANGES-1.10

chore(router): upgrade nginx to 1.10.1 stable

---

contrib/azure/arm-template.json

The Microsoft API's have changed since this template was published.  These updates ensure the functionality of the template.

fix(contrib/azure): update template to current API and images

---

controller/api/models.py
controller/api/tests/test_container.py

In some extreme cases (such as a gunicorn worker timeout), Container objects can be orphaned and eventually accumulate. This cleans up any such stale Containers before starting a deploy operation.

fix(models): prune old containers before deploy
